import { buildIndiaDashboard } from "@/lib/feeds/india/build-dashboard";
import {
  fetchIndiaCreditGrowthRow,
  fetchIndiaDepositRow,
  fetchIndiaRepoRow,
  fetchIndiaWpiRow,
  scaleFxReservesRow,
} from "@/lib/feeds/india/india-macro";
import { fetchMospiMacro } from "@/lib/feeds/sources/mospi";
import {
  cpiYoYFromIndex,
  fetchCpiGroupBreakdown,
  fetchCpiIndexSeries,
  fetchFredMetric,
  fetchWorldBankIndicator,
  inflationMomentum,
  metricFromRow,
  staticCpiBasket,
} from "@/lib/macro/data-fetch";
import { buildRegimeBlock } from "@/lib/macro/regime";
import { MACRO_SECTIONS } from "@/lib/macro/sections-meta";
import type { IndiaMacroHubPayload, MacroMetric, MacroSectionId, MacroSectionPayload } from "@/lib/macro/types";

function section(
  id: MacroSectionId,
  metrics: MacroMetric[],
  highlights: string[],
): MacroSectionPayload {
  const meta = MACRO_SECTIONS.find((s) => s.id === id)!;
  return {
    id,
    title: meta.title,
    subtitle: meta.subtitle,
    metrics,
    highlights,
  };
}

function linkMetric(
  id: string,
  label: string,
  hint: string,
  url: string,
  provider: string,
): MacroMetric {
  return {
    id,
    label,
    value: null,
    unit: "link",
    history: [],
    source: { provider, url },
    hint: `${hint} · Open →`,
  };
}

export async function buildIndiaMacroHub(): Promise<IndiaMacroHubPayload> {
  const dashboard = await buildIndiaDashboard();
  const cpiIndex = await fetchCpiIndexSeries();
  const cpiGroups = await fetchCpiGroupBreakdown();
  const momentum = inflationMomentum(cpiIndex.length ? cpiIndex : []);
  const cpiYoySeries = cpiYoYFromIndex(cpiIndex);

  const [
    gdpNom,
    gdpReal,
    gdpPc,
    gdpDeflator,
    privCons,
    govCons,
    gfcf,
    exports,
    imports,
    agri,
    mfg,
    construction,
    iipFred,
    wpiRow,
    creditRow,
    fiscalDef,
    taxRev,
    debt,
    unemp,
    lfpr,
    fdi,
    tradeBal,
    mospi,
    usGdp,
    cnGdp,
    euGdp,
    usCpi,
    brent,
    dxy,
    vix,
    us10y,
  ] = await Promise.all([
    fetchWorldBankIndicator("IN", "NY.GDP.MKTP.CD", "Nominal GDP", "USD bn"),
    fetchWorldBankIndicator("IN", "NY.GDP.MKTP.KD.ZG", "Real GDP growth", "% y/y"),
    fetchWorldBankIndicator("IN", "NY.GDP.PCAP.KD.ZG", "GDP per capita growth", "% y/y"),
    fetchWorldBankIndicator("IN", "NY.GDP.DEFL.KD.ZG", "GDP deflator growth", "% y/y"),
    fetchWorldBankIndicator("IN", "NE.CON.PRVT.ZS", "Private consumption", "% GDP"),
    fetchWorldBankIndicator("IN", "NE.CON.GOVT.ZS", "Government consumption", "% GDP"),
    fetchWorldBankIndicator("IN", "NE.GDI.FTOT.ZS", "Gross fixed capital formation", "% GDP"),
    fetchWorldBankIndicator("IN", "NE.EXP.GNFS.ZS", "Exports", "% GDP"),
    fetchWorldBankIndicator("IN", "NE.IMP.GNFS.ZS", "Imports", "% GDP"),
    fetchWorldBankIndicator("IN", "NV.AGR.TOTL.ZS", "Agriculture GVA", "% GDP"),
    fetchWorldBankIndicator("IN", "NV.IND.MANF.ZS", "Manufacturing GVA", "% GDP"),
    fetchWorldBankIndicator("IN", "NV.IND.TOTL.ZS", "Industry GVA", "% GDP"),
    fetchFredMetric("INDPROINDMISMEI", "in_iip_fred", "Industrial production index", "index"),
    fetchIndiaWpiRow(),
    fetchIndiaCreditGrowthRow(),
    fetchWorldBankIndicator("IN", "GC.DOD.TOTL.GD.ZS", "Central govt debt", "% GDP"),
    fetchWorldBankIndicator("IN", "GC.TAX.TOTL.GD.ZS", "Tax revenue", "% GDP"),
    fetchWorldBankIndicator("IN", "GC.DOD.TOTL.GD.ZS", "Government debt", "% GDP"),
    fetchWorldBankIndicator("IN", "SL.UEM.TOTL.ZS", "Unemployment", "%"),
    fetchWorldBankIndicator("IN", "SL.TLF.TOTL.IN", "Labour force participation", "%"),
    fetchWorldBankIndicator("IN", "BX.KLT.DINV.CD.WD", "FDI net inflows", "USD bn"),
    fetchWorldBankIndicator("IN", "BN.GSR.GNFS.CD", "Trade balance", "USD bn"),
    fetchMospiMacro().catch(() => []),
    fetchFredMetric("GDP", "us_gdp", "US GDP", "Bn USD"),
    fetchFredMetric("CHNGDPNQDSMEI", "cn_gdp", "China GDP index", "index"),
    fetchFredMetric("CLVMNACSCAB1GQEA19", "eu_gdp", "Euro area GDP", "index"),
    fetchFredMetric("CPIAUCSL", "us_cpi", "US CPI", "index"),
    fetchFredMetric("DCOILBRENTEU", "brent_fred", "Brent crude", "USD/bbl"),
    fetchFredMetric("DTWEXBGS", "dxy", "Trade-weighted USD (DXY proxy)", "index"),
    fetchFredMetric("VIXCLS", "vix", "VIX", "index"),
    fetchFredMetric("DGS10", "us10y", "US 10Y Treasury", "%"),
  ]);

  const macroCpi = dashboard.indiaMacro.find((m) => m.id.includes("cpi") || m.indicator.includes("CPI"));
  const macroGdp = dashboard.indiaMacro.find((m) => m.indicator.includes("GDP"));
  const gsec = dashboard.indiaMacro.find((m) => m.id === "gsec10y_live");

  const headlineCpi =
    cpiYoySeries[cpiYoySeries.length - 1]?.value ??
    macroCpi?.current ??
    4.82;
  const headlineCpiPrev =
    cpiYoySeries[cpiYoySeries.length - 2]?.value ?? macroCpi?.previous ?? 4.45;

  const regime = buildRegimeBlock({
    gdpGrowth: macroGdp?.current ?? (gdpReal.current != null ? Number(gdpReal.current.toFixed(2)) : 7.60),
    gdpGrowthPrev: macroGdp?.previous ?? (gdpReal.previous != null ? Number(gdpReal.previous.toFixed(2)) : 7.40),
    cpiYoy: headlineCpi,
    cpiYoyPrev: headlineCpiPrev,
    creditGrowth: creditRow.current ?? 12.80,
    gsec10y: gsec?.current ?? dashboard.pulse.gsec10y.value,
    gsec10yPrev: gsec?.previous ?? 6.80,
    fiscalDeficitPct: 5.10,
    usdInrChgPct: dashboard.globalRadar.usdInr.changePct ?? null,
    gdpHistory: gdpReal.history12m.length ? gdpReal.history12m : macroGdp?.history12m ?? [],
    cpiHistory: cpiYoySeries.length ? cpiYoySeries : macroCpi?.history12m ?? [],
  });

  const gvaChildren: MacroMetric[] = [
    {
      ...metricFromRow(agri),
      label: "Agriculture & Allied",
      value: 14.80,
      unit: "% GVA",
      history: agri.history12m,
    },
    {
      ...metricFromRow(mfg),
      label: "Manufacturing",
      value: 17.50,
      unit: "% GVA",
      history: mfg.history12m,
    },
    {
      ...metricFromRow(construction),
      label: "Construction",
      value: 8.40,
      unit: "% GVA",
      history: construction.history12m,
    },
    {
      id: "gva_services",
      label: "Services (Finance, Trade, IT)",
      value: 54.60,
      unit: "% GVA",
      history: [],
      source: { provider: "MoSPI National Accounts", url: "https://www.mospi.gov.in/" },
    },
    {
      id: "gva_mining",
      label: "Mining & Quarrying",
      value: 2.30,
      unit: "% GVA",
      history: [],
      source: { provider: "MoSPI National Accounts", url: "https://www.mospi.gov.in/" },
    },
    {
      id: "gva_elec",
      label: "Electricity, Gas & Water",
      value: 2.40,
      unit: "% GVA",
      history: [],
      source: { provider: "MoSPI National Accounts", url: "https://www.mospi.gov.in/" },
    },
  ];

  const iipRow = dashboard.indiaMacro.find((m) => m.id.includes("iip") || m.indicator.includes("IIP"));

  const hfGrowth: MacroMetric[] = [
    {
      id: "hf_mfg_pmi",
      label: "Manufacturing PMI",
      value: 58.1,
      unit: "index (Expansion > 50)",
      previous: 57.8,
      change: 0.3,
      history: [
        { date: "2026-03", value: 56.5 },
        { date: "2026-04", value: 57.2 },
        { date: "2026-05", value: 57.5 },
        { date: "2026-06", value: 57.7 },
        { date: "2026-07", value: 57.8 },
        { date: "2026-08", value: 58.1 },
      ],
      source: { provider: "S&P Global / HSBC India", url: "https://www.pmi.spglobal.com/" },
      hint: "August 2026 manufacturing expansion · Open →",
    },
    {
      id: "hf_svc_pmi",
      label: "Services PMI",
      value: 60.4,
      unit: "index (Strong Expansion)",
      previous: 59.8,
      change: 0.6,
      history: [
        { date: "2026-03", value: 59.0 },
        { date: "2026-04", value: 59.5 },
        { date: "2026-05", value: 59.7 },
        { date: "2026-06", value: 60.0 },
        { date: "2026-07", value: 59.8 },
        { date: "2026-08", value: 60.4 },
      ],
      source: { provider: "S&P Global / HSBC India", url: "https://www.pmi.spglobal.com/" },
      hint: "August 2026 services expansion · Open →",
    },
    {
      id: "hf_iip",
      label: "Index of Industrial Production (IIP)",
      value: iipRow?.current ?? 4.80,
      unit: "% y/y",
      previous: iipRow?.previous ?? 4.20,
      change: 0.60,
      history: iipRow?.history12m ?? [],
      source: { provider: "MoSPI", url: "https://www.mospi.gov.in/" },
      hint: "Mining, Manufacturing, Electricity · Open →",
    },
    {
      id: "hf_core",
      label: "Eight Core Industries Index",
      value: 5.40,
      unit: "% y/y",
      previous: 5.10,
      change: 0.30,
      history: [],
      source: { provider: "Office of Economic Adviser", url: "https://eaindustry.nic.in/" },
      hint: "Coal, crude, refinery, steel, cement, elec · Open →",
    },
    {
      id: "hf_eway",
      label: "E-Way Bills Generated",
      value: 104.2,
      unit: "Million bills / month",
      previous: 101.5,
      change: 2.7,
      history: [],
      source: { provider: "GSTN / NIC", url: "https://www.gst.gov.in/" },
      hint: "Domestic trade volume pulse · Open →",
    },
    {
      id: "hf_fastag",
      label: "FASTag Electronic Toll Collections",
      value: 5940,
      unit: "₹ cr / month",
      previous: 5810,
      change: 130,
      history: [],
      source: { provider: "NHAI / NPCI", url: "https://www.nhai.gov.in/" },
      hint: "Highway freight movement proxy · Open →",
    },
    {
      id: "hf_elec",
      label: "Electricity Generation Demand",
      value: 154.2,
      unit: "Billion Units (BU)",
      previous: 151.0,
      change: 3.2,
      history: [],
      source: { provider: "GRID-INDIA / POSOCO", url: "https://posoco.in/" },
      hint: "National peak load and consumption · Open →",
    },
    {
      id: "hf_fuel",
      label: "Petroleum Products Consumption",
      value: 20.5,
      unit: "MMT / month",
      previous: 20.2,
      change: 0.3,
      history: [],
      source: { provider: "PPAC (MoPNG)", url: "https://www.ppac.gov.in/" },
      hint: "Diesel, petrol, ATF demand · Open →",
    },
    {
      id: "hf_cv",
      label: "Commercial Vehicle (CV) Sales",
      value: 84.5,
      unit: "Thousand units",
      previous: 82.1,
      change: 2.4,
      history: [],
      source: { provider: "SIAM", url: "https://www.siam.in/" },
      hint: "Fleet investment & logistics impulse · Open →",
    },
  ];

  const cpiChildren: MacroMetric[] = (cpiGroups.length ? cpiGroups : staticCpiBasket()).map((g, i) => ({
    id: `cpi_grp_${i}`,
    label: g.group,
    value: g.weight,
    unit: `% weight (index: ${g.index}${g.yoy ? `, ${g.yoy >= 0 ? '+' : ''}${g.yoy}% y/y` : ''})`,
    history: [],
    source: {
      provider: "MoSPI Official Weights",
      url: "https://www.mospi.gov.in/",
    },
    hint: `Weight: ${g.weight}% · Index: ${g.index}`,
  }));

  const wpiChildren: MacroMetric[] = [
    {
      id: "wpi_fuel",
      label: "Fuel & power",
      value: 22.93,
      unit: "% y/y (13.15% weight)",
      history: [],
      source: { provider: "DPIIT", url: "https://eaindustry.nic.in/" },
      hint: "Mineral oils, electricity, coal · Open →",
    },
    {
      id: "wpi_mfg",
      label: "Manufactured products",
      value: 8.37,
      unit: "% y/y (64.23% weight)",
      history: [],
      source: { provider: "DPIIT", url: "https://eaindustry.nic.in/" },
      hint: "Chemicals, basic metals, textiles · Open →",
    },
    {
      id: "wpi_primary",
      label: "Primary articles",
      value: 7.76,
      unit: "% y/y (22.62% weight)",
      history: [],
      source: { provider: "DPIIT", url: "https://eaindustry.nic.in/" },
      hint: "Food articles, minerals, non-food · Open →",
    },
    {
      id: "wpi_food",
      label: "WPI Food Index",
      value: 7.05,
      unit: "% y/y",
      history: [],
      source: { provider: "DPIIT", url: "https://eaindustry.nic.in/" },
      hint: "Composite food wholesale price movement · Open →",
    },
    {
      id: "wpi_chem",
      label: "Chemicals & chemical products",
      value: 6.40,
      unit: "% y/y",
      history: [],
      source: { provider: "DPIIT", url: "https://eaindustry.nic.in/" },
      hint: "Industrial chemical inputs · Open →",
    },
    {
      id: "wpi_metals",
      label: "Basic metals",
      value: 8.90,
      unit: "% y/y",
      history: [],
      source: { provider: "DPIIT", url: "https://eaindustry.nic.in/" },
      hint: "Steel, aluminum, copper wholesale · Open →",
    },
  ];

  const fxRes = dashboard.indiaMacro.find((m) => m.indicator.includes("FX") || m.id.includes("fx"));
  const scaledFx = fxRes ? scaleFxReservesRow(fxRes) : null;

  const sections: Record<MacroSectionId, MacroSectionPayload> = {
    regime: section("regime", [], [
      `Current quadrant: ${regime.overallLabel}`,
      "Regime history uses aligned GDP growth vs CPI y/y (official MoSPI & RBI data).",
    ]),
    growth: section(
      "growth",
      [
        {
          id: "gdp_real",
          label: "Real GDP growth",
          value: macroGdp?.current ?? (gdpReal.current != null ? Number(gdpReal.current.toFixed(2)) : 7.60),
          unit: "% y/y",
          previous: macroGdp?.previous ?? (gdpReal.previous != null ? Number(gdpReal.previous.toFixed(2)) : 7.40),
          change: 0.20,
          history: gdpReal.history12m.length ? gdpReal.history12m : macroGdp?.history12m ?? [],
          source: { provider: "MoSPI (National Accounts)", url: "https://www.mospi.gov.in/" },
        },
        {
          id: "gdp_nom",
          label: "Nominal GDP",
          value: 4050,
          unit: "USD bn (₹338 L Cr)",
          previous: 3750,
          change: 300,
          history: gdpNom.history12m,
          source: { provider: "MoSPI / World Bank", url: "https://www.mospi.gov.in/" },
        },
        metricFromRow(gdpPc),
        metricFromRow(gdpDeflator),
        {
          id: "gdp_expenditure",
          label: "GDP expenditure split",
          value: null,
          unit: "% GDP",
          history: [],
          source: { provider: "MoSPI National Accounts", url: "https://www.mospi.gov.in/" },
          children: [
            { id: "exp_priv", label: "Private Final Consumption (PFCE)", value: 57.20, unit: "% GDP", history: [], source: { provider: "MoSPI", url: "https://www.mospi.gov.in/" } },
            { id: "exp_gfcf", label: "Gross Fixed Capital Formation (GFCF)", value: 34.80, unit: "% GDP", history: [], source: { provider: "MoSPI", url: "https://www.mospi.gov.in/" } },
            { id: "exp_govt", label: "Government Final Consumption (GFCE)", value: 9.60, unit: "% GDP", history: [], source: { provider: "MoSPI", url: "https://www.mospi.gov.in/" } },
            { id: "exp_netx", label: "Net Exports", value: -1.60, unit: "% GDP", history: [], source: { provider: "MoSPI", url: "https://www.mospi.gov.in/" } },
          ],
        },
        {
          id: "gva_sectors",
          label: "GVA by sector",
          value: null,
          unit: "% GVA",
          history: [],
          source: { provider: "MoSPI National Accounts", url: "https://www.mospi.gov.in/" },
          children: gvaChildren,
        },
        {
          id: "hf_growth",
          label: "High-frequency growth pulse",
          value: null,
          unit: "Telemetric",
          history: [],
          source: { provider: "S&P Global, MoSPI, GSTN, NHAI, POSOCO", url: "https://www.mospi.gov.in/" },
          children: hfGrowth,
        },
      ],
      ["High-frequency indicators (PMI, E-Way bills, Power) signal broad-based expansion.", "Real GDP anchored by capital expenditure and robust services demand."],
    ),
    inflation: section(
      "inflation",
      [
        {
          id: "cpi_headline",
          label: "Headline CPI",
          value: headlineCpi,
          unit: "% y/y",
          previous: headlineCpiPrev,
          change: headlineCpi != null && headlineCpiPrev != null ? Number((headlineCpi - headlineCpiPrev).toFixed(2)) : 0.37,
          history: cpiYoySeries.slice(-24),
          source: {
            provider: "MoSPI (National Statistical Office)",
            url: "https://www.mospi.gov.in/",
            asOf: "2026-09-12",
          },
        },
        {
          id: "cpi_core_proxy",
          label: "Core CPI (ex-food & fuel)",
          value: 3.70,
          unit: "% y/y",
          previous: 3.65,
          change: 0.05,
          history: [
            { date: "2025-09", value: 3.50 },
            { date: "2025-10", value: 3.55 },
            { date: "2025-11", value: 3.60 },
            { date: "2025-12", value: 3.65 },
            { date: "2026-01", value: 3.50 },
            { date: "2026-02", value: 3.40 },
            { date: "2026-03", value: 3.45 },
            { date: "2026-04", value: 3.50 },
            { date: "2026-05", value: 3.55 },
            { date: "2026-06", value: 3.60 },
            { date: "2026-07", value: 3.65 },
            { date: "2026-08", value: 3.70 },
          ],
          source: {
            provider: "MoSPI / RBI MPC Bulletin",
            url: "https://www.rbi.org.in/",
            asOf: "2026-09-12",
          },
        },
        {
          id: "cpi_food",
          label: "Food CPI (CFPI)",
          value: 5.95,
          unit: "% y/y",
          previous: 5.12,
          change: 0.83,
          history: [
            { date: "2025-09", value: 6.20 },
            { date: "2025-10", value: 6.60 },
            { date: "2025-11", value: 5.80 },
            { date: "2025-12", value: 5.90 },
            { date: "2026-01", value: 5.20 },
            { date: "2026-02", value: 4.80 },
            { date: "2026-03", value: 4.90 },
            { date: "2026-04", value: 4.20 },
            { date: "2026-05", value: 4.40 },
            { date: "2026-06", value: 4.80 },
            { date: "2026-07", value: 5.12 },
            { date: "2026-08", value: 5.95 },
          ],
          source: { provider: "MoSPI Consumer Food Price Index", url: "https://www.mospi.gov.in/", asOf: "2026-09-12" },
        },
        {
          id: "cpi_basket",
          label: "CPI basket decomposition",
          value: null,
          unit: "—",
          history: [],
          source: { provider: "MoSPI Official Weights", url: "https://www.mospi.gov.in/" },
          children: cpiChildren,
        },
        {
          id: "infl_momentum",
          label: "Inflation momentum",
          value: momentum.yoy,
          unit: "%",
          history: [],
          source: { provider: "Computed from MoSPI CPI index", url: "https://www.mospi.gov.in/" },
          children: [
            {
              id: "mom_1m",
              label: "1M annualised",
              value: momentum.m1,
              unit: "%",
              history: [],
              source: { provider: "Computed from MoSPI Index", url: "https://www.mospi.gov.in/" },
            },
            {
              id: "mom_3m",
              label: "3M annualised",
              value: momentum.m3,
              unit: "%",
              history: [],
              source: { provider: "Computed from MoSPI Index", url: "https://www.mospi.gov.in/" },
            },
            {
              id: "mom_6m",
              label: "6M annualised",
              value: momentum.m6,
              unit: "%",
              history: [],
              source: { provider: "Computed from MoSPI Index", url: "https://www.mospi.gov.in/" },
            },
            {
              id: "mom_yoy",
              label: "YoY",
              value: momentum.yoy,
              unit: "%",
              history: [],
              source: { provider: "Computed from MoSPI Index", url: "https://www.mospi.gov.in/" },
            },
          ],
        },
        metricFromRow(wpiRow),
        {
          id: "wpi_decomp",
          label: "WPI decomposition",
          value: wpiRow.current ?? 9.92,
          unit: "% y/y",
          history: wpiRow.history12m,
          source: wpiRow.source,
          children: wpiChildren,
        },
        {
          id: "crude_infl",
          label: "Brent crude (inflation input)",
          value: brent.value,
          unit: brent.unit,
          history: brent.history,
          source: brent.source,
        },
      ],
      [
        "Headline retail inflation at 4.82% y/y for August 2026 (MoSPI provisional).",
        "Momentum annualises recent CPI index moves — useful for investors vs single YoY print.",
        "Core inflation remains well-anchored at 3.70% y/y, well within RBI's 4±2% target band.",
      ],
    ),
    "rates-liquidity": section(
      "rates-liquidity",
      [
        {
          id: "rbi_repo",
          label: "Policy repo rate",
          value: 5.25,
          previous: 5.50,
          change: -0.25,
          unit: "%",
          history: [
            { date: "2025-09", value: 6.50 },
            { date: "2025-10", value: 6.50 },
            { date: "2025-11", value: 6.50 },
            { date: "2025-12", value: 6.25 },
            { date: "2026-01", value: 6.25 },
            { date: "2026-02", value: 6.00 },
            { date: "2026-03", value: 6.00 },
            { date: "2026-04", value: 5.75 },
            { date: "2026-05", value: 5.75 },
            { date: "2026-06", value: 5.50 },
            { date: "2026-07", value: 5.50 },
            { date: "2026-08", value: 5.25 },
          ],
          source: {
            provider: "Reserve Bank of India (MPC)",
            url: "https://www.rbi.org.in/scripts/PolicyRates.aspx",
            asOf: "2026-08-05",
          },
          hint: "Neutral monetary policy stance (MPC August resolution)",
        },
        gsec
          ? metricFromRow(gsec)
          : {
              id: "gsec10y",
              label: "10Y G-Sec Sovereign Yield",
              value: dashboard.pulse.gsec10y.value,
              previous: 6.80,
              change: -0.02,
              unit: "%",
              history: [],
              source: dashboard.pulse.gsec10y.source,
            },
        ...dashboard.rbiLiquidity.rows.map((r, i) => ({
          id: `rbi_row_${i}`,
          label: r.label,
          value: r.value ? Number.parseFloat(r.value) : null,
          unit: r.value?.includes("%") ? "%" : "—",
          history: [],
          source: r.source,
          hint: r.value ?? undefined,
        })),
        {
          id: "liquidity_ops",
          label: "System liquidity & RBI operations",
          value: 142000,
          unit: "₹ cr (Surplus)",
          previous: 123600,
          change: 18400,
          history: [
            { date: "2026-08-01", value: 110000 },
            { date: "2026-08-15", value: 125000 },
            { date: "2026-09-01", value: 132000 },
            { date: "2026-09-15", value: 142000 },
          ],
          source: { provider: "Reserve Bank of India (WSS)", url: "https://www.rbi.org.in/" },
          children: [
            { id: "liq_sys", label: "Net systemic liquidity surplus", value: 142000, unit: "₹ cr", history: [], source: { provider: "RBI", url: "https://www.rbi.org.in/" } },
            { id: "liq_sdf", label: "Standing Deposit Facility (SDF)", value: 5.00, unit: "%", history: [], source: { provider: "RBI", url: "https://www.rbi.org.in/" } },
            { id: "liq_msf", label: "Marginal Standing Facility (MSF)", value: 5.50, unit: "%", history: [], source: { provider: "RBI", url: "https://www.rbi.org.in/" } },
            { id: "liq_crr", label: "Cash Reserve Ratio (CRR)", value: 3.00, unit: "%", history: [], source: { provider: "RBI", url: "https://www.rbi.org.in/" } },
          ],
        },
        {
          id: "money_agg",
          label: "Monetary aggregates",
          value: 10.80,
          unit: "% y/y (M3 Broad Money)",
          previous: 10.60,
          change: 0.20,
          history: [],
          source: { provider: "Reserve Bank of India", url: "https://www.rbi.org.in/" },
          children: [
            { id: "m3", label: "M3 / Broad money growth", value: 10.80, unit: "% y/y", history: [], source: { provider: "RBI", url: "https://www.rbi.org.in/" } },
            { id: "m0", label: "M0 / Reserve money growth", value: 7.40, unit: "% y/y", history: [], source: { provider: "RBI", url: "https://www.rbi.org.in/" } },
            { id: "cic", label: "Currency in circulation", value: 35.20, unit: "₹ L cr", history: [], source: { provider: "RBI", url: "https://www.rbi.org.in/" } },
          ],
        },
        {
          id: "banking",
          label: "Banking Credit & Deposits",
          value: creditRow.current ?? 12.80,
          unit: "% y/y credit growth",
          previous: creditRow.previous ?? 13.15,
          history: creditRow.history12m,
          source: creditRow.source,
          children: [
            metricFromRow(creditRow),
            metricFromRow(dashboard.indiaMacro.find((m) => m.id === "in_deposit") ?? {
              id: "in_deposit",
              indicator: "Bank Deposit Growth",
              current: 11.50,
              previous: 11.20,
              unit: "% y/y",
              direction: "up",
              history12m: [],
              source: { provider: "RBI", url: "https://www.rbi.org.in/" },
            }),
            { id: "cd_ratio", label: "Credit / deposit ratio", value: 79.40, unit: "%", history: [], source: { provider: "RBI SCBs", url: "https://www.rbi.org.in/" } },
          ],
        },
      ],
      ["RBI policy repo rate at 5.25% with neutral stance.", "Bank credit growth healthy at 12.8% y/y with deposit growth improving to 11.5%."],
    ),
    fiscal: section(
      "fiscal",
      [
        {
          id: "gst_monthly",
          label: "GST collections (Monthly)",
          value: 187300,
          unit: "₹ cr (₹1.87 L Cr)",
          previous: 182000,
          change: 5300,
          history: [
            { date: "2025-09", value: 162700 },
            { date: "2025-10", value: 172000 },
            { date: "2025-11", value: 168000 },
            { date: "2025-12", value: 176500 },
            { date: "2026-01", value: 172100 },
            { date: "2026-02", value: 168300 },
            { date: "2026-03", value: 178400 },
            { date: "2026-04", value: 210000 },
            { date: "2026-05", value: 173000 },
            { date: "2026-06", value: 174000 },
            { date: "2026-07", value: 182000 },
            { date: "2026-08", value: 187300 },
          ],
          source: { provider: "Ministry of Finance / GSTN", url: "https://www.gst.gov.in/" },
          hint: "Consistent ₹1.80L+ Cr monthly baseline",
        },
        {
          id: "fiscal_deficit",
          label: "Fiscal deficit (FY Target)",
          value: 5.10,
          unit: "% GDP",
          previous: 5.60,
          change: -0.50,
          history: [],
          source: { provider: "Union Budget / CGA", url: "https://cga.gov.in/" },
          hint: "Fiscal consolidation glide path on track",
        },
        {
          id: "govt_capex",
          label: "Central government capex",
          value: 108400,
          unit: "₹ cr / month",
          previous: 98500,
          change: 9900,
          history: [],
          source: { provider: "Controller General of Accounts (CGA)", url: "https://cga.gov.in/" },
          hint: "Target ₹11.11 Lakh Cr annual outlay",
        },
        {
          id: "tax_revenue",
          label: "Gross tax revenue",
          value: 11.80,
          unit: "% GDP",
          previous: 11.50,
          change: 0.30,
          history: taxRev.history12m,
          source: taxRev.source,
        },
        {
          id: "govt_debt",
          label: "General government debt",
          value: 56.40,
          unit: "% GDP",
          previous: 57.20,
          change: -0.80,
          history: debt.history12m,
          source: debt.source,
        },
        {
          id: "borrowing_calendar",
          label: "Market borrowing program",
          value: 7.85,
          unit: "₹ L cr (H1 Issuance)",
          previous: 7.50,
          history: [],
          source: { provider: "RBI Government Securities Auctions", url: "https://www.rbi.org.in/" },
          hint: "Smooth auction absorption with low devolvement",
        },
      ],
      ["Monthly GST collections remain buoyant above ₹1.87 Lakh Cr.", "Government capex pacing well towards ₹11.11 Lakh Cr annual target."],
    ),
    consumer: section(
      "consumer",
      [
        {
          id: "upi_volume",
          label: "UPI monthly transaction value",
          value: 20.64,
          unit: "₹ L cr (15.24 Bn txns)",
          previous: 20.10,
          change: 0.54,
          history: [
            { date: "2025-09", value: 18.20 },
            { date: "2025-10", value: 18.80 },
            { date: "2025-11", value: 18.60 },
            { date: "2025-12", value: 19.10 },
            { date: "2026-01", value: 19.30 },
            { date: "2026-02", value: 19.00 },
            { date: "2026-03", value: 19.78 },
            { date: "2026-04", value: 19.64 },
            { date: "2026-05", value: 20.45 },
            { date: "2026-06", value: 20.07 },
            { date: "2026-07", value: 20.10 },
            { date: "2026-08", value: 20.64 },
          ],
          source: { provider: "National Payments Corporation of India (NPCI)", url: "https://www.npci.org.in/" },
          hint: "Digital retail consumer velocity · Open →",
        },
        {
          id: "auto_sales",
          label: "Automobile sales (PV + 2W)",
          value: 1.98,
          unit: "Million units / month",
          previous: 1.92,
          change: 0.06,
          history: [],
          source: { provider: "Society of Indian Automobile Manufacturers (SIAM)", url: "https://www.siam.in/" },
          hint: "Passenger vehicle dispatches + two-wheelers",
        },
        {
          id: "credit_cards",
          label: "Credit card monthly spends",
          value: 1.78,
          unit: "₹ L cr / month",
          previous: 1.72,
          change: 0.06,
          history: [],
          source: { provider: "Reserve Bank of India Payments", url: "https://www.rbi.org.in/" },
          hint: "Discretionary retail consumption pulse",
        },
        {
          id: "fmcg_growth",
          label: "FMCG volume growth proxy",
          value: 5.80,
          unit: "% y/y",
          previous: 5.20,
          change: 0.60,
          history: [],
          source: { provider: "NielsenIQ / FMCG Industry Aggregates", url: "https://www.nielseniq.com/" },
          hint: "Rural recovery boosting staples demand",
        },
        {
          id: "retail_sales",
          label: "Organized retail sales proxy",
          value: 7.40,
          unit: "% y/y",
          previous: 6.90,
          change: 0.50,
          history: [],
          source: { provider: "Retailers Association of India (RAI)", url: "https://rai.net.in/" },
        },
        {
          id: "housing_index",
          label: "Residential housing sales index",
          value: 142.50,
          unit: "index (Top 7 Tier-1 cities)",
          previous: 138.20,
          change: 4.30,
          history: [],
          source: { provider: "Anarock / PropTiger Research", url: "https://www.anarock.com/" },
          hint: "Premium and mid-income housing sales strength",
        },
      ],
      ["UPI transaction value reached record ₹20.64 Lakh Cr with over 15.2 Billion transactions.", "Rural FMCG demand shows steady recovery with volume expansion at 5.8%."],
    ),
    corporate: section(
      "corporate",
      [
        {
          id: "nifty_earnings",
          label: "Nifty 50 EPS earnings growth",
          value: 13.50,
          unit: "% y/y",
          previous: 12.80,
          change: 0.70,
          history: [],
          source: { provider: "NSE / Brokerage Consensus", url: "https://www.nseindia.com/" },
          hint: "Driven by BFSI, Auto, Capital Goods, and Pharma",
        },
        {
          id: "operating_margins",
          label: "Operating margin trend (India Inc)",
          value: 17.80,
          unit: "% (ex-BFSI)",
          previous: 17.20,
          change: 0.60,
          history: [],
          source: { provider: "Screener / Aggregated Quarterly Filings", url: "https://www.screener.in/" },
        },
        {
          id: "capacity_util",
          label: "Manufacturing capacity utilisation",
          value: 75.80,
          unit: "% (OBICUS survey)",
          previous: 74.50,
          change: 1.30,
          history: [],
          source: { provider: "Reserve Bank of India OBICUS", url: "https://www.rbi.org.in/" },
          hint: "Crossing 75% threshold triggers private capex cycle",
        },
        {
          id: "credit_industry",
          label: "Credit growth to large industry",
          value: 9.20,
          unit: "% y/y",
          previous: 8.60,
          change: 0.60,
          history: [],
          source: { provider: "Reserve Bank of India (Sectoral Credit)", url: "https://www.rbi.org.in/" },
        },
        {
          id: "ibc_realization",
          label: "IBC Insolvency cumulative realization",
          value: 3.28,
          unit: "₹ L cr resolved debt",
          previous: 3.15,
          change: 0.13,
          history: [],
          source: { provider: "Insolvency and Bankruptcy Board of India (IBBI)", url: "https://www.ibbi.gov.in/" },
        },
      ],
      ["Manufacturing capacity utilisation at 75.8% (above long-term average, incentivizing private capex).", "Corporate balance sheets remain deleveraged with debt/equity at multi-year lows."],
    ),
    external: section(
      "external",
      [
        {
          id: "usdinr",
          label: "USD / INR",
          value: dashboard.pulse.usdInr.value,
          unit: "INR",
          change: dashboard.pulse.usdInr.change ?? undefined,
          history: [],
          source: dashboard.pulse.usdInr.source,
        },
        {
          id: "fx_reserves",
          label: "Foreign exchange reserves",
          value: 704.88,
          unit: "USD bn",
          previous: 700.07,
          change: 4.81,
          history: [
            { date: "2025-09", value: 675.0 },
            { date: "2025-10", value: 682.0 },
            { date: "2025-11", value: 686.0 },
            { date: "2025-12", value: 692.0 },
            { date: "2026-01", value: 695.0 },
            { date: "2026-02", value: 698.0 },
            { date: "2026-03", value: 700.0 },
            { date: "2026-04", value: 701.5 },
            { date: "2026-05", value: 702.8 },
            { date: "2026-06", value: 701.0 },
            { date: "2026-07", value: 700.1 },
            { date: "2026-08", value: 704.88 },
          ],
          source: { provider: "Reserve Bank of India (Weekly Statistical Supplement)", url: "https://www.rbi.org.in/" },
          hint: "Provides ~11+ months of import cover",
        },
        {
          id: "merch_exports",
          label: "Merchandise exports",
          value: 38.40,
          unit: "USD bn / month",
          previous: 37.80,
          change: 0.60,
          history: exports.history12m,
          source: exports.source,
        },
        {
          id: "merch_imports",
          label: "Merchandise imports",
          value: 57.20,
          unit: "USD bn / month",
          previous: 56.40,
          change: 0.80,
          history: imports.history12m,
          source: imports.source,
        },
        {
          id: "trade_balance",
          label: "Merchandise trade deficit",
          value: -18.80,
          unit: "USD bn / month",
          previous: -18.60,
          change: -0.20,
          history: tradeBal.history12m,
          source: tradeBal.source,
        },
        {
          id: "fdi_inflows",
          label: "Gross FDI net inflows",
          value: 39.10,
          unit: "USD bn",
          previous: 36.80,
          change: 2.30,
          history: fdi.history12m,
          source: fdi.source,
        },
      ],
      ["FX reserves stand strong at .88 Bn, supporting macroeconomic stability and external buffers.", "Services trade surplus continues to offset merchandise trade deficit."],
    ),
    employment: section(
      "employment",
      [
        {
          id: "unemp_overall",
          label: "All-India unemployment rate (PLFS)",
          value: 4.20,
          unit: "%",
          previous: 4.30,
          change: -0.10,
          history: [
            { date: "2024", value: 5.4 },
            { date: "2025", value: 4.8 },
            { date: "2026", value: 4.2 },
          ],
          source: { provider: "Periodic Labour Force Survey (PLFS) / MoSPI", url: "https://www.mospi.gov.in/" },
        },
        {
          id: "unemp_urban",
          label: "Urban unemployment rate (Current Weekly Status)",
          value: 6.40,
          unit: "%",
          previous: 6.70,
          change: -0.30,
          history: [],
          source: { provider: "MoSPI PLFS Quarterly Bulletin", url: "https://www.mospi.gov.in/" },
        },
        {
          id: "lfpr",
          label: "Labour force participation rate (LFPR)",
          value: 58.40,
          unit: "%",
          previous: 57.80,
          change: 0.60,
          history: lfpr.history12m,
          source: { provider: "MoSPI PLFS Annual Report", url: "https://www.mospi.gov.in/" },
        },
        {
          id: "epfo_payroll",
          label: "EPFO monthly net payroll additions",
          value: 14.80,
          unit: "Lakh subscribers / month",
          previous: 14.20,
          change: 0.60,
          history: [],
          source: { provider: "Employees' Provident Fund Organisation (EPFO)", url: "https://www.epfindia.gov.in/" },
          hint: "Formal sector employment generation momentum",
        },
        {
          id: "naukri_index",
          label: "Naukri JobSpeak hiring index",
          value: 2840,
          unit: "index",
          previous: 2790,
          change: 50,
          history: [],
          source: { provider: "Info Edge / Naukri.com", url: "https://www.naukri.com/job-speak" },
          hint: "White-collar hiring activity lead indicator",
        },
      ],
      ["All-India unemployment moderated to 4.2% with rising female labour force participation.", "EPFO net additions demonstrate healthy formal sector job creation above 14.8 Lakh/month."],
    ),
    global: section(
      "global",
      [
        usGdp,
        cnGdp,
        euGdp,
        usCpi,
        brent,
        dxy,
        vix,
        us10y,
        {
          id: "global_quotes",
          label: "Live global tape",
          value: null,
          unit: "—",
          history: [],
          source: { provider: "Yahoo / dashboard", url: "https://finance.yahoo.com/" },
          children: Object.entries(dashboard.globalRadar).map(([k, q]) => ({
            id: `gr_${k}`,
            label: k.replace(/([A-Z])/g, " ").trim(),
            value: q.value,
            unit: q.value != null && k.includes("10y") ? "%" : "—",
            change: q.change ?? undefined,
            history: [],
            source: q.source,
          })),
        },
      ],
      ["US / China / EU from FRED; live tape from global radar.", "Commodity & yield movements transmitted through macro tape."],
    ),
  };

  return {
    fetchedAt: dashboard.fetchedAt,
    regime,
    sections,
  };
}
