import { buildIndiaDashboard } from "@/lib/feeds/india/build-dashboard";
import { fetchIndiaCreditGrowthRow, fetchIndiaWpiRow } from "@/lib/feeds/india/india-macro";
import { fetchMospiMacro } from "@/lib/feeds/sources/mospi";
import {
  cpiYoYFromIndex,
  fetchCpiGroupBreakdown,
  fetchCpiIndexSeries,
  fetchFredMetric,
  fetchWorldBankIndicator,
  inflationMomentum,
  metricFromRow,
  staticCpiBasket,
} from "@/lib/macro/data-fetch";
import { buildRegimeBlock } from "@/lib/macro/regime";
import { applyCollectorMetric, loadCollectorMacroMap } from "@/lib/macro/from-collector";
import { MACRO_SECTIONS } from "@/lib/macro/sections-meta";
import type { IndiaMacroHubPayload, MacroMetric, MacroSectionId, MacroSectionPayload } from "@/lib/macro/types";

function section(
  id: MacroSectionId,
  metrics: MacroMetric[],
  highlights: string[],
): MacroSectionPayload {
  const meta = MACRO_SECTIONS.find((s) => s.id === id)!;
  return {
    id,
    title: meta.title,
    subtitle: meta.subtitle,
    metrics,
    highlights,
  };
}

export async function buildIndiaMacroHub(): Promise<IndiaMacroHubPayload> {
  const dashboard = await buildIndiaDashboard();
  const collector = await loadCollectorMacroMap([
    "in_gst_monthly_cr",
    "in_upi_monthly_lc",
    "in_epfo_payroll_lakh",
    "in_naukri_jobspeak",
    "in_fx_reserves_usd_bn",
    "in_nifty50_yoy_pct",
    "rbi_repo",
    "rbi_net_liquidity",
    "india_fx_reserves_ex_gold",
  ]);
  const cpiIndex = await fetchCpiIndexSeries();
  const cpiGroups = await fetchCpiGroupBreakdown();
  const momentum = inflationMomentum(cpiIndex.length ? cpiIndex : []);
  const cpiYoySeries = cpiYoYFromIndex(cpiIndex);

  const [
    gdpNom,
    gdpReal,
    gdpPc,
    gdpDeflator,
    _privCons,
    _govCons,
    _gfcf,
    exports,
    imports,
    agri,
    mfg,
    construction,
    _iipFred,
    wpiRow,
    creditRow,
    _fiscalDef,
    taxRev,
    debt,
    _unemp,
    lfpr,
    fdi,
    tradeBal,
    _mospi,
    usGdp,
    cnGdp,
    euGdp,
    usCpi,
    brent,
    dxy,
    vix,
    us10y,
  ] = await Promise.all([
    fetchWorldBankIndicator("IN", "NY.GDP.MKTP.CD", "Nominal GDP", "USD bn"),
    fetchWorldBankIndicator("IN", "NY.GDP.MKTP.KD.ZG", "Real GDP growth", "% y/y"),
    fetchWorldBankIndicator("IN", "NY.GDP.PCAP.KD.ZG", "GDP per capita growth", "% y/y"),
    fetchWorldBankIndicator("IN", "NY.GDP.DEFL.KD.ZG", "GDP deflator growth", "% y/y"),
    fetchWorldBankIndicator("IN", "NE.CON.PRVT.ZS", "Private consumption", "% GDP"),
    fetchWorldBankIndicator("IN", "NE.CON.GOVT.ZS", "Government consumption", "% GDP"),
    fetchWorldBankIndicator("IN", "NE.GDI.FTOT.ZS", "Gross fixed capital formation", "% GDP"),
    fetchWorldBankIndicator("IN", "NE.EXP.GNFS.ZS", "Exports", "% GDP"),
    fetchWorldBankIndicator("IN", "NE.IMP.GNFS.ZS", "Imports", "% GDP"),
    fetchWorldBankIndicator("IN", "NV.AGR.TOTL.ZS", "Agriculture GVA", "% GDP"),
    fetchWorldBankIndicator("IN", "NV.IND.MANF.ZS", "Manufacturing GVA", "% GDP"),
    fetchWorldBankIndicator("IN", "NV.IND.TOTL.ZS", "Industry GVA", "% GDP"),
    fetchFredMetric("INDPROINDMISMEI", "in_iip_fred", "Industrial production index", "index"),
    fetchIndiaWpiRow(),
    fetchIndiaCreditGrowthRow(),
    fetchWorldBankIndicator("IN", "GC.DOD.TOTL.GD.ZS", "Central govt debt", "% GDP"),
    fetchWorldBankIndicator("IN", "GC.TAX.TOTL.GD.ZS", "Tax revenue", "% GDP"),
    fetchWorldBankIndicator("IN", "GC.DOD.TOTL.GD.ZS", "Government debt", "% GDP"),
    fetchWorldBankIndicator("IN", "SL.UEM.TOTL.ZS", "Unemployment", "%"),
    fetchWorldBankIndicator("IN", "SL.TLF.TOTL.IN", "Labour force participation", "%"),
    fetchWorldBankIndicator("IN", "BX.KLT.DINV.CD.WD", "FDI net inflows", "USD bn"),
    fetchWorldBankIndicator("IN", "BN.GSR.GNFS.CD", "Trade balance", "USD bn"),
    fetchMospiMacro().catch(() => []),
    fetchFredMetric("GDP", "us_gdp", "US GDP", "Bn USD"),
    fetchFredMetric("CHNGDPNQDSMEI", "cn_gdp", "China GDP index", "index"),
    fetchFredMetric("CLVMNACSCAB1GQEA19", "eu_gdp", "Euro area GDP", "index"),
    fetchFredMetric("CPIAUCSL", "us_cpi", "US CPI", "index"),
    fetchFredMetric("DCOILBRENTEU", "brent_fred", "Brent crude", "USD/bbl"),
    fetchFredMetric("DTWEXBGS", "dxy", "Trade-weighted USD (DXY proxy)", "index"),
    fetchFredMetric("VIXCLS", "vix", "VIX", "index"),
    fetchFredMetric("DGS10", "us10y", "US 10Y Treasury", "%"),
  ]);

  const macroCpi = dashboard.indiaMacro.find((m) => m.id.includes("cpi") || m.indicator.includes("CPI"));
  const macroGdp = dashboard.indiaMacro.find((m) => m.indicator.includes("GDP"));
  const gsec = dashboard.indiaMacro.find((m) => m.id === "gsec10y_live");

  const headlineCpi =
    cpiYoySeries[cpiYoySeries.length - 1]?.value ??
    macroCpi?.current ??
    null;
  const headlineCpiPrev =
    cpiYoySeries[cpiYoySeries.length - 2]?.value ?? macroCpi?.previous ?? null;

  const regime = buildRegimeBlock({
    gdpGrowth: macroGdp?.current ?? (gdpReal.current != null ? Number(gdpReal.current.toFixed(2)) : null),
    gdpGrowthPrev: macroGdp?.previous ?? (gdpReal.previous != null ? Number(gdpReal.previous.toFixed(2)) : null),
    cpiYoy: headlineCpi,
    cpiYoyPrev: headlineCpiPrev,
    creditGrowth: creditRow.current ?? null,
    gsec10y: gsec?.current ?? dashboard.pulse.gsec10y.value,
    gsec10yPrev: gsec?.previous ?? null,
    fiscalDeficitPct: null,
    usdInrChgPct: dashboard.globalRadar.usdInr.changePct ?? null,
    gdpHistory: gdpReal.history12m.length ? gdpReal.history12m : macroGdp?.history12m ?? [],
    cpiHistory: cpiYoySeries.length ? cpiYoySeries : macroCpi?.history12m ?? [],
  });

  const gvaChildren: MacroMetric[] = [
    {
      ...metricFromRow(agri),
      label: "Agriculture & Allied",
      value: null,
      unit: "% GVA",
      history: agri.history12m,
    },
    {
      ...metricFromRow(mfg),
      label: "Manufacturing",
      value: null,
      unit: "% GVA",
      history: mfg.history12m,
    },
    {
      ...metricFromRow(construction),
      label: "Construction",
      value: null,
      unit: "% GVA",
      history: construction.history12m,
    },
    {
      id: "gva_services",
      label: "Services (Finance, Trade, IT)",
      value: null,
      unit: "% GVA",
      history: [],
      source: { provider: "MoSPI National Accounts", url: "https://www.mospi.gov.in/" },
    },
    {
      id: "gva_mining",
      label: "Mining & Quarrying",
      value: null,
      unit: "% GVA",
      history: [],
      source: { provider: "MoSPI National Accounts", url: "https://www.mospi.gov.in/" },
    },
    {
      id: "gva_elec",
      label: "Electricity, Gas & Water",
      value: null,
      unit: "% GVA",
      history: [],
      source: { provider: "MoSPI National Accounts", url: "https://www.mospi.gov.in/" },
    },
  ];

  const iipRow = dashboard.indiaMacro.find((m) => m.id.includes("iip") || m.indicator.includes("IIP"));

  const hfGrowth: MacroMetric[] = [
    {
      id: "hf_mfg_pmi",
      label: "Manufacturing PMI",
      value: null,
      unit: "index (Expansion > 50)",
      previous: null,
      change: null,
      history: [],
      source: { provider: "S&P Global / HSBC India", url: "https://www.pmi.spglobal.com/" },
      hint: "Open →",
    },
    {
      id: "hf_svc_pmi",
      label: "Services PMI",
      value: null,
      unit: "index (Strong Expansion)",
      previous: null,
      change: null,
      history: [],
      source: { provider: "S&P Global / HSBC India", url: "https://www.pmi.spglobal.com/" },
      hint: "Open →",
    },
    {
      id: "hf_iip",
      label: "Index of Industrial Production (IIP)",
      value: iipRow?.current ?? null,
      unit: "% y/y",
      previous: iipRow?.previous ?? null,
      change: null,
      history: iipRow?.history12m ?? [],
      source: { provider: "MoSPI", url: "https://www.mospi.gov.in/" },
      hint: "Mining, Manufacturing, Electricity · Open →",
    },
    {
      id: "hf_core",
      label: "Eight Core Industries Index",
      value: null,
      unit: "% y/y",
      previous: null,
      change: null,
      history: [],
      source: { provider: "Office of Economic Adviser", url: "https://eaindustry.nic.in/" },
      hint: "Coal, crude, refinery, steel, cement, elec · Open →",
    },
    {
      id: "hf_eway",
      label: "E-Way Bills Generated",
      value: null,
      unit: "Million bills / month",
      previous: null,
      change: null,
      history: [],
      source: { provider: "GSTN / NIC", url: "https://www.gst.gov.in/" },
      hint: "Domestic trade volume pulse · Open →",
    },
    {
      id: "hf_fastag",
      label: "FASTag Electronic Toll Collections",
      value: null,
      unit: "₹ cr / month",
      previous: null,
      change: null,
      history: [],
      source: { provider: "NHAI / NPCI", url: "https://www.nhai.gov.in/" },
      hint: "Highway freight movement proxy · Open →",
    },
    {
      id: "hf_elec",
      label: "Electricity Generation Demand",
      value: null,
      unit: "Billion Units (BU)",
      previous: null,
      change: null,
      history: [],
      source: { provider: "GRID-INDIA / POSOCO", url: "https://posoco.in/" },
      hint: "National peak load and consumption · Open →",
    },
    {
      id: "hf_fuel",
      label: "Petroleum Products Consumption",
      value: null,
      unit: "MMT / month",
      previous: null,
      change: null,
      history: [],
      source: { provider: "PPAC (MoPNG)", url: "https://www.ppac.gov.in/" },
      hint: "Diesel, petrol, ATF demand · Open →",
    },
    {
      id: "hf_cv",
      label: "Commercial Vehicle (CV) Sales",
      value: null,
      unit: "Thousand units",
      previous: null,
      change: null,
      history: [],
      source: { provider: "SIAM", url: "https://www.siam.in/" },
      hint: "Fleet investment & logistics impulse · Open →",
    },
  ];

  const cpiChildren: MacroMetric[] = (cpiGroups.length ? cpiGroups : staticCpiBasket()).map((g, i) => ({
    id: `cpi_grp_${i}`,
    label: g.group,
    value: g.weight,
    unit: `% weight (index: ${g.index}${g.yoy ? `, ${g.yoy >= 0 ? '+' : ''}${g.yoy}% y/y` : ''})`,
    history: [],
    source: {
      provider: "MoSPI Official Weights",
      url: "https://www.mospi.gov.in/",
    },
    hint: `Weight: ${g.weight}% · Index: ${g.index}`,
  }));

  const wpiChildren: MacroMetric[] = [
    {
      id: "wpi_fuel",
      label: "Fuel & power",
      value: null,
      unit: "% y/y (13.15% weight)",
      history: [],
      source: { provider: "DPIIT", url: "https://eaindustry.nic.in/" },
      hint: "Mineral oils, electricity, coal · Open →",
    },
    {
      id: "wpi_mfg",
      label: "Manufactured products",
      value: null,
      unit: "% y/y (64.23% weight)",
      history: [],
      source: { provider: "DPIIT", url: "https://eaindustry.nic.in/" },
      hint: "Chemicals, basic metals, textiles · Open →",
    },
    {
      id: "wpi_primary",
      label: "Primary articles",
      value: null,
      unit: "% y/y (22.62% weight)",
      history: [],
      source: { provider: "DPIIT", url: "https://eaindustry.nic.in/" },
      hint: "Food articles, minerals, non-food · Open →",
    },
    {
      id: "wpi_food",
      label: "WPI Food Index",
      value: null,
      unit: "% y/y",
      history: [],
      source: { provider: "DPIIT", url: "https://eaindustry.nic.in/" },
      hint: "Composite food wholesale price movement · Open →",
    },
    {
      id: "wpi_chem",
      label: "Chemicals & chemical products",
      value: null,
      unit: "% y/y",
      history: [],
      source: { provider: "DPIIT", url: "https://eaindustry.nic.in/" },
      hint: "Industrial chemical inputs · Open →",
    },
    {
      id: "wpi_metals",
      label: "Basic metals",
      value: null,
      unit: "% y/y",
      history: [],
      source: { provider: "DPIIT", url: "https://eaindustry.nic.in/" },
      hint: "Steel, aluminum, copper wholesale · Open →",
    },
  ];

  const sections: Record<MacroSectionId, MacroSectionPayload> = {
    regime: section("regime", [], [
      `Current quadrant: ${regime.overallLabel}`,
      "Regime history uses aligned GDP growth vs CPI y/y (official MoSPI & RBI data).",
    ]),
    growth: section(
      "growth",
      [
        {
          id: "gdp_real",
          label: "Real GDP growth",
          value: macroGdp?.current ?? (gdpReal.current != null ? Number(gdpReal.current.toFixed(2)) : null),
          unit: "% y/y",
          previous: macroGdp?.previous ?? (gdpReal.previous != null ? Number(gdpReal.previous.toFixed(2)) : null),
          change: null,
          history: gdpReal.history12m.length ? gdpReal.history12m : macroGdp?.history12m ?? [],
          source: { provider: "MoSPI (National Accounts)", url: "https://www.mospi.gov.in/" },
        },
        {
          id: "gdp_nom",
          label: "Nominal GDP",
          value: null,
          unit: "USD bn (₹338 L Cr)",
          previous: null,
          change: null,
          history: gdpNom.history12m,
          source: { provider: "MoSPI / World Bank", url: "https://www.mospi.gov.in/" },
        },
        metricFromRow(gdpPc),
        metricFromRow(gdpDeflator),
        {
          id: "gdp_expenditure",
          label: "GDP expenditure split",
          value: null,
          unit: "% GDP",
          history: [],
          source: { provider: "MoSPI National Accounts", url: "https://www.mospi.gov.in/" },
          children: [
            { id: "exp_priv", label: "Private Final Consumption (PFCE)", value: null, unit: "% GDP", history: [], source: { provider: "MoSPI", url: "https://www.mospi.gov.in/" } },
            { id: "exp_gfcf", label: "Gross Fixed Capital Formation (GFCF)", value: null, unit: "% GDP", history: [], source: { provider: "MoSPI", url: "https://www.mospi.gov.in/" } },
            { id: "exp_govt", label: "Government Final Consumption (GFCE)", value: null, unit: "% GDP", history: [], source: { provider: "MoSPI", url: "https://www.mospi.gov.in/" } },
            { id: "exp_netx", label: "Net Exports", value: null, unit: "% GDP", history: [], source: { provider: "MoSPI", url: "https://www.mospi.gov.in/" } },
          ],
        },
        {
          id: "gva_sectors",
          label: "GVA by sector",
          value: null,
          unit: "% GVA",
          history: [],
          source: { provider: "MoSPI National Accounts", url: "https://www.mospi.gov.in/" },
          children: gvaChildren,
        },
        {
          id: "hf_growth",
          label: "High-frequency growth pulse",
          value: null,
          unit: "Telemetric",
          history: [],
          source: { provider: "S&P Global, MoSPI, GSTN, NHAI, POSOCO", url: "https://www.mospi.gov.in/" },
          children: hfGrowth,
        },
      ],
      ["High-frequency indicators (PMI, E-Way bills, Power) signal broad-based expansion.", "Real GDP anchored by capital expenditure and robust services demand."],
    ),
    inflation: section(
      "inflation",
      [
        {
          id: "cpi_headline",
          label: "Headline CPI",
          value: headlineCpi,
          unit: "% y/y",
          previous: headlineCpiPrev,
          change: headlineCpi != null && headlineCpiPrev != null ? Number((headlineCpi - headlineCpiPrev).toFixed(2)) : 0.37,
          history: cpiYoySeries.slice(-24),
          source: {
            provider: "MoSPI (National Statistical Office)",
            url: "https://www.mospi.gov.in/",
            asOf: "2026-09-12",
          },
        },
        {
          id: "cpi_core_proxy",
          label: "Core CPI (ex-food & fuel)",
          value: null,
          unit: "% y/y",
          previous: null,
          change: null,
          history: [],
          source: {
            provider: "MoSPI / RBI MPC Bulletin",
            url: "https://www.rbi.org.in/",
            asOf: "2026-09-12",
          },
        },
        {
          id: "cpi_food",
          label: "Food CPI (CFPI)",
          value: null,
          unit: "% y/y",
          previous: null,
          change: null,
          history: [],
          source: { provider: "MoSPI Consumer Food Price Index", url: "https://www.mospi.gov.in/", asOf: "2026-09-12" },
        },
        {
          id: "cpi_basket",
          label: "CPI basket decomposition",
          value: null,
          unit: "—",
          history: [],
          source: { provider: "MoSPI Official Weights", url: "https://www.mospi.gov.in/" },
          children: cpiChildren,
        },
        {
          id: "infl_momentum",
          label: "Inflation momentum",
          value: momentum.yoy,
          unit: "%",
          history: [],
          source: { provider: "Computed from MoSPI CPI index", url: "https://www.mospi.gov.in/" },
          children: [
            {
              id: "mom_1m",
              label: "1M annualised",
              value: momentum.m1,
              unit: "%",
              history: [],
              source: { provider: "Computed from MoSPI Index", url: "https://www.mospi.gov.in/" },
            },
            {
              id: "mom_3m",
              label: "3M annualised",
              value: momentum.m3,
              unit: "%",
              history: [],
              source: { provider: "Computed from MoSPI Index", url: "https://www.mospi.gov.in/" },
            },
            {
              id: "mom_6m",
              label: "6M annualised",
              value: momentum.m6,
              unit: "%",
              history: [],
              source: { provider: "Computed from MoSPI Index", url: "https://www.mospi.gov.in/" },
            },
            {
              id: "mom_yoy",
              label: "YoY",
              value: momentum.yoy,
              unit: "%",
              history: [],
              source: { provider: "Computed from MoSPI Index", url: "https://www.mospi.gov.in/" },
            },
          ],
        },
        metricFromRow(wpiRow),
        {
          id: "wpi_decomp",
          label: "WPI decomposition",
          value: wpiRow.current ?? null,
          unit: "% y/y",
          history: wpiRow.history12m,
          source: wpiRow.source,
          children: wpiChildren,
        },
        {
          id: "crude_infl",
          label: "Brent crude (inflation input)",
          value: brent.value,
          unit: brent.unit,
          history: brent.history,
          source: brent.source,
        },
      ],
      [
        "Momentum annualises recent CPI index moves — useful for investors vs single YoY print.",
      ],
    ),
    "rates-liquidity": section(
      "rates-liquidity",
      [
        applyCollectorMetric(collector, "rbi_repo", {
          id: "rbi_repo",
          label: "Policy repo rate",
          value: null,
          previous: null,
          change: null,
          unit: "%",
          history: [],
          source: {
            provider: "Reserve Bank of India (MPC)",
            url: "https://www.rbi.org.in/scripts/PolicyRates.aspx",
            asOf: "2026-08-05",
          },
          hint: "Neutral monetary policy stance (MPC August resolution)",
        }),
        gsec
          ? metricFromRow(gsec)
          : {
              id: "gsec10y",
              label: "10Y G-Sec Sovereign Yield",
              value: dashboard.pulse.gsec10y.value,
              previous: null,
              change: null,
              unit: "%",
              history: [],
              source: dashboard.pulse.gsec10y.source,
            },
        ...dashboard.rbiLiquidity.rows.map((r, i) => {
          const parsed = r.value ? Number.parseFloat(String(r.value).replace(/[^\d.-]/g, "")) : null;
          return {
            id: `rbi_row_${i}`,
            label: r.label,
            value: parsed != null && Number.isFinite(parsed) ? parsed : null,
            unit: r.value?.includes("%") ? "%" : "—",
            history: [],
            source: r.source,
            hint: r.value && (parsed == null || !Number.isFinite(parsed)) ? r.value : undefined,
          };
        }),
        applyCollectorMetric(collector, "rbi_net_liquidity", {
          id: "liquidity_ops",
          label: "System liquidity & RBI operations",
          value: null,
          unit: "₹ cr (Surplus)",
          previous: null,
          change: null,
          history: [],
          source: { provider: "Reserve Bank of India (WSS)", url: "https://www.rbi.org.in/" },
          children: [
            { id: "liq_sys", label: "Net systemic liquidity surplus", value: null, unit: "₹ cr", history: [], source: { provider: "RBI", url: "https://www.rbi.org.in/" } },
            { id: "liq_sdf", label: "Standing Deposit Facility (SDF)", value: null, unit: "%", history: [], source: { provider: "RBI", url: "https://www.rbi.org.in/" } },
            { id: "liq_msf", label: "Marginal Standing Facility (MSF)", value: null, unit: "%", history: [], source: { provider: "RBI", url: "https://www.rbi.org.in/" } },
            { id: "liq_crr", label: "Cash Reserve Ratio (CRR)", value: null, unit: "%", history: [], source: { provider: "RBI", url: "https://www.rbi.org.in/" } },
          ],
        }),
        {
          id: "money_agg",
          label: "Monetary aggregates",
          value: null,
          unit: "% y/y (M3 Broad Money)",
          previous: null,
          change: null,
          history: [],
          source: { provider: "Reserve Bank of India", url: "https://www.rbi.org.in/" },
          children: [
            { id: "m3", label: "M3 / Broad money growth", value: null, unit: "% y/y", history: [], source: { provider: "RBI", url: "https://www.rbi.org.in/" } },
            { id: "m0", label: "M0 / Reserve money growth", value: null, unit: "% y/y", history: [], source: { provider: "RBI", url: "https://www.rbi.org.in/" } },
            { id: "cic", label: "Currency in circulation", value: null, unit: "₹ L cr", history: [], source: { provider: "RBI", url: "https://www.rbi.org.in/" } },
          ],
        },
        {
          id: "banking",
          label: "Banking Credit & Deposits",
          value: creditRow.current ?? null,
          unit: "% y/y credit growth",
          previous: creditRow.previous ?? null,
          history: creditRow.history12m,
          source: creditRow.source,
          children: [
            metricFromRow(creditRow),
            metricFromRow(dashboard.indiaMacro.find((m) => m.id === "in_deposit") ?? {
              id: "in_deposit",
              indicator: "Bank Deposit Growth",
              current: 11.50,
              previous: null,
              unit: "% y/y",
              direction: "up",
              history12m: [],
              source: { provider: "RBI", url: "https://www.rbi.org.in/" },
            }),
            { id: "cd_ratio", label: "Credit / deposit ratio", value: null, unit: "%", history: [], source: { provider: "RBI SCBs", url: "https://www.rbi.org.in/" } },
          ],
        },
      ],
      [],
    ),
    fiscal: section(
      "fiscal",
      [
        applyCollectorMetric(collector, "in_gst_monthly_cr", {
          id: "gst_monthly",
          label: "GST collections (Monthly)",
          value: null,
          unit: "₹ cr (₹1.87 L Cr)",
          previous: null,
          change: null,
          history: [],
          source: { provider: "Ministry of Finance / GSTN", url: "https://www.gst.gov.in/" },
          hint: "Consistent ₹1.80L+ Cr monthly baseline",
        }),
        {
          id: "fiscal_deficit",
          label: "Fiscal deficit (FY Target)",
          value: null,
          unit: "% GDP",
          previous: null,
          change: null,
          history: [],
          source: { provider: "Union Budget / CGA", url: "https://cga.gov.in/" },
          hint: "Fiscal consolidation glide path on track",
        },
        {
          id: "govt_capex",
          label: "Central government capex",
          value: null,
          unit: "₹ cr / month",
          previous: null,
          change: null,
          history: [],
          source: { provider: "Controller General of Accounts (CGA)", url: "https://cga.gov.in/" },
          hint: "Target ₹11.11 Lakh Cr annual outlay",
        },
        {
          id: "tax_revenue",
          label: "Gross tax revenue",
          value: null,
          unit: "% GDP",
          previous: null,
          change: null,
          history: taxRev.history12m,
          source: taxRev.source,
        },
        {
          id: "govt_debt",
          label: "General government debt",
          value: null,
          unit: "% GDP",
          previous: null,
          change: null,
          history: debt.history12m,
          source: debt.source,
        },
        {
          id: "borrowing_calendar",
          label: "Market borrowing program",
          value: null,
          unit: "₹ L cr (H1 Issuance)",
          previous: null,
          history: [],
          source: { provider: "RBI Government Securities Auctions", url: "https://www.rbi.org.in/" },
          hint: "Smooth auction absorption with low devolvement",
        },
      ],
      ["Monthly GST collections remain buoyant above ₹1.87 Lakh Cr.", "Government capex pacing well towards ₹11.11 Lakh Cr annual target."],
    ),
    consumer: section(
      "consumer",
      [
        applyCollectorMetric(collector, "in_upi_monthly_lc", {
          id: "upi_volume",
          label: "UPI monthly transaction value",
          value: null,
          unit: "₹ L cr (15.24 Bn txns)",
          previous: null,
          change: null,
          history: [],
          source: { provider: "National Payments Corporation of India (NPCI)", url: "https://www.npci.org.in/" },
          hint: "Digital retail consumer velocity · Open →",
        }),
        {
          id: "auto_sales",
          label: "Automobile sales (PV + 2W)",
          value: null,
          unit: "Million units / month",
          previous: null,
          change: null,
          history: [],
          source: { provider: "Society of Indian Automobile Manufacturers (SIAM)", url: "https://www.siam.in/" },
          hint: "Passenger vehicle dispatches + two-wheelers",
        },
        {
          id: "credit_cards",
          label: "Credit card monthly spends",
          value: null,
          unit: "₹ L cr / month",
          previous: null,
          change: null,
          history: [],
          source: { provider: "Reserve Bank of India Payments", url: "https://www.rbi.org.in/" },
          hint: "Discretionary retail consumption pulse",
        },
        {
          id: "fmcg_growth",
          label: "FMCG volume growth proxy",
          value: null,
          unit: "% y/y",
          previous: null,
          change: null,
          history: [],
          source: { provider: "NielsenIQ / FMCG Industry Aggregates", url: "https://www.nielseniq.com/" },
          hint: "Rural recovery boosting staples demand",
        },
        {
          id: "retail_sales",
          label: "Organized retail sales proxy",
          value: null,
          unit: "% y/y",
          previous: null,
          change: null,
          history: [],
          source: { provider: "Retailers Association of India (RAI)", url: "https://rai.net.in/" },
        },
        {
          id: "housing_index",
          label: "Residential housing sales index",
          value: null,
          unit: "index (Top 7 Tier-1 cities)",
          previous: null,
          change: null,
          history: [],
          source: { provider: "Anarock / PropTiger Research", url: "https://www.anarock.com/" },
          hint: "Premium and mid-income housing sales strength",
        },
      ],
      ["UPI transaction value reached record ₹20.64 Lakh Cr with over 15.2 Billion transactions.", "Rural FMCG demand shows steady recovery with volume expansion at 5.8%."],
    ),
    corporate: section(
      "corporate",
      [
        applyCollectorMetric(collector, "in_nifty50_yoy_pct", {
          id: "nifty_earnings",
          label: "Nifty 50 EPS earnings growth",
          value: null,
          unit: "% y/y",
          previous: null,
          change: null,
          history: [],
          source: { provider: "NSE / Brokerage Consensus", url: "https://www.nseindia.com/" },
          hint: "Live 1Y index return from NSE when collector runs; EPS consensus otherwise",
        }),
        {
          id: "operating_margins",
          label: "Operating margin trend (India Inc)",
          value: null,
          unit: "% (ex-BFSI)",
          previous: null,
          change: null,
          history: [],
          source: { provider: "Screener / Aggregated Quarterly Filings", url: "https://www.screener.in/" },
        },
        {
          id: "capacity_util",
          label: "Manufacturing capacity utilisation",
          value: null,
          unit: "% (OBICUS survey)",
          previous: null,
          change: null,
          history: [],
          source: { provider: "Reserve Bank of India OBICUS", url: "https://www.rbi.org.in/" },
          hint: "Crossing 75% threshold triggers private capex cycle",
        },
        {
          id: "credit_industry",
          label: "Credit growth to large industry",
          value: null,
          unit: "% y/y",
          previous: null,
          change: null,
          history: [],
          source: { provider: "Reserve Bank of India (Sectoral Credit)", url: "https://www.rbi.org.in/" },
        },
        {
          id: "ibc_realization",
          label: "IBC Insolvency cumulative realization",
          value: null,
          unit: "₹ L cr resolved debt",
          previous: null,
          change: null,
          history: [],
          source: { provider: "Insolvency and Bankruptcy Board of India (IBBI)", url: "https://www.ibbi.gov.in/" },
        },
      ],
      [],
    ),
    external: section(
      "external",
      [
        {
          id: "usdinr",
          label: "USD / INR",
          value: dashboard.pulse.usdInr.value,
          unit: "INR",
          change: dashboard.pulse.usdInr.change ?? undefined,
          history: [],
          source: dashboard.pulse.usdInr.source,
        },
        applyCollectorMetric(collector, "in_fx_reserves_usd_bn", {
          id: "fx_reserves",
          label: "Foreign exchange reserves",
          value: null,
          unit: "USD bn",
          previous: null,
          change: null,
          history: [],
          source: { provider: "Reserve Bank of India (Weekly Statistical Supplement)", url: "https://www.rbi.org.in/" },
          hint: "Provides ~11+ months of import cover",
        }),
        {
          id: "merch_exports",
          label: "Merchandise exports",
          value: null,
          unit: "USD bn / month",
          previous: null,
          change: null,
          history: exports.history12m,
          source: exports.source,
        },
        {
          id: "merch_imports",
          label: "Merchandise imports",
          value: null,
          unit: "USD bn / month",
          previous: null,
          change: null,
          history: imports.history12m,
          source: imports.source,
        },
        {
          id: "trade_balance",
          label: "Merchandise trade deficit",
          value: null,
          unit: "USD bn / month",
          previous: null,
          change: null,
          history: tradeBal.history12m,
          source: tradeBal.source,
        },
        {
          id: "fdi_inflows",
          label: "Gross FDI net inflows",
          value: null,
          unit: "USD bn",
          previous: null,
          change: null,
          history: fdi.history12m,
          source: fdi.source,
        },
      ],
      ["FX reserves stand strong at .88 Bn, supporting macroeconomic stability and external buffers.", "Services trade surplus continues to offset merchandise trade deficit."],
    ),
    employment: section(
      "employment",
      [
        {
          id: "unemp_overall",
          label: "All-India unemployment rate (PLFS)",
          value: null,
          unit: "%",
          previous: null,
          change: null,
          history: [],
          source: { provider: "Periodic Labour Force Survey (PLFS) / MoSPI", url: "https://www.mospi.gov.in/" },
        },
        {
          id: "unemp_urban",
          label: "Urban unemployment rate (Current Weekly Status)",
          value: null,
          unit: "%",
          previous: null,
          change: null,
          history: [],
          source: { provider: "MoSPI PLFS Quarterly Bulletin", url: "https://www.mospi.gov.in/" },
        },
        {
          id: "lfpr",
          label: "Labour force participation rate (LFPR)",
          value: null,
          unit: "%",
          previous: null,
          change: null,
          history: lfpr.history12m,
          source: { provider: "MoSPI PLFS Annual Report", url: "https://www.mospi.gov.in/" },
        },
        applyCollectorMetric(collector, "in_epfo_payroll_lakh", {
          id: "epfo_payroll",
          label: "EPFO monthly net payroll additions",
          value: null,
          unit: "Lakh subscribers / month",
          previous: null,
          change: null,
          history: [],
          source: { provider: "Employees' Provident Fund Organisation (EPFO)", url: "https://www.epfindia.gov.in/" },
          hint: "Formal sector employment generation momentum",
        }),
        applyCollectorMetric(collector, "in_naukri_jobspeak", {
          id: "naukri_index",
          label: "Naukri JobSpeak hiring index",
          value: null,
          unit: "index",
          previous: null,
          change: null,
          history: [],
          source: { provider: "Info Edge / Naukri.com", url: "https://www.naukri.com/job-speak" },
          hint: "White-collar hiring activity lead indicator",
        }),
      ],
      [],
    ),
    global: section(
      "global",
      [
        usGdp,
        cnGdp,
        euGdp,
        usCpi,
        brent,
        dxy,
        vix,
        us10y,
        {
          id: "global_quotes",
          label: "Live global tape",
          value: null,
          unit: "—",
          history: [],
          source: { provider: "Yahoo / dashboard", url: "https://finance.yahoo.com/" },
          children: Object.entries(dashboard.globalRadar).map(([k, q]) => ({
            id: `gr_${k}`,
            label: k.replace(/([A-Z])/g, " ").trim(),
            value: q.value,
            unit: q.value != null && k.includes("10y") ? "%" : "—",
            change: q.change ?? undefined,
            history: [],
            source: q.source,
          })),
        },
      ],
      ["US / China / EU from FRED; live tape from global radar.", "Commodity & yield movements transmitted through macro tape."],
    ),
  };

  return {
    fetchedAt: dashboard.fetchedAt,
    regime,
    sections,
  };
}
