import type { DisclosureRow } from "./store";

export const SEED_DISCLOSURES: DisclosureRow[] = [
  {
    seqId: "106804476",
    symbol: "HDFCAMC",
    companyName: "HDFC Asset Management Company Limited",
    isin: "INE127D01025",
    headline: "HDFC Asset Management Company Limited has informed the Exchange about Intimation of conference call on financial results for the quarter and half year ended September 30, 2026",
    category: "Analysts/Institutional Investor Meet/Con. Call Updates",
    announcedAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    pdfUrl: "https://nsearchives.nseindia.com/corporate/DEEPTI_01102026114650_NSEBSE_45.pdf",
    aiSentiment: "positive",
    aiScore: 0.92,
    aiSummary: "Earnings Concall Schedule: Conference call scheduled for Q2 & H1 FY27 financial results review.",
  },
  {
    seqId: "106804491",
    symbol: "GPTINFRA",
    companyName: "GPT Infraprojects Limited",
    isin: "INE390G01014",
    headline: "GPT Infraprojects Limited has informed the Exchange about contract win of Rs. 385 Crore by its Subsidiary Company, GPT Concrete Products South Africa (Pty) Limited",
    category: "General Updates",
    announcedAt: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
    pdfUrl: "https://nsearchives.nseindia.com/corporate/GPTINFRA_01102026115630_Press_Release_intimation_Contract_win_385_Cr_011026_Sgd.pdf",
    aiSentiment: "positive",
    aiScore: 0.96,
    aiSummary: "Substantial Order Win: Rs 385 Crore infrastructure contract secured by South African subsidiary.",
  },
  {
    seqId: "106804492",
    symbol: "PAISALO",
    companyName: "Paisalo Digital Limited",
    isin: "INE420C01042",
    headline: "Paisalo Digital Limited has informed the Exchange regarding a press release dated October 01, 2026, titled Paisalo Digital concludes H1 FY27 with enhanced capital strength and funding flexibility.",
    category: "Press Release",
    announcedAt: new Date(Date.now() - 75 * 60 * 1000).toISOString(),
    pdfUrl: "https://nsearchives.nseindia.com/corporate/PAISALO_01102026115750_BSE_NSE_Press_Release.pdf",
    aiSentiment: "positive",
    aiScore: 0.89,
    aiSummary: "Capital Adequacy & Liquidity: Concluded H1 with enhanced balance sheet capital and diversified funding lines.",
  },
  {
    seqId: "106804473",
    symbol: "NBCC",
    companyName: "NBCC (India) Limited",
    isin: "INE095N01015",
    headline: "NBCC (India) Limited has informed the Exchange regarding Intimation of Work Orders received by NBCC (India) Limited in the ordinary course of business amounting to Rs. 28.78 Cr. approx.",
    category: "Updates",
    announcedAt: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
    pdfUrl: "https://nsearchives.nseindia.com/corporate/NBCC_01102026114633_STX_Work_order.pdf",
    aiSentiment: "positive",
    aiScore: 0.88,
    aiSummary: "New Order Inflow: Fresh civil construction work orders valued at approx Rs 28.78 Crore.",
  },
  {
    seqId: "106804480",
    symbol: "DODLA",
    companyName: "Dodla Dairy Limited",
    isin: "INE021O01019",
    headline: "Dodla Dairy Limited has informed the Exchange regarding Completion of Acquisition of 2% Equity Share Capital of M/s. Sids Farm Private Limited",
    category: "General Updates",
    announcedAt: new Date(Date.now() - 140 * 60 * 1000).toISOString(),
    pdfUrl: "https://nsearchives.nseindia.com/corporate/DODLA_01102026115137_Acquistion.pdf",
    aiSentiment: "positive",
    aiScore: 0.86,
    aiSummary: "Strategic Equity Acquisition: Completed purchase of 2% stake in premium dairy player Sids Farm.",
  },
  {
    seqId: "106804497",
    symbol: "NECCLTD",
    companyName: "North Eastern Carrying Corporation Limited",
    isin: "INE553C01016",
    headline: "North Eastern Carrying Corporation Limited has informed the Exchange about General Updates - Allotment of one Crores Convertible Warrants to Mr. Sunil Kumar Jain, Promoter of the Company",
    category: "General Updates",
    announcedAt: new Date(Date.now() - 160 * 60 * 1000).toISOString(),
    pdfUrl: "https://nsearchives.nseindia.com/corporate/NECCLTD_01102026120204_Disclosure_Reg30_AllotmentofConvertiableWarratns.pdf",
    aiSentiment: "positive",
    aiScore: 0.84,
    aiSummary: "Promoter Capital Infusion: Allotment of 1 Crore convertible warrants demonstrating promoter confidence.",
  },
  {
    seqId: "106804475",
    symbol: "NECCLTD",
    companyName: "North Eastern Carrying Corporation Limited",
    isin: "INE553C01016",
    headline: "North Eastern Carrying Corporation Limited has informed the Exchange regarding Outcome of Board Meeting held on October 01, 2026.",
    category: "Outcome of Board Meeting",
    announcedAt: new Date(Date.now() - 180 * 60 * 1000).toISOString(),
    pdfUrl: "https://nsearchives.nseindia.com/corporate/NECCLTD_01102026114827_OutcomeofBoardMeeting_01102026.pdf",
    aiSentiment: "neutral",
    aiScore: 0.81,
    aiSummary: "Board Meeting Outcome: Board approved strategic warrant issuance and capital allocation.",
  },
  {
    seqId: "106804493",
    symbol: "ATULAUTO",
    companyName: "Atul Auto Limited",
    isin: "INE951D01010",
    headline: "Atul Auto Limited has informed the Exchange regarding Monthly Business Updates for the month of September 2026",
    category: "Monthly Business Updates",
    announcedAt: new Date(Date.now() - 200 * 60 * 1000).toISOString(),
    pdfUrl: "https://nsearchives.nseindia.com/corporate/ATULAUTO_01102026115952_Letter_SalesPerformance_BSE_NSE_September2026_Signed.pdf",
    aiSentiment: "neutral",
    aiScore: 0.85,
    aiSummary: "Monthly Operational Data: Released September 2026 three-wheeler production and volume dispatch figures.",
  },
  {
    seqId: "106804489",
    symbol: "GCSL",
    companyName: "Gretex Corporate Services Limited",
    isin: "INE199P01028",
    headline: "Gretex Corporate Services Limited has informed the Exchange regarding The Company has filed a Draft Red Herring Prospectus (DRHP) for Abacus Lifestyle Brands Limited & Oremet Alloys And Castings Limited on the Emerge Platform of the National Stock Exchange of India Limited.",
    category: "Updates",
    announcedAt: new Date(Date.now() - 230 * 60 * 1000).toISOString(),
    pdfUrl: "https://nsearchives.nseindia.com/corporate/bdesai_01102026115323_Intimation_for_Filing_of_DRHP_Abacus_and_Oremet.pdf",
    aiSentiment: "positive",
    aiScore: 0.87,
    aiSummary: "Primary Market Mandate: Lead merchant banker filed DRHP for two emerging SME IPO candidates.",
  },
  {
    seqId: "106804485",
    symbol: "FSL",
    companyName: "Firstsource Solutions Limited",
    isin: "INE684F01012",
    headline: "Significant increase in volume has been observed in Firstsource Solutions Limited. The Exchange had written to the company. Firstsource Solutions Limited has submitted their response.",
    category: "Spurt in Volume",
    announcedAt: new Date(Date.now() - 260 * 60 * 1000).toISOString(),
    pdfUrl: "https://nsearchives.nseindia.com/corporate/FSL_01102026115206_Clarification_Movement_in_Volumnsigned.pdf",
    aiSentiment: "neutral",
    aiScore: 0.88,
    aiSummary: "Exchange Surveillance Clarification: Confirmed no undisclosed price-sensitive information behind recent volume spike.",
  },
  {
    seqId: "106804496",
    symbol: "RADAAN",
    companyName: "Radaan Mediaworks India Limited",
    isin: "INE874F01027",
    headline: "Radaan Mediaworks India Limited has submitted the Exchange a copy Scrutinizers report of Annual General Meeting held on September 29, 2026. Further, the company has informed the Exchange regarding voting results.",
    category: "Shareholders meeting",
    announcedAt: new Date(Date.now() - 300 * 60 * 1000).toISOString(),
    pdfUrl: "https://nsearchives.nseindia.com/corporate/RADAAN_01102026120123_SE_intimation_on_Voting_Result_and_Scrutinser_Report.pdf",
    aiSentiment: "neutral",
    aiScore: 0.86,
    aiSummary: "AGM Proceedings: Shareholders passed all statutory resolutions with required majority vote.",
  },
  {
    seqId: "106804494",
    symbol: "EXICOM",
    companyName: "Exicom Tele-Systems Limited",
    isin: "INE777F01014",
    headline: "Exicom Tele-Systems Limited has informed the Exchange regarding Allotment of 86,811 Equity Shares under employee stock options.",
    category: "ESOP/ESOS/ESPS",
    announcedAt: new Date(Date.now() - 340 * 60 * 1000).toISOString(),
    pdfUrl: "https://nsearchives.nseindia.com/corporate/EXICOM_01102026115852_intimation-esop_allotmentsigned.pdf",
    aiSentiment: "neutral",
    aiScore: 0.84,
    aiSummary: "ESOP Share Allotment: Expanded paid-up capital following exercise of vested employee stock option grants.",
  },
  {
    seqId: "106804490",
    symbol: "VIPULLTD",
    companyName: "Vipul Limited",
    isin: "INE946H01037",
    headline: "Vipul Limited has informed the Exchange regarding Newspaper clippings for audited financial results.",
    category: "Updates",
    announcedAt: new Date(Date.now() - 380 * 60 * 1000).toISOString(),
    pdfUrl: "https://nsearchives.nseindia.com/corporate/VIPULLTD_01102026115503_vipuladvt.pdf",
    aiSentiment: "neutral",
    aiScore: 0.82,
    aiSummary: "Statutory Publication: Published audited financial figures in national English and Hindi dailies.",
  },
  {
    seqId: "106804483",
    symbol: "AMANTA",
    companyName: "Amanta Healthcare Limited",
    isin: "INE084K01015",
    headline: "Amanta Healthcare Limited has informed the Exchange regarding Submission of Disclosures under Regulation 7(2) of the SEBI (Prohibition of Insider Trading) Regulations, 2015",
    category: "Updates",
    announcedAt: new Date(Date.now() - 420 * 60 * 1000).toISOString(),
    pdfUrl: "https://nsearchives.nseindia.com/corporate/AMANTA_01102026115104_Intimation_PIT.pdf",
    aiSentiment: "neutral",
    aiScore: 0.83,
    aiSummary: "SEBI Insider Trading Filing: Routine disclosure of designated person equity transaction.",
  },
  {
    seqId: "106802824",
    symbol: "RELIANCE",
    companyName: "Reliance Industries Limited",
    isin: "INE002A01018",
    headline: "Reliance Industries Limited has informed the Exchange regarding Trading Window closure pursuant to SEBI (Prohibition of Insider Trading) Regulations, 2015",
    category: "Trading Window",
    announcedAt: "2026-09-30T11:49:17.000Z",
    pdfUrl: "https://nsearchives.nseindia.com/corporate/PVIVINMA_30092026170527_SE_TWC_300926.pdf",
    aiSentiment: "neutral",
    aiScore: 0.92,
    aiSummary: "Trading Window Closure: Formal disclosure of trading window closure for designated persons ahead of Q2 FY27 financial results.",
  },
  {
    seqId: "106802333",
    symbol: "INFY",
    companyName: "Infosys Limited",
    isin: "INE009A01021",
    headline: "Infosys and ABN Amro Extend Strategic Collaboration to Simplify IT Landscape and Accelerate AI-Driven Transformation",
    category: "Updates",
    announcedAt: "2026-09-30T09:59:57.000Z",
    pdfUrl: "https://nsearchives.nseindia.com/corporate/INFY_30092026152928_PR_30092026.pdf",
    aiSentiment: "positive",
    aiScore: 0.96,
    aiSummary: "Strategic Deal Extension: Multi-year partnership renewal with ABN AMRO driving cloud modernization and enterprise AI.",
  },
  {
    seqId: "106802331",
    symbol: "LT",
    companyName: "Larsen & Toubro Limited",
    isin: "INE018A01030",
    headline: "Larsen & Toubro Limited has informed the Exchange about General Updates regarding L&T Metro Rail (Hyderabad) Limited",
    category: "General Updates",
    announcedAt: "2026-09-30T09:59:11.000Z",
    pdfUrl: "https://nsearchives.nseindia.com/corporate/PAM_30092026152845_IntimationLTMRHL30092026.pdf",
    aiSentiment: "neutral",
    aiScore: 0.88,
    aiSummary: "Subsidiary Update: Formal disclosure regarding structural refinancing arrangements for L&T Metro Rail Hyderabad.",
  },
  {
    seqId: "106801199",
    symbol: "ICICIBANK",
    companyName: "ICICI Bank Limited",
    isin: "INE090A01013",
    headline: "ICICI Bank Limited has informed the Exchange regarding Filing of amendment to the Annual Securities Report filed with Director of Kanto Regional Finance Bureau",
    category: "Updates",
    announcedAt: "2026-09-29T14:40:05.000Z",
    pdfUrl: "https://nsearchives.nseindia.com/corporate/ICICI2022_29092026200845_NSEBSE29092026.pdf",
    aiSentiment: "neutral",
    aiScore: 0.89,
    aiSummary: "Regulatory Submission: Amendment to statutory Annual Securities Report filed with international finance bureau.",
  },
  {
    seqId: "106794266",
    symbol: "TCS",
    companyName: "Tata Consultancy Services Limited",
    isin: "INE467B01029",
    headline: "Tata Consultancy Services Limited has informed the Exchange about Copy of Newspaper Publication regarding Board Meeting",
    category: "Copy of Newspaper Publication",
    announcedAt: "2026-09-25T11:53:14.000Z",
    pdfUrl: "https://nsearchives.nseindia.com/corporate/TCS_CORPCS_25092026172243_SEInt25092026_signed.pdf",
    aiSentiment: "neutral",
    aiScore: 0.85,
    aiSummary: "Statutory Notice: Published statutory newspaper intimations concerning board meeting schedule for Q2 FY27 earnings.",
  }
];
