import type { Instrument } from "@/lib/types";

export const UNIVERSE: Instrument[] = [
  {
    symbol: "SPY",
    name: "SPDR S&P 500 ETF",
    assetClass: "Equity",
    sector: "Multi-Asset",
    region: "US",
    currency: "USD",
    description: "Broad US large-cap equity benchmark.",
  },
  {
    symbol: "QQQ",
    name: "Invesco QQQ Trust",
    assetClass: "Equity",
    sector: "Technology",
    region: "US",
    currency: "USD",
    description: "Nasdaq-100 growth complex.",
  },
  {
    symbol: "IWM",
    name: "iShares Russell 2000",
    assetClass: "Equity",
    sector: "Multi-Asset",
    region: "US",
    currency: "USD",
    description: "US small-cap beta.",
  },
  {
    symbol: "EFA",
    name: "iShares MSCI EAFE",
    assetClass: "Equity",
    sector: "Multi-Asset",
    region: "Europe",
    currency: "USD",
    description: "Developed international equities.",
  },
  {
    symbol: "EEM",
    name: "iShares MSCI Emerging Markets",
    assetClass: "Equity",
    sector: "Multi-Asset",
    region: "EM",
    currency: "USD",
    description: "Emerging-market equity beta.",
  },
  {
    symbol: "AAPL",
    name: "Apple Inc.",
    assetClass: "Equity",
    sector: "Technology",
    region: "US",
    currency: "USD",
    description: "Global consumer-tech franchise.",
  },
  {
    symbol: "MSFT",
    name: "Microsoft Corporation",
    assetClass: "Equity",
    sector: "Technology",
    region: "US",
    currency: "USD",
    description: "Enterprise software and cloud compounder.",
  },
  {
    symbol: "NVDA",
    name: "NVIDIA Corporation",
    assetClass: "Equity",
    sector: "Technology",
    region: "US",
    currency: "USD",
    description: "Accelerated computing and AI infrastructure.",
  },
  {
    symbol: "GOOGL",
    name: "Alphabet Inc.",
    assetClass: "Equity",
    sector: "Communication",
    region: "US",
    currency: "USD",
    description: "Search, YouTube, and cloud advertising platform.",
  },
  {
    symbol: "AMZN",
    name: "Amazon.com Inc.",
    assetClass: "Equity",
    sector: "Consumer",
    region: "US",
    currency: "USD",
    description: "Commerce, AWS, and advertising flywheel.",
  },
  {
    symbol: "META",
    name: "Meta Platforms Inc.",
    assetClass: "Equity",
    sector: "Communication",
    region: "US",
    currency: "USD",
    description: "Social graph and performance advertising.",
  },
  {
    symbol: "JPM",
    name: "JPMorgan Chase & Co.",
    assetClass: "Equity",
    sector: "Financials",
    region: "US",
    currency: "USD",
    description: "US money-center bank and markets franchise.",
  },
  {
    symbol: "GS",
    name: "Goldman Sachs Group",
    assetClass: "Equity",
    sector: "Financials",
    region: "US",
    currency: "USD",
    description: "Institutional markets, IBD, and asset management.",
  },
  {
    symbol: "BRK.B",
    name: "Berkshire Hathaway",
    assetClass: "Equity",
    sector: "Financials",
    region: "US",
    currency: "USD",
    description: "Insurance float and compound capital allocator.",
  },
  {
    symbol: "JNJ",
    name: "Johnson & Johnson",
    assetClass: "Equity",
    sector: "Healthcare",
    region: "US",
    currency: "USD",
    description: "Defensive healthcare conglomerate.",
  },
  {
    symbol: "UNH",
    name: "UnitedHealth Group",
    assetClass: "Equity",
    sector: "Healthcare",
    region: "US",
    currency: "USD",
    description: "Managed care and Optum services platform.",
  },
  {
    symbol: "XOM",
    name: "Exxon Mobil Corporation",
    assetClass: "Equity",
    sector: "Energy",
    region: "US",
    currency: "USD",
    description: "Integrated oil major, high commodity beta.",
  },
  {
    symbol: "CVX",
    name: "Chevron Corporation",
    assetClass: "Equity",
    sector: "Energy",
    region: "US",
    currency: "USD",
    description: "Integrated energy with disciplined capital return.",
  },
  {
    symbol: "CAT",
    name: "Caterpillar Inc.",
    assetClass: "Equity",
    sector: "Industrials",
    region: "US",
    currency: "USD",
    description: "Global machinery and infrastructure cycle.",
  },
  {
    symbol: "NEE",
    name: "NextEra Energy",
    assetClass: "Equity",
    sector: "Utilities",
    region: "US",
    currency: "USD",
    description: "Regulated utility plus renewables growth.",
  },
  {
    symbol: "PLD",
    name: "Prologis Inc.",
    assetClass: "Equity",
    sector: "Real Estate",
    region: "US",
    currency: "USD",
    description: "Global logistics REIT.",
  },
  {
    symbol: "TLT",
    name: "iShares 20+ Year Treasury",
    assetClass: "Fixed Income",
    sector: "Rates",
    region: "US",
    currency: "USD",
    description: "Long-duration US Treasury exposure.",
  },
  {
    symbol: "IEF",
    name: "iShares 7-10 Year Treasury",
    assetClass: "Fixed Income",
    sector: "Rates",
    region: "US",
    currency: "USD",
    description: "Intermediate Treasury duration.",
  },
  {
    symbol: "LQD",
    name: "iShares IG Corporate Bond",
    assetClass: "Fixed Income",
    sector: "Credit",
    region: "US",
    currency: "USD",
    description: "Investment-grade credit beta.",
  },
  {
    symbol: "HYG",
    name: "iShares High Yield Corporate",
    assetClass: "Fixed Income",
    sector: "Credit",
    region: "US",
    currency: "USD",
    description: "US high-yield credit risk premium.",
  },
  {
    symbol: "TIP",
    name: "iShares TIPS Bond",
    assetClass: "Fixed Income",
    sector: "Rates",
    region: "US",
    currency: "USD",
    description: "Inflation-linked Treasuries.",
  },
  {
    symbol: "GLD",
    name: "SPDR Gold Shares",
    assetClass: "Commodity",
    sector: "Precious Metals",
    region: "Global",
    currency: "USD",
    description: "Physical gold proxy.",
  },
  {
    symbol: "SLV",
    name: "iShares Silver Trust",
    assetClass: "Commodity",
    sector: "Precious Metals",
    region: "Global",
    currency: "USD",
    description: "Silver industrial/monetary hybrid.",
  },
  {
    symbol: "USO",
    name: "United States Oil Fund",
    assetClass: "Commodity",
    sector: "Energy Commodity",
    region: "Global",
    currency: "USD",
    description: "WTI crude oil futures overlay.",
  },
  {
    symbol: "DBC",
    name: "Invesco DB Commodity Index",
    assetClass: "Commodity",
    sector: "Energy Commodity",
    region: "Global",
    currency: "USD",
    description: "Broad commodity basket.",
  },
  {
    symbol: "UUP",
    name: "Invesco DB US Dollar Index",
    assetClass: "FX",
    sector: "Currency",
    region: "US",
    currency: "USD",
    description: "USD vs basket of G10 currencies.",
  },
  {
    symbol: "VXUS",
    name: "Vanguard Total Intl Stock",
    assetClass: "Equity",
    sector: "Multi-Asset",
    region: "Global",
    currency: "USD",
    description: "All-world ex-US equity.",
  },
  {
    symbol: "BND",
    name: "Vanguard Total Bond Market",
    assetClass: "Fixed Income",
    sector: "Rates",
    region: "US",
    currency: "USD",
    description: "US aggregate fixed income.",
  },
  {
    symbol: "VNQ",
    name: "Vanguard Real Estate ETF",
    assetClass: "Equity",
    sector: "Real Estate",
    region: "US",
    currency: "USD",
    description: "US REIT complex.",
  },
  {
    symbol: "ASML",
    name: "ASML Holding",
    assetClass: "Equity",
    sector: "Technology",
    region: "Europe",
    currency: "USD",
    description: "EUVlithography monopoly in the semiconductor stack.",
  },
  {
    symbol: "TSM",
    name: "Taiwan Semiconductor",
    assetClass: "Equity",
    sector: "Technology",
    region: "EM",
    currency: "USD",
    description: "Foundry backbone of global compute.",
  },
  {
    symbol: "LLY",
    name: "Eli Lilly and Company",
    assetClass: "Equity",
    sector: "Healthcare",
    region: "US",
    currency: "USD",
    description: "Incretin franchise and late-stage pipeline.",
  },
  {
    symbol: "AVGO",
    name: "Broadcom Inc.",
    assetClass: "Equity",
    sector: "Technology",
    region: "US",
    currency: "USD",
    description: "Custom silicon, networking, and infrastructure software.",
  },
];

import { INDIA_EQUITIES } from "@/lib/feeds/india/instruments";

const INDIA_INSTRUMENTS: Instrument[] = INDIA_EQUITIES.map((eq) => ({
  symbol: eq.symbol,
  name: eq.name,
  assetClass: "Equity",
  sector:
    eq.sector === "IT"
      ? "Technology"
      : eq.sector === "Banking" || eq.sector === "Financial Services"
      ? "Financials"
      : eq.sector === "Energy"
      ? "Energy"
      : eq.sector === "Telecom"
      ? "Communication"
      : eq.sector === "Auto" || eq.sector === "FMCG" || eq.sector === "Consumer"
      ? "Consumer"
      : eq.sector === "Pharma"
      ? "Healthcare"
      : "Industrials",
  region: "EM",
  currency: "USD",
  description: `${eq.name} (${eq.symbol}) listed on National Stock Exchange of India (NSE).`,
}));

export const ALL_UNIVERSE: Instrument[] = [...UNIVERSE, ...INDIA_INSTRUMENTS];

export const INSTRUMENT_MAP = Object.fromEntries(
  ALL_UNIVERSE.map((instrument) => [instrument.symbol.toUpperCase(), instrument]),
) as Record<string, Instrument>;

/** The instrument if it is in the static symbol directory, otherwise undefined (never a made-up stand-in). */
export function getInstrument(symbol: string): Instrument | undefined {
  return INSTRUMENT_MAP[symbol.toUpperCase().replace(/\.NS$/, "")];
}
