import type { Instrument } from "@/lib/types";

export const UNIVERSE: Instrument[] = [
  {
    symbol: "SPY",
    name: "SPDR S&P 500 ETF",
    assetClass: "Equity",
    sector: "Multi-Asset",
    region: "US",
    currency: "USD",
    betaMkt: 1,
    betaRates: -0.15,
    betaGrowth: 0.35,
    betaValue: 0.1,
    betaCmdty: 0.05,
    vol: 0.16,
    drift: 0.09,
    startPrice: 250,
    yieldPct: 1.3,
    description: "Broad US large-cap equity benchmark.",
  },
  {
    symbol: "QQQ",
    name: "Invesco QQQ Trust",
    assetClass: "Equity",
    sector: "Technology",
    region: "US",
    currency: "USD",
    betaMkt: 1.15,
    betaRates: -0.35,
    betaGrowth: 0.85,
    betaValue: -0.4,
    betaCmdty: -0.05,
    vol: 0.22,
    drift: 0.13,
    startPrice: 154,
    pe: 32,
    description: "Nasdaq-100 growth complex.",
  },
  {
    symbol: "IWM",
    name: "iShares Russell 2000",
    assetClass: "Equity",
    sector: "Multi-Asset",
    region: "US",
    currency: "USD",
    betaMkt: 1.12,
    betaRates: -0.2,
    betaGrowth: 0.25,
    betaValue: 0.35,
    betaCmdty: 0.1,
    vol: 0.24,
    drift: 0.08,
    startPrice: 134,
    description: "US small-cap beta.",
  },
  {
    symbol: "EFA",
    name: "iShares MSCI EAFE",
    assetClass: "Equity",
    sector: "Multi-Asset",
    region: "Europe",
    currency: "USD",
    betaMkt: 0.92,
    betaRates: -0.1,
    betaGrowth: 0.15,
    betaValue: 0.25,
    betaCmdty: 0.12,
    vol: 0.18,
    drift: 0.07,
    startPrice: 60,
    description: "Developed international equities.",
  },
  {
    symbol: "EEM",
    name: "iShares MSCI Emerging Markets",
    assetClass: "Equity",
    sector: "Multi-Asset",
    region: "EM",
    currency: "USD",
    betaMkt: 1.05,
    betaRates: -0.05,
    betaGrowth: 0.2,
    betaValue: 0.15,
    betaCmdty: 0.35,
    vol: 0.21,
    drift: 0.07,
    startPrice: 39,
    description: "Emerging-market equity beta.",
  },
  {
    symbol: "AAPL",
    name: "Apple Inc.",
    assetClass: "Equity",
    sector: "Technology",
    region: "US",
    currency: "USD",
    betaMkt: 1.18,
    betaRates: -0.25,
    betaGrowth: 0.7,
    betaValue: -0.15,
    betaCmdty: -0.05,
    vol: 0.28,
    drift: 0.16,
    startPrice: 39,
    pe: 29,
    description: "Global consumer-tech franchise.",
  },
  {
    symbol: "MSFT",
    name: "Microsoft Corporation",
    assetClass: "Equity",
    sector: "Technology",
    region: "US",
    currency: "USD",
    betaMkt: 1.1,
    betaRates: -0.3,
    betaGrowth: 0.75,
    betaValue: -0.2,
    betaCmdty: -0.08,
    vol: 0.26,
    drift: 0.15,
    startPrice: 101,
    pe: 34,
    description: "Enterprise software and cloud compounder.",
  },
  {
    symbol: "NVDA",
    name: "NVIDIA Corporation",
    assetClass: "Equity",
    sector: "Technology",
    region: "US",
    currency: "USD",
    betaMkt: 1.55,
    betaRates: -0.45,
    betaGrowth: 1.2,
    betaValue: -0.55,
    betaCmdty: -0.1,
    vol: 0.48,
    drift: 0.28,
    startPrice: 4.1,
    pe: 48,
    description: "Accelerated computing and AI infrastructure.",
  },
  {
    symbol: "GOOGL",
    name: "Alphabet Inc.",
    assetClass: "Equity",
    sector: "Communication",
    region: "US",
    currency: "USD",
    betaMkt: 1.12,
    betaRates: -0.22,
    betaGrowth: 0.65,
    betaValue: -0.1,
    betaCmdty: -0.04,
    vol: 0.27,
    drift: 0.14,
    startPrice: 52,
    pe: 24,
    description: "Search, YouTube, and cloud advertising platform.",
  },
  {
    symbol: "AMZN",
    name: "Amazon.com Inc.",
    assetClass: "Equity",
    sector: "Consumer",
    region: "US",
    currency: "USD",
    betaMkt: 1.22,
    betaRates: -0.28,
    betaGrowth: 0.8,
    betaValue: -0.25,
    betaCmdty: 0.02,
    vol: 0.32,
    drift: 0.15,
    startPrice: 75,
    pe: 38,
    description: "Commerce, AWS, and advertising flywheel.",
  },
  {
    symbol: "META",
    name: "Meta Platforms Inc.",
    assetClass: "Equity",
    sector: "Communication",
    region: "US",
    currency: "USD",
    betaMkt: 1.25,
    betaRates: -0.2,
    betaGrowth: 0.7,
    betaValue: -0.05,
    betaCmdty: -0.02,
    vol: 0.36,
    drift: 0.14,
    startPrice: 131,
    pe: 26,
    description: "Social graph and performance advertising.",
  },
  {
    symbol: "JPM",
    name: "JPMorgan Chase & Co.",
    assetClass: "Equity",
    sector: "Financials",
    region: "US",
    currency: "USD",
    betaMkt: 1.08,
    betaRates: 0.35,
    betaGrowth: 0.1,
    betaValue: 0.45,
    betaCmdty: 0.08,
    vol: 0.24,
    drift: 0.11,
    startPrice: 97,
    pe: 12,
    yieldPct: 2.2,
    description: "US money-center bank and markets franchise.",
  },
  {
    symbol: "GS",
    name: "Goldman Sachs Group",
    assetClass: "Equity",
    sector: "Financials",
    region: "US",
    currency: "USD",
    betaMkt: 1.2,
    betaRates: 0.4,
    betaGrowth: 0.15,
    betaValue: 0.4,
    betaCmdty: 0.1,
    vol: 0.28,
    drift: 0.1,
    startPrice: 167,
    pe: 13,
    description: "Institutional markets, IBD, and asset management.",
  },
  {
    symbol: "BRK.B",
    name: "Berkshire Hathaway",
    assetClass: "Equity",
    sector: "Financials",
    region: "US",
    currency: "USD",
    betaMkt: 0.82,
    betaRates: 0.1,
    betaGrowth: -0.05,
    betaValue: 0.55,
    betaCmdty: 0.12,
    vol: 0.18,
    drift: 0.09,
    startPrice: 204,
    pe: 16,
    description: "Insurance float and compound capital allocator.",
  },
  {
    symbol: "JNJ",
    name: "Johnson & Johnson",
    assetClass: "Equity",
    sector: "Healthcare",
    region: "US",
    currency: "USD",
    betaMkt: 0.55,
    betaRates: -0.05,
    betaGrowth: 0.05,
    betaValue: 0.25,
    betaCmdty: 0,
    vol: 0.16,
    drift: 0.07,
    startPrice: 128,
    pe: 17,
    yieldPct: 3.1,
    description: "Defensive healthcare conglomerate.",
  },
  {
    symbol: "UNH",
    name: "UnitedHealth Group",
    assetClass: "Equity",
    sector: "Healthcare",
    region: "US",
    currency: "USD",
    betaMkt: 0.7,
    betaRates: -0.08,
    betaGrowth: 0.2,
    betaValue: 0.15,
    betaCmdty: 0,
    vol: 0.2,
    drift: 0.12,
    startPrice: 249,
    pe: 19,
    description: "Managed care and Optum services platform.",
  },
  {
    symbol: "XOM",
    name: "Exxon Mobil Corporation",
    assetClass: "Equity",
    sector: "Energy",
    region: "US",
    currency: "USD",
    betaMkt: 0.85,
    betaRates: 0.05,
    betaGrowth: -0.1,
    betaValue: 0.35,
    betaCmdty: 0.95,
    vol: 0.26,
    drift: 0.08,
    startPrice: 68,
    pe: 14,
    yieldPct: 3.4,
    description: "Integrated oil major, high commodity beta.",
  },
  {
    symbol: "CVX",
    name: "Chevron Corporation",
    assetClass: "Equity",
    sector: "Energy",
    region: "US",
    currency: "USD",
    betaMkt: 0.8,
    betaRates: 0.04,
    betaGrowth: -0.08,
    betaValue: 0.32,
    betaCmdty: 0.9,
    vol: 0.24,
    drift: 0.07,
    startPrice: 109,
    pe: 15,
    yieldPct: 3.6,
    description: "Integrated energy with disciplined capital return.",
  },
  {
    symbol: "CAT",
    name: "Caterpillar Inc.",
    assetClass: "Equity",
    sector: "Industrials",
    region: "US",
    currency: "USD",
    betaMkt: 1.05,
    betaRates: 0.1,
    betaGrowth: 0.15,
    betaValue: 0.3,
    betaCmdty: 0.45,
    vol: 0.27,
    drift: 0.1,
    startPrice: 127,
    pe: 18,
    description: "Global machinery and infrastructure cycle.",
  },
  {
    symbol: "NEE",
    name: "NextEra Energy",
    assetClass: "Equity",
    sector: "Utilities",
    region: "US",
    currency: "USD",
    betaMkt: 0.45,
    betaRates: -0.55,
    betaGrowth: 0.15,
    betaValue: 0.05,
    betaCmdty: -0.1,
    vol: 0.2,
    drift: 0.08,
    startPrice: 43,
    pe: 22,
    yieldPct: 2.8,
    description: "Regulated utility plus renewables growth.",
  },
  {
    symbol: "PLD",
    name: "Prologis Inc.",
    assetClass: "Equity",
    sector: "Real Estate",
    region: "US",
    currency: "USD",
    betaMkt: 0.85,
    betaRates: -0.7,
    betaGrowth: 0.2,
    betaValue: 0.1,
    betaCmdty: 0.05,
    vol: 0.23,
    drift: 0.08,
    startPrice: 59,
    yieldPct: 3.2,
    description: "Global logistics REIT.",
  },
  {
    symbol: "TLT",
    name: "iShares 20+ Year Treasury",
    assetClass: "Fixed Income",
    sector: "Rates",
    region: "US",
    currency: "USD",
    betaMkt: -0.25,
    betaRates: -1.6,
    betaGrowth: -0.35,
    betaValue: 0.05,
    betaCmdty: -0.15,
    vol: 0.18,
    drift: 0.02,
    startPrice: 122,
    yieldPct: 4.4,
    description: "Long-duration US Treasury exposure.",
  },
  {
    symbol: "IEF",
    name: "iShares 7-10 Year Treasury",
    assetClass: "Fixed Income",
    sector: "Rates",
    region: "US",
    currency: "USD",
    betaMkt: -0.12,
    betaRates: -0.95,
    betaGrowth: -0.2,
    betaValue: 0.02,
    betaCmdty: -0.08,
    vol: 0.09,
    drift: 0.025,
    startPrice: 102,
    yieldPct: 4.1,
    description: "Intermediate Treasury duration.",
  },
  {
    symbol: "LQD",
    name: "iShares IG Corporate Bond",
    assetClass: "Fixed Income",
    sector: "Credit",
    region: "US",
    currency: "USD",
    betaMkt: 0.18,
    betaRates: -0.7,
    betaGrowth: 0.05,
    betaValue: 0.05,
    betaCmdty: 0.02,
    vol: 0.08,
    drift: 0.035,
    startPrice: 113,
    yieldPct: 5.1,
    description: "Investment-grade credit beta.",
  },
  {
    symbol: "HYG",
    name: "iShares High Yield Corporate",
    assetClass: "Fixed Income",
    sector: "Credit",
    region: "US",
    currency: "USD",
    betaMkt: 0.42,
    betaRates: -0.25,
    betaGrowth: 0.2,
    betaValue: 0.15,
    betaCmdty: 0.12,
    vol: 0.1,
    drift: 0.05,
    startPrice: 81,
    yieldPct: 7.2,
    description: "US high-yield credit risk premium.",
  },
  {
    symbol: "TIP",
    name: "iShares TIPS Bond",
    assetClass: "Fixed Income",
    sector: "Rates",
    region: "US",
    currency: "USD",
    betaMkt: -0.05,
    betaRates: -0.55,
    betaGrowth: -0.05,
    betaValue: 0,
    betaCmdty: 0.25,
    vol: 0.07,
    drift: 0.03,
    startPrice: 110,
    yieldPct: 2.1,
    description: "Inflation-linked Treasuries.",
  },
  {
    symbol: "GLD",
    name: "SPDR Gold Shares",
    assetClass: "Commodity",
    sector: "Precious Metals",
    region: "Global",
    currency: "USD",
    betaMkt: 0.08,
    betaRates: -0.45,
    betaGrowth: -0.1,
    betaValue: 0.05,
    betaCmdty: 0.55,
    vol: 0.15,
    drift: 0.06,
    startPrice: 128,
    description: "Physical gold proxy.",
  },
  {
    symbol: "SLV",
    name: "iShares Silver Trust",
    assetClass: "Commodity",
    sector: "Precious Metals",
    region: "Global",
    currency: "USD",
    betaMkt: 0.25,
    betaRates: -0.3,
    betaGrowth: 0.05,
    betaValue: 0.1,
    betaCmdty: 0.7,
    vol: 0.28,
    drift: 0.07,
    startPrice: 14.5,
    description: "Silver industrial/monetary hybrid.",
  },
  {
    symbol: "USO",
    name: "United States Oil Fund",
    assetClass: "Commodity",
    sector: "Energy Commodity",
    region: "Global",
    currency: "USD",
    betaMkt: 0.35,
    betaRates: 0.05,
    betaGrowth: 0.15,
    betaValue: 0.1,
    betaCmdty: 1.4,
    vol: 0.35,
    drift: 0.04,
    startPrice: 78,
    description: "WTI crude oil futures overlay.",
  },
  {
    symbol: "DBC",
    name: "Invesco DB Commodity Index",
    assetClass: "Commodity",
    sector: "Energy Commodity",
    region: "Global",
    currency: "USD",
    betaMkt: 0.22,
    betaRates: 0.02,
    betaGrowth: 0.12,
    betaValue: 0.08,
    betaCmdty: 1.1,
    vol: 0.18,
    drift: 0.045,
    startPrice: 15,
    description: "Broad commodity basket.",
  },
  {
    symbol: "UUP",
    name: "Invesco DB US Dollar Index",
    assetClass: "FX",
    sector: "Currency",
    region: "US",
    currency: "USD",
    betaMkt: -0.18,
    betaRates: 0.55,
    betaGrowth: -0.15,
    betaValue: 0.05,
    betaCmdty: -0.35,
    vol: 0.08,
    drift: 0.015,
    startPrice: 25.4,
    description: "USD vs basket of G10 currencies.",
  },
  {
    symbol: "VXUS",
    name: "Vanguard Total Intl Stock",
    assetClass: "Equity",
    sector: "Multi-Asset",
    region: "Global",
    currency: "USD",
    betaMkt: 0.95,
    betaRates: -0.08,
    betaGrowth: 0.18,
    betaValue: 0.22,
    betaCmdty: 0.18,
    vol: 0.17,
    drift: 0.07,
    startPrice: 47,
    description: "All-world ex-US equity.",
  },
  {
    symbol: "BND",
    name: "Vanguard Total Bond Market",
    assetClass: "Fixed Income",
    sector: "Rates",
    region: "US",
    currency: "USD",
    betaMkt: 0.02,
    betaRates: -0.8,
    betaGrowth: -0.1,
    betaValue: 0.02,
    betaCmdty: -0.04,
    vol: 0.06,
    drift: 0.03,
    startPrice: 79,
    yieldPct: 4.3,
    description: "US aggregate fixed income.",
  },
  {
    symbol: "VNQ",
    name: "Vanguard Real Estate ETF",
    assetClass: "Equity",
    sector: "Real Estate",
    region: "US",
    currency: "USD",
    betaMkt: 0.9,
    betaRates: -0.75,
    betaGrowth: 0.1,
    betaValue: 0.2,
    betaCmdty: 0.05,
    vol: 0.21,
    drift: 0.07,
    startPrice: 76,
    yieldPct: 3.9,
    description: "US REIT complex.",
  },
  {
    symbol: "ASML",
    name: "ASML Holding",
    assetClass: "Equity",
    sector: "Technology",
    region: "Europe",
    currency: "USD",
    betaMkt: 1.28,
    betaRates: -0.35,
    betaGrowth: 0.95,
    betaValue: -0.3,
    betaCmdty: 0.05,
    vol: 0.34,
    drift: 0.16,
    startPrice: 156,
    pe: 36,
    description: "EUVlithography monopoly in the semiconductor stack.",
  },
  {
    symbol: "TSM",
    name: "Taiwan Semiconductor",
    assetClass: "Equity",
    sector: "Technology",
    region: "EM",
    currency: "USD",
    betaMkt: 1.2,
    betaRates: -0.25,
    betaGrowth: 0.9,
    betaValue: -0.15,
    betaCmdty: 0.08,
    vol: 0.32,
    drift: 0.15,
    startPrice: 37,
    pe: 22,
    description: "Foundry backbone of global compute.",
  },
  {
    symbol: "LLY",
    name: "Eli Lilly and Company",
    assetClass: "Equity",
    sector: "Healthcare",
    region: "US",
    currency: "USD",
    betaMkt: 0.65,
    betaRates: -0.15,
    betaGrowth: 0.55,
    betaValue: -0.2,
    betaCmdty: 0,
    vol: 0.25,
    drift: 0.18,
    startPrice: 115,
    pe: 41,
    description: "Incretin franchise and late-stage pipeline.",
  },
  {
    symbol: "AVGO",
    name: "Broadcom Inc.",
    assetClass: "Equity",
    sector: "Technology",
    region: "US",
    currency: "USD",
    betaMkt: 1.18,
    betaRates: -0.28,
    betaGrowth: 0.85,
    betaValue: -0.15,
    betaCmdty: 0,
    vol: 0.3,
    drift: 0.17,
    startPrice: 254,
    pe: 33,
    description: "Custom silicon, networking, and infrastructure software.",
  },
];

import { INDIA_EQUITIES } from "@/lib/feeds/india/instruments";

const INDIA_INSTRUMENTS: Instrument[] = INDIA_EQUITIES.map((eq) => ({
  symbol: eq.symbol,
  name: eq.name,
  assetClass: "Equity",
  sector:
    eq.sector === "IT"
      ? "Technology"
      : eq.sector === "Banking" || eq.sector === "Financial Services"
      ? "Financials"
      : eq.sector === "Energy"
      ? "Energy"
      : eq.sector === "Telecom"
      ? "Communication"
      : eq.sector === "Auto" || eq.sector === "FMCG" || eq.sector === "Consumer"
      ? "Consumer"
      : eq.sector === "Pharma"
      ? "Healthcare"
      : "Industrials",
  region: "EM",
  currency: "USD",
  betaMkt: 1.0,
  betaRates: -0.1,
  betaGrowth: 0.4,
  betaValue: 0.2,
  betaCmdty: 0.1,
  vol: 0.22,
  drift: 0.12,
  startPrice: 1000,
  description: `${eq.name} (${eq.symbol}) listed on National Stock Exchange of India (NSE).`,
}));

export const ALL_UNIVERSE: Instrument[] = [...UNIVERSE, ...INDIA_INSTRUMENTS];

export const INSTRUMENT_MAP = Object.fromEntries(
  ALL_UNIVERSE.map((instrument) => [instrument.symbol.toUpperCase(), instrument]),
) as Record<string, Instrument>;

export function getInstrument(symbol: string): Instrument {
  const sym = symbol.toUpperCase().replace(/\.NS$/, "");
  const instrument = INSTRUMENT_MAP[sym];
  if (instrument) return instrument;

  return {
    symbol: sym,
    name: sym,
    assetClass: "Equity",
    sector: "Technology",
    region: "Global",
    currency: "USD",
    betaMkt: 1.0,
    betaRates: 0,
    betaGrowth: 0.5,
    betaValue: 0,
    betaCmdty: 0,
    vol: 0.2,
    drift: 0.1,
    startPrice: 100,
    description: `${sym} equity position.`,
  };
}
