/** Short names for /research search bar typewriter (mostly Nifty 50 + a few US tickers). */
export const RESEARCH_SEARCH_TYPING_SAMPLES: readonly string[] = [
  "Reliance",
  "TCS",
  "HDFC Bank",
  "ICICI Bank",
  "Infosys",
  "ITC",
  "SBI",
  "Bharti Airtel",
  "Hindustan Unilever",
  "Kotak Mahindra Bank",
  "Larsen & Toubro",
  "Axis Bank",
  "Maruti Suzuki",
  "Sun Pharma",
  "Tata Steel",
  "Wipro",
  "Bajaj Finance",
  "HCL Technologies",
  "Adani Enterprises",
  "Titan",
  "Asian Paints",
  "Nestlé India",
  "UltraTech Cement",
  "Power Grid",
  "NTPC",
  "ONGC",
  "Mahindra & Mahindra",
  "Tata Motors",
  "JSW Steel",
  "Bajaj Finserv",
  "IndusInd Bank",
  "Tech Mahindra",
  "Apollo Hospitals",
  "Cipla",
  "Coal India",
  "Grasim",
  "Eicher Motors",
  "Britannia",
  "Divi's Laboratories",
  "Dr Reddy's",
  "HDFC Life",
  "SBI Life",
  "Trent",
  "BEL",
  "Shriram Finance",
  "Hindalco",
  "Adani Ports",
  "DLF",
  "Jio Financial",
  "NVDA",
];

export const RESEARCH_SEARCH_PLACEHOLDER_PREFIX =
  "Search India & US symbols, ask a question — ";

export const RESEARCH_SEARCH_PLACEHOLDER_STATIC =
  `${RESEARCH_SEARCH_PLACEHOLDER_PREFIX}Reliance, TCS, NVDA, “how to connect MCP to Claude”…`;
