import { expect, it, vi } from "vitest";
const mocks = vi.hoisted(() => ({ read: vi.fn(), db: vi.fn(), nse: vi.fn() }));
vi.mock("@/lib/db", () => ({ hasDatabase: () => true, ensureSchema: vi.fn(), sql: () => mocks.db }));
vi.mock("@/lib/research/company-pay", () => ({ readCompanyPay: mocks.read }));
vi.mock("@/lib/feeds/india/nse-session", () => ({ nseJson: mocks.nse }));
import { getCompanyLeadership } from "../company-leadership";
it("overlays new database pay on cached metadata without downloading PDFs or contacting NSE", async () => {
  const metadata = { symbol: "DBTEST", company: "Test company", checkedAt: "2026-01-01", people: [], pay: null, dividends: null, holdings: null, annualReportUrl: null, notes: ["Median-pay table not read", "Other note"] };
  mocks.db.mockResolvedValue([{ payload: metadata }]);
  const pay = { symbol: "DBTEST", fy: "FY26", rows: [], status: "unreadable", extractedBy: "rules", reason: "No readable table", sourceUrl: "https://nsearchives.nseindia.com/test.pdf", filingDate: "2026-06-01", updatedAt: "2026-06-02", ratios: [] };
  mocks.read.mockResolvedValue(pay);
  expect((await getCompanyLeadership("DBTEST")).pay).toEqual(pay);
  mocks.read.mockResolvedValue({ ...pay, status: "ok" });
  const refreshed = await getCompanyLeadership("DBTEST");
  expect(refreshed.pay?.status).toBe("ok");
  expect(refreshed.notes).toEqual(["Other note"]);
  expect(mocks.db).toHaveBeenCalledTimes(1);
  expect(mocks.db.mock.calls[0].slice(1)).toContain("leadership:v2:DBTEST");
  expect(mocks.db.mock.calls[0].slice(1)).toContain(true);
  expect(mocks.read).toHaveBeenCalledTimes(2);
  expect(mocks.nse).not.toHaveBeenCalled();
});
it("returns database pay before an uncached NSE metadata lookup finishes", async () => {
  mocks.db.mockReset().mockResolvedValue([]);
  let release!: () => void;
  const network = new Promise<never[]>((resolve) => { release = () => resolve([]); });
  mocks.nse.mockReset().mockImplementation(() => network);
  const pay = { symbol: "COLDTEST", fy: "FY26", rows: [], status: "unreadable", extractedBy: "rules", reason: "No readable table", sourceUrl: "https://nsearchives.nseindia.com/test.pdf", filingDate: "2026-06-01", updatedAt: "2026-06-02", ratios: [] };
  mocks.read.mockResolvedValue(pay);
  let task: (() => Promise<void>) | undefined;
  const first = await getCompanyLeadership("COLDTEST", { defer: (job) => { task = job; } });
  expect(first.pay).toEqual(pay);
  expect(first.refreshing).toBe(true);
  expect(task).toBeDefined();
  release();
  await task!();
  const second = await getCompanyLeadership("COLDTEST");
  expect(second.refreshing).toBeUndefined();
  expect(second.pay).toEqual(pay);
});
