import { BALANCE_FIELDS, CASHFLOW_FIELDS, INCOME_FIELDS, type FieldKey } from "@/lib/models/types";

export const ALL_MODEL_FIELDS: FieldKey[] = [...INCOME_FIELDS, ...BALANCE_FIELDS, ...CASHFLOW_FIELDS];

/** Our field key -> Yahoo fundamentals-timeseries type names to try in order (first non-null wins). */
export const FIELD_MAP: Record<FieldKey, string[]> = {
  revenue: ["TotalRevenue", "OperatingRevenue"],
  cogs: ["CostOfRevenue", "ReconciledCostOfRevenue"],
  gross_profit: ["GrossProfit"],
  sga: ["SellingGeneralAndAdministration"],
  rnd: ["ResearchAndDevelopment"],
  opex_total: ["OperatingExpense"],
  operating_income: ["OperatingIncome", "TotalOperatingIncomeAsReported"],
  da: ["DepreciationAndAmortization", "ReconciledDepreciation", "DepreciationAmortizationDepletion"],
  interest_expense: ["InterestExpense", "InterestExpenseNonOperating"],
  interest_income: ["InterestIncome", "InterestIncomeNonOperating"],
  pretax_income: ["PretaxIncome"],
  tax: ["TaxProvision"],
  net_income: ["NetIncome", "NetIncomeCommonStockholders"],
  diluted_shares: ["DilutedAverageShares"],
  basic_shares: ["BasicAverageShares"],
  diluted_eps: ["DilutedEPS"],
  ebitda: ["EBITDA", "NormalizedEBITDA"],
  cash: ["CashAndCashEquivalents"],
  cash_and_sti: ["CashCashEquivalentsAndShortTermInvestments"],
  receivables: ["AccountsReceivable", "Receivables"],
  inventory: ["Inventory"],
  current_assets: ["CurrentAssets"],
  ppe: ["NetPPE"],
  goodwill_intangibles: ["GoodwillAndOtherIntangibleAssets", "Goodwill"],
  total_assets: ["TotalAssets"],
  payables: ["AccountsPayable", "Payables"],
  short_term_debt: ["CurrentDebtAndCapitalLeaseObligation", "CurrentDebt"],
  current_liabilities: ["CurrentLiabilities"],
  long_term_debt: ["LongTermDebtAndCapitalLeaseObligation", "LongTermDebt"],
  total_liabilities: ["TotalLiabilitiesNetMinorityInterest"],
  total_equity: ["TotalEquityGrossMinorityInterest", "StockholdersEquity"],
  stockholders_equity: ["StockholdersEquity"],
  retained_earnings: ["RetainedEarnings"],
  total_debt: ["TotalDebt"],
  shares_outstanding: ["OrdinarySharesNumber", "ShareIssued"],
  lease_liabilities: ["CapitalLeaseObligations", "LongTermCapitalLeaseObligation"],
  minority_interest: ["MinorityInterest"],
  preferred_equity: ["PreferredStock", "PreferredSecuritiesOutsideStockEquity"],
  pension_liability: ["NonCurrentPensionAndOtherPostretirementBenefitPlans", "PensionandOtherPostRetirementBenefitPlansCurrent"],
  lt_investments: ["LongTermEquityInvestment", "InvestmentinFinancialAssets", "InvestmentsAndAdvances"],
  cfo: ["OperatingCashFlow", "CashFlowFromContinuingOperatingActivities"],
  da_cf: ["DepreciationAndAmortization", "DepreciationAmortizationDepletion"],
  sbc: ["StockBasedCompensation"],
  change_wc: ["ChangeInWorkingCapital"],
  capex: ["CapitalExpenditure", "PurchaseOfPPE"],
  cfi: ["InvestingCashFlow", "CashFlowFromContinuingInvestingActivities"],
  cff: ["FinancingCashFlow", "CashFlowFromContinuingFinancingActivities"],
  dividends: ["CashDividendsPaid", "CommonStockDividendPaid"],
  buybacks: ["RepurchaseOfCapitalStock"],
  stock_issued: ["CommonStockIssuance", "IssuanceOfCapitalStock"],
  debt_issued: ["IssuanceOfDebt", "LongTermDebtIssuance"],
  debt_repaid: ["RepaymentOfDebt", "LongTermDebtPayments"],
  begin_cash: ["BeginningCashPosition"],
  end_cash: ["EndCashPosition"],
  net_change_cash: ["ChangesInCash"],
  free_cash_flow: ["FreeCashFlow"],
};

export const REVENUE_TIMESERIES_KEYS = FIELD_MAP.revenue;

/** Exchange suffix -> benchmark index used for the beta regression. */
export const INDEX_BY_SUFFIX: Record<string, [string, string]> = {
  "": ["^GSPC", "S&P 500"],
  NS: ["^NSEI", "NIFTY 50"],
  BO: ["^BSESN", "BSE SENSEX"],
  L: ["^FTSE", "FTSE 100"],
  DE: ["^GDAXI", "DAX"],
  PA: ["^FCHI", "CAC 40"],
  T: ["^N225", "Nikkei 225"],
  HK: ["^HSI", "Hang Seng"],
  TO: ["^GSPTSE", "S&P/TSX"],
  AX: ["^AXJO", "S&P/ASX 200"],
  SS: ["000001.SS", "SSE Composite"],
  SZ: ["399001.SZ", "SZSE Component"],
  KS: ["^KS11", "KOSPI"],
  SW: ["^SSMI", "SMI"],
  AS: ["^AEX", "AEX"],
  MI: ["FTSEMIB.MI", "FTSE MIB"],
  MC: ["^IBEX", "IBEX 35"],
  SA: ["^BVSP", "Bovespa"],
  MX: ["^MXX", "IPC Mexico"],
  TW: ["^TWII", "TAIEX"],
  SI: ["^STI", "Straits Times"],
  JO: ["^J203.JO", "JSE All Share"],
  ST: ["^OMX", "OMX Stockholm 30"],
  CO: ["^OMXC25", "OMX Copenhagen 25"],
  OL: ["^OSEAX", "Oslo All Share"],
  HE: ["^OMXH25", "OMX Helsinki 25"],
  BR: ["^BFX", "BEL 20"],
  VI: ["^ATX", "ATX"],
};

/** Minor-unit quote currencies used by Yahoo (pence, cents, agorot) -> [major currency, divisor]. */
export const MINOR_UNITS: Record<string, [string, number]> = {
  GBp: ["GBP", 100],
  GBX: ["GBP", 100],
  ZAc: ["ZAR", 100],
  ILA: ["ILS", 100],
};

/** Yahoo "trailing" (TTM) timeseries types used for current-multiple sanity checks and comps. */
export const TTM_TYPES = {
  revenue: "TotalRevenue",
  ebitda: "EBITDA",
  ebit: "OperatingIncome",
  net_income: "NetIncome",
} as const;
