import type { MutualFund } from "./types";

export const MUTUAL_FUNDS_STORE: MutualFund[] = [
  {
    id: "parag-parikh-flexi-cap",
    amfiCode: "122639",
    name: "Parag Parikh Flexi Cap Fund - Direct Plan - Growth",
    shortName: "PPFAS Flexi Cap",
    amc: "PPFAS Mutual Fund",
    category: "Flexi Cap",
    benchmark: "NIFTY 500 TRI",
    aumCr: 74850.25,
    nav: 84.62,
    navDate: "2026-09-29",
    expenseRatioPct: 0.61,
    riskRating: "Very High",
    inceptionDate: "2013-05-24",
    disclosureDate: "2026-09-10",
    disclosureUrl: "https://amc.ppfas.com/downloads/portfolio-disclosure/",
    concentration: {
      top5WeightPct: 32.8,
      top10WeightPct: 54.2,
      totalHoldingsCount: 38,
      hhi: 412,
      effectiveNumStocks: 24.3,
      marketCapBreakdown: {
        largeCapPct: 68.5,
        midCapPct: 9.8,
        smallCapPct: 7.5,
        cashPct: 14.2,
      },
    },
    factorExposure: [
      {
        factor: "Value",
        score: 1.45,
        label: "Deep Value & Cash Discipline",
        percentile: 88,
        description: "Focus on cash-flow generative franchises purchased at reasonable valuations.",
      },
      {
        factor: "Quality",
        score: 1.72,
        label: "High Moat Quality",
        percentile: 94,
        description: "High return on capital employed (ROCE) and negligible leverage.",
      },
      {
        factor: "Low Volatility",
        score: 1.15,
        label: "Superior Downside Protection",
        percentile: 91,
        description: "Buffer of cash / arbitrage suppresses market drawdowns during corrections.",
      },
      {
        factor: "Momentum",
        score: -0.35,
        label: "Contrarian / Low Momentum",
        percentile: 38,
        description: "Willing to hold unloved compounders through consolidation phases.",
      },
      {
        factor: "Growth",
        score: 0.65,
        label: "Moderate Growth",
        percentile: 55,
        description: "Prioritizes earnings durability over hyper-growth multiples.",
      },
      {
        factor: "Size Tilt",
        score: 0.85,
        label: "Large-Cap Oriented",
        percentile: 72,
        description: "Dominant weight in mega-cap leaders with opportunistic mid-cap exposure.",
      },
    ],
    sectorExposure: [
      { sector: "Financial Services", weightPct: 28.5, benchmarkWeightPct: 30.2, diffPct: -1.7 },
      { sector: "Consumer Goods & FMCG", weightPct: 14.2, benchmarkWeightPct: 8.5, diffPct: +5.7 },
      { sector: "Energy & Utilities", weightPct: 12.8, benchmarkWeightPct: 9.4, diffPct: +3.4 },
      { sector: "Information Technology", weightPct: 11.5, benchmarkWeightPct: 10.8, diffPct: +0.7 },
      { sector: "Automobile & Auto Components", weightPct: 8.4, benchmarkWeightPct: 6.9, diffPct: +1.5 },
      { sector: "Healthcare & Pharma", weightPct: 4.8, benchmarkWeightPct: 5.6, diffPct: -0.8 },
      { sector: "Capital Goods", weightPct: 3.2, benchmarkWeightPct: 6.8, diffPct: -3.6 },
      { sector: "Cash, Repos & Debt Equivalents", weightPct: 14.2, benchmarkWeightPct: 0.0, diffPct: +14.2 },
      { sector: "Others", weightPct: 2.4, benchmarkWeightPct: 21.8, diffPct: -19.4 },
    ],
    managerBehaviour: {
      managerName: "Rajeev Thakkar & Raunak Onkar",
      managerTenureYears: 13.3,
      turnoverRatioPct: 16.4,
      activeSharePct: 74.8,
      philosophy: "Value investing with cash dry-powder, low turnover, and strong owner-operator alignment.",
      cashStance: {
        currentCashPct: 14.2,
        cashTrend: "STABLE",
        cashHistory: [
          { month: "Jun 2026", cashPct: 15.1 },
          { month: "Jul 2026", cashPct: 14.6 },
          { month: "Aug 2026", cashPct: 14.0 },
          { month: "Sep 2026", cashPct: 14.2 },
        ],
      },
      convictionBets: [
        {
          symbol: "ITC",
          name: "ITC Limited",
          fundWeightPct: 6.85,
          benchmarkWeightPct: 2.85,
          activeWeightPct: 4.0,
          rationale: "Dominant FMCG cash engine, demerger value unlock, and >3% dividend yield.",
        },
        {
          symbol: "POWERGRID",
          name: "Power Grid Corp of India",
          fundWeightPct: 5.4,
          benchmarkWeightPct: 1.2,
          activeWeightPct: 4.2,
          rationale: "Regulated ROE utility benefiting from India's inter-state power grid capex.",
        },
        {
          symbol: "COALINDIA",
          name: "Coal India Limited",
          fundWeightPct: 5.15,
          benchmarkWeightPct: 0.85,
          activeWeightPct: 4.3,
          rationale: "Monopoly domestic supplier, huge free cash flow, and strong shareholder yield.",
        },
        {
          symbol: "CDSL",
          name: "Central Depository Services Ltd",
          fundWeightPct: 3.5,
          benchmarkWeightPct: 0.25,
          activeWeightPct: 3.25,
          rationale: "Structural beneficiary of Indian retail demat account financialization.",
        },
      ],
    },
    holdings: [
      {
        symbol: "HDFCBANK",
        name: "HDFC Bank Limited",
        isin: "INE040A01034",
        sector: "Financial Services",
        weightPct: 8.24,
        shares: 36800000,
        marketValueCr: 6168.0,
        marketCapCategory: "Large Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 3.8,
        sharesChangeCount: 1350000,
        prevShares: 35450000,
        currentPriceInr: 1676.0,
      },
      {
        symbol: "BAJFINANCE",
        name: "Bajaj Finance Limited",
        isin: "INE296A01032",
        sector: "Financial Services",
        weightPct: 7.15,
        shares: 7250000,
        marketValueCr: 5351.5,
        marketCapCategory: "Large Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 4.2,
        sharesChangeCount: 290000,
        prevShares: 6960000,
        currentPriceInr: 7380.0,
      },
      {
        symbol: "ITC",
        name: "ITC Limited",
        isin: "INE154A01025",
        sector: "Consumer Goods & FMCG",
        weightPct: 6.85,
        shares: 114200000,
        marketValueCr: 5127.5,
        marketCapCategory: "Large Cap",
        changeStatus: "UNCHANGED",
        sharesChangePct: 0.0,
        currentPriceInr: 449.0,
      },
      {
        symbol: "POWERGRID",
        name: "Power Grid Corp of India",
        isin: "INE752E01010",
        sector: "Energy & Utilities",
        weightPct: 5.4,
        shares: 124500000,
        marketValueCr: 4041.5,
        marketCapCategory: "Large Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 2.5,
        sharesChangeCount: 3000000,
        prevShares: 121500000,
        currentPriceInr: 324.5,
      },
      {
        symbol: "COALINDIA",
        name: "Coal India Limited",
        isin: "INE522F01014",
        sector: "Energy & Utilities",
        weightPct: 5.15,
        shares: 78500000,
        marketValueCr: 3854.0,
        marketCapCategory: "Large Cap",
        changeStatus: "UNCHANGED",
        sharesChangePct: 0.0,
        currentPriceInr: 491.0,
      },
      {
        symbol: "ICICIBANK",
        name: "ICICI Bank Limited",
        isin: "INE090A01021",
        sector: "Financial Services",
        weightPct: 4.92,
        shares: 30100000,
        marketValueCr: 3682.0,
        marketCapCategory: "Large Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 5.1,
        sharesChangeCount: 1450000,
        prevShares: 28650000,
        currentPriceInr: 1223.0,
      },
      {
        symbol: "HCLTECH",
        name: "HCL Technologies Limited",
        isin: "INE860A01027",
        sector: "Information Technology",
        weightPct: 4.65,
        shares: 20200000,
        marketValueCr: 3480.5,
        marketCapCategory: "Large Cap",
        changeStatus: "UNCHANGED",
        sharesChangePct: 0.0,
        currentPriceInr: 1723.0,
      },
      {
        symbol: "AXISBANK",
        name: "Axis Bank Limited",
        isin: "INE238A01034",
        sector: "Financial Services",
        weightPct: 3.95,
        shares: 24200000,
        marketValueCr: 2956.0,
        marketCapCategory: "Large Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 6.4,
        sharesChangeCount: 1450000,
        prevShares: 22750000,
        currentPriceInr: 1221.5,
      },
      {
        symbol: "CDSL",
        name: "Central Depository Services Ltd",
        isin: "INE736A01011",
        sector: "Financial Services",
        weightPct: 3.5,
        shares: 16500000,
        marketValueCr: 2619.5,
        marketCapCategory: "Mid Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 7.8,
        sharesChangeCount: 1200000,
        prevShares: 15300000,
        currentPriceInr: 1587.5,
      },
      {
        symbol: "MARUTI",
        name: "Maruti Suzuki India Limited",
        isin: "INE585B01010",
        sector: "Automobile & Auto Components",
        weightPct: 3.25,
        shares: 1950000,
        marketValueCr: 2432.5,
        marketCapCategory: "Large Cap",
        changeStatus: "UNCHANGED",
        sharesChangePct: 0.0,
        currentPriceInr: 12475.0,
      },
      {
        symbol: "ZOMATO",
        name: "Zomato Limited",
        isin: "INE758T01015",
        sector: "Consumer Goods & FMCG",
        weightPct: 2.85,
        shares: 78000000,
        marketValueCr: 2133.0,
        marketCapCategory: "Large Cap",
        changeStatus: "NEW",
        sharesChangePct: 100.0,
        sharesChangeCount: 78000000,
        prevShares: 0,
        currentPriceInr: 273.5,
      },
      {
        symbol: "BHARTIARTL",
        name: "Bharti Airtel Limited",
        isin: "INE397D01024",
        sector: "Telecommunication",
        weightPct: 2.45,
        shares: 11200000,
        marketValueCr: 1833.5,
        marketCapCategory: "Large Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 8.5,
        sharesChangeCount: 880000,
        prevShares: 10320000,
        currentPriceInr: 1637.0,
      },
      {
        symbol: "WIPRO",
        name: "Wipro Limited",
        isin: "INE075A01022",
        sector: "Information Technology",
        weightPct: 1.15,
        shares: 16200000,
        marketValueCr: 860.5,
        marketCapCategory: "Large Cap",
        changeStatus: "TRIMMED",
        sharesChangePct: -22.4,
        sharesChangeCount: -4700000,
        prevShares: 20900000,
        currentPriceInr: 531.0,
      },
    ],
    changesMoM: {
      month: "September 2026",
      newEntries: [
        {
          symbol: "ZOMATO",
          name: "Zomato Limited",
          isin: "INE758T01015",
          sector: "Consumer Services",
          weightPct: 2.85,
          shares: 78000000,
          marketValueCr: 2133.0,
          marketCapCategory: "Large Cap",
          changeStatus: "NEW",
          sharesChangePct: 100.0,
          sharesChangeCount: 78000000,
          currentPriceInr: 273.5,
        },
      ],
      completeExits: [
        {
          symbol: "BANDHANBNK",
          name: "Bandhan Bank Limited",
          isin: "INE545U01014",
          sector: "Financial Services",
          weightPct: 0.0,
          shares: 0,
          marketValueCr: 0,
          marketCapCategory: "Mid Cap",
          changeStatus: "EXIT",
          sharesChangePct: -100.0,
          prevShares: 18500000,
          currentPriceInr: 198.0,
        },
      ],
      accumulated: [
        {
          symbol: "CDSL",
          name: "Central Depository Services Ltd",
          isin: "INE736A01011",
          sector: "Financial Services",
          weightPct: 3.5,
          shares: 16500000,
          marketValueCr: 2619.5,
          marketCapCategory: "Mid Cap",
          changeStatus: "ACCUMULATED",
          sharesChangePct: 7.8,
          sharesChangeCount: 1200000,
        },
        {
          symbol: "AXISBANK",
          name: "Axis Bank Limited",
          isin: "INE238A01034",
          sector: "Financial Services",
          weightPct: 3.95,
          shares: 24200000,
          marketValueCr: 2956.0,
          marketCapCategory: "Large Cap",
          changeStatus: "ACCUMULATED",
          sharesChangePct: 6.4,
          sharesChangeCount: 1450000,
        },
        {
          symbol: "BHARTIARTL",
          name: "Bharti Airtel Limited",
          isin: "INE397D01024",
          sector: "Telecommunication",
          weightPct: 2.45,
          shares: 11200000,
          marketValueCr: 1833.5,
          marketCapCategory: "Large Cap",
          changeStatus: "ACCUMULATED",
          sharesChangePct: 8.5,
          sharesChangeCount: 880000,
        },
      ],
      trimmed: [
        {
          symbol: "WIPRO",
          name: "Wipro Limited",
          isin: "INE075A01022",
          sector: "Information Technology",
          weightPct: 1.15,
          shares: 16200000,
          marketValueCr: 860.5,
          marketCapCategory: "Large Cap",
          changeStatus: "TRIMMED",
          sharesChangePct: -22.4,
          sharesChangeCount: -4700000,
        },
      ],
    },
  },
  {
    id: "hdfc-mid-cap-opportunities",
    amfiCode: "118989",
    name: "HDFC Mid-Cap Opportunities Fund - Direct Plan - Growth",
    shortName: "HDFC Mid-Cap",
    amc: "HDFC Mutual Fund",
    category: "Mid Cap",
    benchmark: "NIFTY Midcap 150 TRI",
    aumCr: 71820.5,
    nav: 194.25,
    navDate: "2026-09-29",
    expenseRatioPct: 0.74,
    riskRating: "Very High",
    inceptionDate: "2007-06-25",
    disclosureDate: "2026-09-10",
    disclosureUrl: "https://www.hdfcfund.com/investor-services/portfolio-details",
    concentration: {
      top5WeightPct: 21.4,
      top10WeightPct: 37.8,
      totalHoldingsCount: 68,
      hhi: 245,
      effectiveNumStocks: 40.8,
      marketCapBreakdown: {
        largeCapPct: 18.2,
        midCapPct: 69.4,
        smallCapPct: 7.8,
        cashPct: 4.6,
      },
    },
    factorExposure: [
      {
        factor: "Growth",
        score: 1.42,
        label: "High Operating Growth",
        percentile: 86,
        description: "Exposure to emerging market-share gainers across domestic manufacturing.",
      },
      {
        factor: "Quality",
        score: 1.28,
        label: "Strong Balance Sheet",
        percentile: 82,
        description: "Focus on clean cash flows and disciplined capital allocation.",
      },
      {
        factor: "Size Tilt",
        score: -0.92,
        label: "Mid-Cap Focus",
        percentile: 89,
        description: "Structural bias towards ₹20,000 Cr to ₹80,000 Cr market capitalization.",
      },
      {
        factor: "Value",
        score: 0.35,
        label: "GARP Discipline",
        percentile: 62,
        description: "Avoids extreme momentum valuation multiples.",
      },
      {
        factor: "Momentum",
        score: 0.88,
        label: "Positive Earnings Momentum",
        percentile: 74,
        description: "Overweights sectors with upward earnings revisions.",
      },
      {
        factor: "Low Volatility",
        score: 0.25,
        label: "Moderate Beta",
        percentile: 51,
        description: "Diversified across 65+ names to cushion stock-specific volatility.",
      },
    ],
    sectorExposure: [
      { sector: "Capital Goods & Manufacturing", weightPct: 22.4, benchmarkWeightPct: 18.2, diffPct: +4.2 },
      { sector: "Financial Services", weightPct: 18.5, benchmarkWeightPct: 17.4, diffPct: +1.1 },
      { sector: "Automobile & Auto Components", weightPct: 12.8, benchmarkWeightPct: 10.5, diffPct: +2.3 },
      { sector: "Healthcare & Pharma", weightPct: 11.2, benchmarkWeightPct: 10.8, diffPct: +0.4 },
      { sector: "Information Technology", weightPct: 9.8, benchmarkWeightPct: 8.6, diffPct: +1.2 },
      { sector: "Chemicals & Materials", weightPct: 7.5, benchmarkWeightPct: 9.1, diffPct: -1.6 },
      { sector: "Consumer Services & Retail", weightPct: 6.8, benchmarkWeightPct: 8.4, diffPct: -1.6 },
      { sector: "Cash & Equivalents", weightPct: 4.6, benchmarkWeightPct: 0.0, diffPct: +4.6 },
      { sector: "Others", weightPct: 6.4, benchmarkWeightPct: 17.0, diffPct: -10.6 },
    ],
    managerBehaviour: {
      managerName: "Chirag Setalvad",
      managerTenureYears: 17.2,
      turnoverRatioPct: 22.5,
      activeSharePct: 79.4,
      philosophy: "Bottom-up growth at a reasonable price (GARP) with deep industrial and balance-sheet vetting.",
      cashStance: {
        currentCashPct: 4.6,
        cashTrend: "DECREASING",
        cashHistory: [
          { month: "Jun 2026", cashPct: 6.2 },
          { month: "Jul 2026", cashPct: 5.5 },
          { month: "Aug 2026", cashPct: 4.9 },
          { month: "Sep 2026", cashPct: 4.6 },
        ],
      },
      convictionBets: [
        {
          symbol: "BHARATFORG",
          name: "Bharat Forge Limited",
          fundWeightPct: 4.65,
          benchmarkWeightPct: 1.45,
          activeWeightPct: 3.2,
          rationale: "Global forging expansion and surging domestic defense order book.",
        },
        {
          symbol: "COFORGE",
          name: "Coforge Limited",
          fundWeightPct: 4.15,
          benchmarkWeightPct: 1.6,
          activeWeightPct: 2.55,
          rationale: "Top-tier organic revenue growth and BFS/Travel domain strength.",
        },
        {
          symbol: "VOLTAS",
          name: "Voltas Limited",
          fundWeightPct: 3.85,
          benchmarkWeightPct: 1.15,
          activeWeightPct: 2.7,
          rationale: "RAC market leadership and electromechanical engineering turnaround.",
        },
        {
          symbol: "DIXON",
          name: "Dixon Technologies (India) Ltd",
          fundWeightPct: 3.6,
          benchmarkWeightPct: 1.25,
          activeWeightPct: 2.35,
          rationale: "India electronics manufacturing services (EMS) champion with PLI tailwinds.",
        },
      ],
    },
    holdings: [
      {
        symbol: "BHARATFORG",
        name: "Bharat Forge Limited",
        isin: "INE465A01025",
        sector: "Capital Goods & Manufacturing",
        weightPct: 4.65,
        shares: 22800000,
        marketValueCr: 3339.5,
        marketCapCategory: "Mid Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 5.4,
        sharesChangeCount: 1160000,
        prevShares: 21640000,
        currentPriceInr: 1465.0,
      },
      {
        symbol: "COFORGE",
        name: "Coforge Limited",
        isin: "INE591G01017",
        sector: "Information Technology",
        weightPct: 4.15,
        shares: 4150000,
        marketValueCr: 2981.0,
        marketCapCategory: "Mid Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 8.2,
        sharesChangeCount: 315000,
        prevShares: 3835000,
        currentPriceInr: 7180.0,
      },
      {
        symbol: "VOLTAS",
        name: "Voltas Limited",
        isin: "INE226A01021",
        sector: "Consumer Goods",
        weightPct: 3.85,
        shares: 16800000,
        marketValueCr: 2765.0,
        marketCapCategory: "Mid Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 4.5,
        sharesChangeCount: 720000,
        prevShares: 16080000,
        currentPriceInr: 1646.0,
      },
      {
        symbol: "FEDERALBNK",
        name: "The Federal Bank Limited",
        isin: "INE171A01029",
        sector: "Financial Services",
        weightPct: 3.65,
        shares: 138000000,
        marketValueCr: 2621.5,
        marketCapCategory: "Mid Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 3.2,
        sharesChangeCount: 4280000,
        prevShares: 133720000,
        currentPriceInr: 190.0,
      },
      {
        symbol: "DIXON",
        name: "Dixon Technologies (India) Ltd",
        isin: "INE935N01020",
        sector: "Consumer Goods",
        weightPct: 3.6,
        shares: 2120000,
        marketValueCr: 2585.5,
        marketCapCategory: "Mid Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 12.5,
        sharesChangeCount: 235000,
        prevShares: 1885000,
        currentPriceInr: 12195.0,
      },
      {
        symbol: "MAXHEALTH",
        name: "Max Healthcare Institute Ltd",
        isin: "INE027H01010",
        sector: "Healthcare & Pharma",
        weightPct: 3.4,
        shares: 26400000,
        marketValueCr: 2442.0,
        marketCapCategory: "Large Cap",
        changeStatus: "UNCHANGED",
        sharesChangePct: 0.0,
        currentPriceInr: 925.0,
      },
      {
        symbol: "TATACOMM",
        name: "Tata Communications Limited",
        isin: "INE151A01013",
        sector: "Telecommunication",
        weightPct: 3.15,
        shares: 11800000,
        marketValueCr: 2262.5,
        marketCapCategory: "Mid Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 6.8,
        sharesChangeCount: 750000,
        prevShares: 11050000,
        currentPriceInr: 1917.0,
      },
      {
        symbol: "BALKRISIND",
        name: "Balkrishna Industries Limited",
        isin: "INE787D01026",
        sector: "Automobile & Auto Components",
        weightPct: 2.85,
        shares: 6850000,
        marketValueCr: 2046.8,
        marketCapCategory: "Mid Cap",
        changeStatus: "TRIMMED",
        sharesChangePct: -4.5,
        sharesChangeCount: -320000,
        prevShares: 7170000,
        currentPriceInr: 2988.0,
      },
      {
        symbol: "BEL",
        name: "Bharat Electronics Limited",
        isin: "INE263A01024",
        sector: "Capital Goods & Manufacturing",
        weightPct: 2.75,
        shares: 67200000,
        marketValueCr: 1975.0,
        marketCapCategory: "Large Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 9.2,
        sharesChangeCount: 5670000,
        prevShares: 61530000,
        currentPriceInr: 294.0,
      },
      {
        symbol: "ASTRAL",
        name: "Astral Limited",
        isin: "INE006I01046",
        sector: "Building Materials",
        weightPct: 2.45,
        shares: 9200000,
        marketValueCr: 1759.5,
        marketCapCategory: "Mid Cap",
        changeStatus: "UNCHANGED",
        sharesChangePct: 0.0,
        currentPriceInr: 1912.5,
      },
      {
        symbol: "TRENT",
        name: "Trent Limited",
        isin: "INE849A01020",
        sector: "Consumer Services & Retail",
        weightPct: 2.35,
        shares: 2450000,
        marketValueCr: 1688.0,
        marketCapCategory: "Large Cap",
        changeStatus: "NEW",
        sharesChangePct: 100.0,
        sharesChangeCount: 2450000,
        prevShares: 0,
        currentPriceInr: 6890.0,
      },
    ],
    changesMoM: {
      month: "September 2026",
      newEntries: [
        {
          symbol: "TRENT",
          name: "Trent Limited",
          isin: "INE849A01020",
          sector: "Consumer Services & Retail",
          weightPct: 2.35,
          shares: 2450000,
          marketValueCr: 1688.0,
          marketCapCategory: "Large Cap",
          changeStatus: "NEW",
          sharesChangePct: 100.0,
          sharesChangeCount: 2450000,
          currentPriceInr: 6890.0,
        },
      ],
      completeExits: [
        {
          symbol: "ZEEL",
          name: "Zee Entertainment Enterprises Ltd",
          isin: "INE256A01028",
          sector: "Media & Entertainment",
          weightPct: 0.0,
          shares: 0,
          marketValueCr: 0,
          marketCapCategory: "Mid Cap",
          changeStatus: "EXIT",
          sharesChangePct: -100.0,
          prevShares: 12500000,
          currentPriceInr: 132.0,
        },
      ],
      accumulated: [
        {
          symbol: "DIXON",
          name: "Dixon Technologies (India) Ltd",
          isin: "INE935N01020",
          sector: "Consumer Goods",
          weightPct: 3.6,
          shares: 2120000,
          marketValueCr: 2585.5,
          marketCapCategory: "Mid Cap",
          changeStatus: "ACCUMULATED",
          sharesChangePct: 12.5,
          sharesChangeCount: 235000,
        },
        {
          symbol: "BEL",
          name: "Bharat Electronics Limited",
          isin: "INE263A01024",
          sector: "Capital Goods & Manufacturing",
          weightPct: 2.75,
          shares: 67200000,
          marketValueCr: 1975.0,
          marketCapCategory: "Large Cap",
          changeStatus: "ACCUMULATED",
          sharesChangePct: 9.2,
          sharesChangeCount: 5670000,
        },
        {
          symbol: "COFORGE",
          name: "Coforge Limited",
          isin: "INE591G01017",
          sector: "Information Technology",
          weightPct: 4.15,
          shares: 4150000,
          marketValueCr: 2981.0,
          marketCapCategory: "Mid Cap",
          changeStatus: "ACCUMULATED",
          sharesChangePct: 8.2,
          sharesChangeCount: 315000,
        },
      ],
      trimmed: [
        {
          symbol: "BALKRISIND",
          name: "Balkrishna Industries Limited",
          isin: "INE787D01026",
          sector: "Automobile & Auto Components",
          weightPct: 2.85,
          shares: 6850000,
          marketValueCr: 2046.8,
          marketCapCategory: "Mid Cap",
          changeStatus: "TRIMMED",
          sharesChangePct: -4.5,
          sharesChangeCount: -320000,
        },
      ],
    },
  },
  {
    id: "nippon-india-small-cap",
    amfiCode: "118778",
    name: "Nippon India Small Cap Fund - Direct Plan - Growth",
    shortName: "Nippon Small Cap",
    amc: "Nippon India Mutual Fund",
    category: "Small Cap",
    benchmark: "NIFTY Smallcap 250 TRI",
    aumCr: 58640.0,
    nav: 172.48,
    navDate: "2026-09-29",
    expenseRatioPct: 0.69,
    riskRating: "Very High",
    inceptionDate: "2010-09-16",
    disclosureDate: "2026-09-10",
    disclosureUrl: "https://mf.nipponindiaim.com/investor-services/monthly-portfolio",
    concentration: {
      top5WeightPct: 14.8,
      top10WeightPct: 24.2,
      totalHoldingsCount: 185,
      hhi: 115,
      effectiveNumStocks: 86.9,
      marketCapBreakdown: {
        largeCapPct: 12.4,
        midCapPct: 16.8,
        smallCapPct: 66.5,
        cashPct: 4.3,
      },
    },
    factorExposure: [
      {
        factor: "Size Tilt",
        score: -1.75,
        label: "Extreme Small-Cap Tilt",
        percentile: 98,
        description: "Focus on under-researched micro & small cap market niches.",
      },
      {
        factor: "Growth",
        score: 1.62,
        label: "High Operating Leverage",
        percentile: 92,
        description: "Exposure to high profit expansion runway companies.",
      },
      {
        factor: "Momentum",
        score: 1.25,
        label: "Strong Price & Flow Momentum",
        percentile: 85,
        description: "Captures trending leaders across defense, power, and capital goods.",
      },
      {
        factor: "Quality",
        score: 0.72,
        label: "Emerging Quality",
        percentile: 65,
        description: "Vets corporate governance, avoiding debt-burdened promoter groups.",
      },
      {
        factor: "Value",
        score: -0.45,
        label: "Growth Over Deep Value",
        percentile: 32,
        description: "Will pay premiums for scalable niche leaders.",
      },
      {
        factor: "Low Volatility",
        score: -0.85,
        label: "High Systematic Volatility",
        percentile: 22,
        description: "Small-cap cyclicality cushioned by extreme diversification (180+ stocks).",
      },
    ],
    sectorExposure: [
      { sector: "Capital Goods & Engineering", weightPct: 24.5, benchmarkWeightPct: 19.8, diffPct: +4.7 },
      { sector: "Financial Services", weightPct: 15.2, benchmarkWeightPct: 16.5, diffPct: -1.3 },
      { sector: "Chemicals & Materials", weightPct: 11.4, benchmarkWeightPct: 10.2, diffPct: +1.2 },
      { sector: "Consumer Discretionary", weightPct: 10.8, benchmarkWeightPct: 11.5, diffPct: -0.7 },
      { sector: "Information Technology", weightPct: 9.6, benchmarkWeightPct: 8.4, diffPct: +1.2 },
      { sector: "Automobile & Ancillaries", weightPct: 8.5, benchmarkWeightPct: 7.8, diffPct: +0.7 },
      { sector: "Healthcare", weightPct: 6.2, benchmarkWeightPct: 7.5, diffPct: -1.3 },
      { sector: "Cash & Equivalents", weightPct: 4.3, benchmarkWeightPct: 0.0, diffPct: +4.3 },
      { sector: "Others", weightPct: 9.5, benchmarkWeightPct: 18.3, diffPct: -8.8 },
    ],
    managerBehaviour: {
      managerName: "Samir Rachh",
      managerTenureYears: 8.5,
      turnoverRatioPct: 28.0,
      activeSharePct: 86.2,
      philosophy: "Broad basket discovery across 180+ small caps with high runway and domestic capex tailwinds.",
      cashStance: {
        currentCashPct: 4.3,
        cashTrend: "STABLE",
        cashHistory: [
          { month: "Jun 2026", cashPct: 4.8 },
          { month: "Jul 2026", cashPct: 4.5 },
          { month: "Aug 2026", cashPct: 4.1 },
          { month: "Sep 2026", cashPct: 4.3 },
        ],
      },
      convictionBets: [
        {
          symbol: "TUBEINVEST",
          name: "Tube Investments of India Ltd",
          fundWeightPct: 3.4,
          benchmarkWeightPct: 0.8,
          activeWeightPct: 2.6,
          rationale: "Engineering excellence, EV transition, and Murugappa group capital allocation track record.",
        },
        {
          symbol: "KPITTECH",
          name: "KPIT Technologies Limited",
          fundWeightPct: 3.1,
          benchmarkWeightPct: 0.9,
          activeWeightPct: 2.2,
          rationale: "Pure-play autonomous driving and software-defined vehicle specialist.",
        },
        {
          symbol: "APARINDS",
          name: "Apar Industries Limited",
          fundWeightPct: 2.85,
          benchmarkWeightPct: 0.6,
          activeWeightPct: 2.25,
          rationale: "Global market leader in conductors and specialty oils feeding global renewable grids.",
        },
      ],
    },
    holdings: [
      {
        symbol: "TUBEINVEST",
        name: "Tube Investments of India Ltd",
        isin: "INE974X01010",
        sector: "Automobile & Ancillaries",
        weightPct: 3.4,
        shares: 4950000,
        marketValueCr: 1993.5,
        marketCapCategory: "Mid Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 6.2,
        sharesChangeCount: 290000,
        prevShares: 4660000,
        currentPriceInr: 4027.0,
      },
      {
        symbol: "HDFCBANK",
        name: "HDFC Bank Limited",
        isin: "INE040A01034",
        sector: "Financial Services",
        weightPct: 3.15,
        shares: 11020000,
        marketValueCr: 1847.0,
        marketCapCategory: "Large Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 4.5,
        sharesChangeCount: 475000,
        prevShares: 10545000,
        currentPriceInr: 1676.0,
      },
      {
        symbol: "KPITTECH",
        name: "KPIT Technologies Limited",
        isin: "INE04QT01022",
        sector: "Information Technology",
        weightPct: 3.1,
        shares: 11400000,
        marketValueCr: 1817.5,
        marketCapCategory: "Mid Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 8.5,
        sharesChangeCount: 890000,
        prevShares: 10510000,
        currentPriceInr: 1594.0,
      },
      {
        symbol: "APARINDS",
        name: "Apar Industries Limited",
        isin: "INE372A01015",
        sector: "Capital Goods & Engineering",
        weightPct: 2.85,
        shares: 1880000,
        marketValueCr: 1671.0,
        marketCapCategory: "Mid Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 5.5,
        sharesChangeCount: 98000,
        prevShares: 1782000,
        currentPriceInr: 8890.0,
      },
      {
        symbol: "BHARATDYN",
        name: "Bharat Dynamics Limited",
        isin: "INE171Z01018",
        sector: "Capital Goods & Engineering",
        weightPct: 2.3,
        shares: 12200000,
        marketValueCr: 1348.5,
        marketCapCategory: "Mid Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 14.2,
        sharesChangeCount: 1520000,
        prevShares: 10680000,
        currentPriceInr: 1105.0,
      },
      {
        symbol: "DIXON",
        name: "Dixon Technologies (India) Ltd",
        isin: "INE935N01020",
        sector: "Consumer Discretionary",
        weightPct: 2.15,
        shares: 1030000,
        marketValueCr: 1256.0,
        marketCapCategory: "Mid Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 15.0,
        sharesChangeCount: 134000,
        prevShares: 896000,
        currentPriceInr: 12195.0,
      },
      {
        symbol: "ZOMATO",
        name: "Zomato Limited",
        isin: "INE758T01015",
        sector: "Consumer Discretionary",
        weightPct: 2.1,
        shares: 45000000,
        marketValueCr: 1230.5,
        marketCapCategory: "Large Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 11.2,
        sharesChangeCount: 4530000,
        prevShares: 40470000,
        currentPriceInr: 273.5,
      },
      {
        symbol: "BEL",
        name: "Bharat Electronics Limited",
        isin: "INE263A01024",
        sector: "Capital Goods & Engineering",
        weightPct: 1.95,
        shares: 38900000,
        marketValueCr: 1143.5,
        marketCapCategory: "Large Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 7.5,
        sharesChangeCount: 2710000,
        prevShares: 36190000,
        currentPriceInr: 294.0,
      },
      {
        symbol: "KEC",
        name: "KEC International Limited",
        isin: "INE389H01022",
        sector: "Capital Goods & Engineering",
        weightPct: 1.85,
        shares: 11200000,
        marketValueCr: 1085.0,
        marketCapCategory: "Small Cap",
        changeStatus: "UNCHANGED",
        sharesChangePct: 0.0,
        currentPriceInr: 968.5,
      },
      {
        symbol: "CYIENT",
        name: "Cyient Limited",
        isin: "INE136B01020",
        sector: "Information Technology",
        weightPct: 1.65,
        shares: 5150000,
        marketValueCr: 967.5,
        marketCapCategory: "Mid Cap",
        changeStatus: "TRIMMED",
        sharesChangePct: -8.5,
        sharesChangeCount: -480000,
        prevShares: 5630000,
        currentPriceInr: 1878.0,
      },
    ],
    changesMoM: {
      month: "September 2026",
      newEntries: [
        {
          symbol: "SUZLON",
          name: "Suzlon Energy Limited",
          isin: "INE040H01021",
          sector: "Capital Goods & Engineering",
          weightPct: 1.25,
          shares: 98000000,
          marketValueCr: 733.0,
          marketCapCategory: "Mid Cap",
          changeStatus: "NEW",
          sharesChangePct: 100.0,
          sharesChangeCount: 98000000,
          currentPriceInr: 74.8,
        },
      ],
      completeExits: [
        {
          symbol: "RBLBANK",
          name: "RBL Bank Limited",
          isin: "INE976G01028",
          sector: "Financial Services",
          weightPct: 0.0,
          shares: 0,
          marketValueCr: 0,
          marketCapCategory: "Small Cap",
          changeStatus: "EXIT",
          sharesChangePct: -100.0,
          prevShares: 16800000,
          currentPriceInr: 215.0,
        },
      ],
      accumulated: [
        {
          symbol: "BHARATDYN",
          name: "Bharat Dynamics Limited",
          isin: "INE171Z01018",
          sector: "Capital Goods & Engineering",
          weightPct: 2.3,
          shares: 12200000,
          marketValueCr: 1348.5,
          marketCapCategory: "Mid Cap",
          changeStatus: "ACCUMULATED",
          sharesChangePct: 14.2,
          sharesChangeCount: 1520000,
        },
        {
          symbol: "DIXON",
          name: "Dixon Technologies (India) Ltd",
          isin: "INE935N01020",
          sector: "Consumer Discretionary",
          weightPct: 2.15,
          shares: 1030000,
          marketValueCr: 1256.0,
          marketCapCategory: "Mid Cap",
          changeStatus: "ACCUMULATED",
          sharesChangePct: 15.0,
          sharesChangeCount: 134000,
        },
        {
          symbol: "ZOMATO",
          name: "Zomato Limited",
          isin: "INE758T01015",
          sector: "Consumer Discretionary",
          weightPct: 2.1,
          shares: 45000000,
          marketValueCr: 1230.5,
          marketCapCategory: "Large Cap",
          changeStatus: "ACCUMULATED",
          sharesChangePct: 11.2,
          sharesChangeCount: 4530000,
        },
      ],
      trimmed: [
        {
          symbol: "CYIENT",
          name: "Cyient Limited",
          isin: "INE136B01020",
          sector: "Information Technology",
          weightPct: 1.65,
          shares: 5150000,
          marketValueCr: 967.5,
          marketCapCategory: "Mid Cap",
          changeStatus: "TRIMMED",
          sharesChangePct: -8.5,
          sharesChangeCount: -480000,
        },
      ],
    },
  },
  {
    id: "icici-pru-bluechip",
    amfiCode: "120586",
    name: "ICICI Prudential Bluechip Fund - Direct Plan - Growth",
    shortName: "ICICI Pru Bluechip",
    amc: "ICICI Prudential Mutual Fund",
    category: "Large Cap",
    benchmark: "NIFTY 100 TRI",
    aumCr: 59240.8,
    nav: 112.35,
    navDate: "2026-09-29",
    expenseRatioPct: 0.88,
    riskRating: "Very High",
    inceptionDate: "2008-05-23",
    disclosureDate: "2026-09-10",
    disclosureUrl: "https://www.icicipruamc.com/investor-services/monthly-portfolio",
    concentration: {
      top5WeightPct: 37.4,
      top10WeightPct: 58.6,
      totalHoldingsCount: 52,
      hhi: 485,
      effectiveNumStocks: 20.6,
      marketCapBreakdown: {
        largeCapPct: 88.5,
        midCapPct: 8.2,
        smallCapPct: 0.0,
        cashPct: 3.3,
      },
    },
    factorExposure: [
      {
        factor: "Quality",
        score: 1.85,
        label: "Bluechip Moats",
        percentile: 96,
        description: "Focus on sector oligarchs with high pricing power and ROEs.",
      },
      {
        factor: "Size Tilt",
        score: 1.95,
        label: "Mega-Cap Focus",
        percentile: 99,
        description: "Heavy anchor in India's top 30 companies.",
      },
      {
        factor: "Low Volatility",
        score: 1.25,
        label: "Low Beta Large Caps",
        percentile: 90,
        description: "Resilient performance across macro market cycles.",
      },
      {
        factor: "Growth",
        score: 0.95,
        label: "Steady Compounders",
        percentile: 68,
        description: "Predictable 12-15% earnings compounding over multi-year periods.",
      },
      {
        factor: "Value",
        score: 0.45,
        label: "Disciplined Entry",
        percentile: 58,
        description: "Trims names when valuation reaches historical upper bands.",
      },
      {
        factor: "Momentum",
        score: 0.35,
        label: "Index Tracking Core",
        percentile: 52,
        description: "Follows structural economic leadership.",
      },
    ],
    sectorExposure: [
      { sector: "Financial Services", weightPct: 34.2, benchmarkWeightPct: 32.5, diffPct: +1.7 },
      { sector: "Energy & Oil & Gas", weightPct: 13.8, benchmarkWeightPct: 11.2, diffPct: +2.6 },
      { sector: "Information Technology", weightPct: 12.5, benchmarkWeightPct: 12.0, diffPct: +0.5 },
      { sector: "Automobile & Auto Components", weightPct: 9.4, benchmarkWeightPct: 8.2, diffPct: +1.2 },
      { sector: "Capital Goods & Infra", weightPct: 8.2, benchmarkWeightPct: 7.8, diffPct: +0.4 },
      { sector: "Telecommunication", weightPct: 5.6, benchmarkWeightPct: 4.8, diffPct: +0.8 },
      { sector: "Healthcare & Pharma", weightPct: 5.1, benchmarkWeightPct: 5.4, diffPct: -0.3 },
      { sector: "Consumer Goods & FMCG", weightPct: 4.9, benchmarkWeightPct: 8.6, diffPct: -3.7 },
      { sector: "Cash & Equivalents", weightPct: 3.3, benchmarkWeightPct: 0.0, diffPct: +3.3 },
      { sector: "Others", weightPct: 3.0, benchmarkWeightPct: 9.5, diffPct: -6.5 },
    ],
    managerBehaviour: {
      managerName: "Anish Tawakley & Vaibhav Dusad",
      managerTenureYears: 9.4,
      turnoverRatioPct: 34.0,
      activeSharePct: 48.5,
      philosophy: "Disciplined large-cap allocation anchored around market leaders with superior ROCE.",
      cashStance: {
        currentCashPct: 3.3,
        cashTrend: "STABLE",
        cashHistory: [
          { month: "Jun 2026", cashPct: 3.8 },
          { month: "Jul 2026", cashPct: 3.5 },
          { month: "Aug 2026", cashPct: 3.2 },
          { month: "Sep 2026", cashPct: 3.3 },
        ],
      },
      convictionBets: [
        {
          symbol: "ICICIBANK",
          name: "ICICI Bank Limited",
          fundWeightPct: 9.4,
          benchmarkWeightPct: 7.2,
          activeWeightPct: 2.2,
          rationale: "Best-in-class return metrics, pristine asset quality, and tech-driven underwriting.",
        },
        {
          symbol: "BHARTIARTL",
          name: "Bharti Airtel Limited",
          fundWeightPct: 5.6,
          benchmarkWeightPct: 3.8,
          activeWeightPct: 1.8,
          rationale: "ARPU expansion, 5G market-share consolidation, and surging enterprise cloud revenue.",
        },
        {
          symbol: "LT",
          name: "Larsen & Toubro Limited",
          fundWeightPct: 6.8,
          benchmarkWeightPct: 4.5,
          activeWeightPct: 2.3,
          rationale: "Massive ₹5 Lakh Cr record order book spanning domestic infra and Middle East energy capex.",
        },
      ],
    },
    holdings: [
      {
        symbol: "ICICIBANK",
        name: "ICICI Bank Limited",
        isin: "INE090A01021",
        sector: "Financial Services",
        weightPct: 9.4,
        shares: 45500000,
        marketValueCr: 5564.5,
        marketCapCategory: "Large Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 4.8,
        sharesChangeCount: 2080000,
        prevShares: 43420000,
        currentPriceInr: 1223.0,
      },
      {
        symbol: "HDFCBANK",
        name: "HDFC Bank Limited",
        isin: "INE040A01034",
        sector: "Financial Services",
        weightPct: 8.85,
        shares: 31300000,
        marketValueCr: 5245.8,
        marketCapCategory: "Large Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 6.5,
        sharesChangeCount: 1910000,
        prevShares: 29390000,
        currentPriceInr: 1676.0,
      },
      {
        symbol: "RELIANCE",
        name: "Reliance Industries Limited",
        isin: "INE002A01018",
        sector: "Energy & Oil & Gas",
        weightPct: 8.1,
        shares: 16200000,
        marketValueCr: 4798.5,
        marketCapCategory: "Large Cap",
        changeStatus: "UNCHANGED",
        sharesChangePct: 0.0,
        currentPriceInr: 2962.0,
      },
      {
        symbol: "LT",
        name: "Larsen & Toubro Limited",
        isin: "INE018A01030",
        sector: "Capital Goods & Infra",
        weightPct: 6.8,
        shares: 11150000,
        marketValueCr: 4028.5,
        marketCapCategory: "Large Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 7.2,
        sharesChangeCount: 750000,
        prevShares: 10400000,
        currentPriceInr: 3613.0,
      },
      {
        symbol: "INFOSYS",
        name: "Infosys Limited",
        isin: "INE009A01021",
        sector: "Information Technology",
        weightPct: 5.85,
        shares: 22800000,
        marketValueCr: 3465.5,
        marketCapCategory: "Large Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 3.2,
        sharesChangeCount: 710000,
        prevShares: 22090000,
        currentPriceInr: 1520.0,
      },
      {
        symbol: "BHARTIARTL",
        name: "Bharti Airtel Limited",
        isin: "INE397D01024",
        sector: "Telecommunication",
        weightPct: 5.6,
        shares: 20250000,
        marketValueCr: 3315.0,
        marketCapCategory: "Large Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 5.8,
        sharesChangeCount: 1110000,
        prevShares: 19140000,
        currentPriceInr: 1637.0,
      },
      {
        symbol: "AXISBANK",
        name: "Axis Bank Limited",
        isin: "INE238A01034",
        sector: "Financial Services",
        weightPct: 4.8,
        shares: 23250000,
        marketValueCr: 2840.0,
        marketCapCategory: "Large Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 4.0,
        sharesChangeCount: 890000,
        prevShares: 22360000,
        currentPriceInr: 1221.5,
      },
      {
        symbol: "MARUTI",
        name: "Maruti Suzuki India Limited",
        isin: "INE585B01010",
        sector: "Automobile & Auto Components",
        weightPct: 4.15,
        shares: 1970000,
        marketValueCr: 2457.5,
        marketCapCategory: "Large Cap",
        changeStatus: "UNCHANGED",
        sharesChangePct: 0.0,
        currentPriceInr: 12475.0,
      },
      {
        symbol: "SBIN",
        name: "State Bank of India",
        isin: "INE062A01020",
        sector: "Financial Services",
        weightPct: 3.85,
        shares: 27800000,
        marketValueCr: 2280.5,
        marketCapCategory: "Large Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 3.5,
        sharesChangeCount: 940000,
        prevShares: 26860000,
        currentPriceInr: 820.0,
      },
      {
        symbol: "TITAN",
        name: "Titan Company Limited",
        isin: "INE280A01028",
        sector: "Consumer Goods & Retail",
        weightPct: 3.15,
        shares: 5500000,
        marketValueCr: 1865.5,
        marketCapCategory: "Large Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 6.4,
        sharesChangeCount: 330000,
        prevShares: 5170000,
        currentPriceInr: 3392.0,
      },
    ],
    changesMoM: {
      month: "September 2026",
      newEntries: [
        {
          symbol: "ZOMATO",
          name: "Zomato Limited",
          isin: "INE758T01015",
          sector: "Consumer Services",
          weightPct: 1.85,
          shares: 40000000,
          marketValueCr: 1094.0,
          marketCapCategory: "Large Cap",
          changeStatus: "NEW",
          sharesChangePct: 100.0,
          sharesChangeCount: 40000000,
          currentPriceInr: 273.5,
        },
      ],
      completeExits: [
        {
          symbol: "INDUSINDBK",
          name: "IndusInd Bank Limited",
          isin: "INE095A01012",
          sector: "Financial Services",
          weightPct: 0.0,
          shares: 0,
          marketValueCr: 0,
          marketCapCategory: "Large Cap",
          changeStatus: "EXIT",
          sharesChangePct: -100.0,
          prevShares: 8500000,
          currentPriceInr: 1445.0,
        },
      ],
      accumulated: [
        {
          symbol: "LT",
          name: "Larsen & Toubro Limited",
          isin: "INE018A01030",
          sector: "Capital Goods & Infra",
          weightPct: 6.8,
          shares: 11150000,
          marketValueCr: 4028.5,
          marketCapCategory: "Large Cap",
          changeStatus: "ACCUMULATED",
          sharesChangePct: 7.2,
          sharesChangeCount: 750000,
        },
        {
          symbol: "HDFCBANK",
          name: "HDFC Bank Limited",
          isin: "INE040A01034",
          sector: "Financial Services",
          weightPct: 8.85,
          shares: 31300000,
          marketValueCr: 5245.8,
          marketCapCategory: "Large Cap",
          changeStatus: "ACCUMULATED",
          sharesChangePct: 6.5,
          sharesChangeCount: 1910000,
        },
        {
          symbol: "TITAN",
          name: "Titan Company Limited",
          isin: "INE280A01028",
          sector: "Consumer Goods & Retail",
          weightPct: 3.15,
          shares: 5500000,
          marketValueCr: 1865.5,
          marketCapCategory: "Large Cap",
          changeStatus: "ACCUMULATED",
          sharesChangePct: 6.4,
          sharesChangeCount: 330000,
        },
      ],
      trimmed: [],
    },
  },
  {
    id: "quant-active-fund",
    amfiCode: "120828",
    name: "Quant Active Fund - Direct Plan - Growth",
    shortName: "Quant Active",
    amc: "Quant Mutual Fund",
    category: "Multi Cap",
    benchmark: "NIFTY 500 Multicap 50:25:25 TRI",
    aumCr: 11450.0,
    nav: 684.2,
    navDate: "2026-09-29",
    expenseRatioPct: 0.77,
    riskRating: "Very High",
    inceptionDate: "2001-03-20",
    disclosureDate: "2026-09-10",
    disclosureUrl: "https://quantmutual.com/statutory-disclosures",
    concentration: {
      top5WeightPct: 34.6,
      top10WeightPct: 53.8,
      totalHoldingsCount: 44,
      hhi: 420,
      effectiveNumStocks: 23.8,
      marketCapBreakdown: {
        largeCapPct: 48.2,
        midCapPct: 26.5,
        smallCapPct: 21.8,
        cashPct: 3.5,
      },
    },
    factorExposure: [
      {
        factor: "Momentum",
        score: 1.95,
        label: "Extreme Momentum Tilt",
        percentile: 99,
        description: "VLRT analytics (Valuation, Liquidity, Risk appetite, Time) chasing high relative strength.",
      },
      {
        factor: "Growth",
        score: 1.48,
        label: "Earnings Acceleration",
        percentile: 88,
        description: "Rapidly rotates capital into sectors entering cyclical acceleration.",
      },
      {
        factor: "Low Volatility",
        score: -1.25,
        label: "High Beta & Active Risk",
        percentile: 12,
        description: "Embraces market volatility to generate high alpha spreads.",
      },
      {
        factor: "Value",
        score: 0.15,
        label: "Dynamic Valuation Timing",
        percentile: 54,
        description: "Exits growth winners swiftly when predictive liquidity indicators roll over.",
      },
      {
        factor: "Quality",
        score: 0.82,
        label: "Selective Quality",
        percentile: 68,
        description: "Balances turnaround cyclicals with established compounders.",
      },
      {
        factor: "Size Tilt",
        score: 0.15,
        label: "Balanced Multi-Cap",
        percentile: 50,
        description: "Complies with 25% minimum each in Large, Mid, and Small caps.",
      },
    ],
    sectorExposure: [
      { sector: "Energy & Power", weightPct: 22.8, benchmarkWeightPct: 10.4, diffPct: +12.4 },
      { sector: "Financial Services", weightPct: 20.4, benchmarkWeightPct: 28.5, diffPct: -8.1 },
      { sector: "Metals & Mining", weightPct: 14.5, benchmarkWeightPct: 4.8, diffPct: +9.7 },
      { sector: "Healthcare & Life Sciences", weightPct: 12.4, benchmarkWeightPct: 6.8, diffPct: +5.6 },
      { sector: "Consumer Discretionary", weightPct: 11.2, benchmarkWeightPct: 9.8, diffPct: +1.4 },
      { sector: "Information Technology", weightPct: 5.4, benchmarkWeightPct: 10.2, diffPct: -4.8 },
      { sector: "Cash & Derivatives Margin", weightPct: 3.5, benchmarkWeightPct: 0.0, diffPct: +3.5 },
      { sector: "Others", weightPct: 9.8, benchmarkWeightPct: 29.5, diffPct: -19.7 },
    ],
    managerBehaviour: {
      managerName: "Sandeep Tandon & Sanjeev Sharma",
      managerTenureYears: 6.8,
      turnoverRatioPct: 148.0,
      activeSharePct: 88.5,
      philosophy: "Dynamic asset allocation utilizing proprietary VLRT framework and high portfolio velocity.",
      cashStance: {
        currentCashPct: 3.5,
        cashTrend: "DECREASING",
        cashHistory: [
          { month: "Jun 2026", cashPct: 7.8 },
          { month: "Jul 2026", cashPct: 5.2 },
          { month: "Aug 2026", cashPct: 4.1 },
          { month: "Sep 2026", cashPct: 3.5 },
        ],
      },
      convictionBets: [
        {
          symbol: "RELIANCE",
          name: "Reliance Industries Limited",
          fundWeightPct: 9.25,
          benchmarkWeightPct: 6.1,
          activeWeightPct: 3.15,
          rationale: "Telecom tariff hikes, retail profitability inflection, and new energy commissioning.",
        },
        {
          symbol: "JIOFIN",
          name: "Jio Financial Services Limited",
          fundWeightPct: 7.6,
          benchmarkWeightPct: 0.95,
          activeWeightPct: 6.65,
          rationale: "Disruptive capital base launching consumer lending, broking, and asset management.",
        },
        {
          symbol: "SAIL",
          name: "Steel Authority of India Ltd",
          fundWeightPct: 5.4,
          benchmarkWeightPct: 0.45,
          activeWeightPct: 4.95,
          rationale: "Domestic infrastructure steel demand and favorable anti-dumping duties.",
        },
      ],
    },
    holdings: [
      {
        symbol: "RELIANCE",
        name: "Reliance Industries Limited",
        isin: "INE002A01018",
        sector: "Energy & Power",
        weightPct: 9.25,
        shares: 3570000,
        marketValueCr: 1059.0,
        marketCapCategory: "Large Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 15.2,
        sharesChangeCount: 470000,
        prevShares: 3100000,
        currentPriceInr: 2962.0,
      },
      {
        symbol: "JIOFIN",
        name: "Jio Financial Services Limited",
        isin: "INE758E01017",
        sector: "Financial Services",
        weightPct: 7.6,
        shares: 24800000,
        marketValueCr: 870.5,
        marketCapCategory: "Large Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 22.0,
        sharesChangeCount: 4470000,
        prevShares: 20330000,
        currentPriceInr: 351.0,
      },
      {
        symbol: "HDFCBANK",
        name: "HDFC Bank Limited",
        isin: "INE040A01034",
        sector: "Financial Services",
        weightPct: 6.8,
        shares: 4640000,
        marketValueCr: 778.5,
        marketCapCategory: "Large Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 18.5,
        sharesChangeCount: 725000,
        prevShares: 3915000,
        currentPriceInr: 1676.0,
      },
      {
        symbol: "SAIL",
        name: "Steel Authority of India Ltd",
        isin: "INE114A01011",
        sector: "Metals & Mining",
        weightPct: 5.4,
        shares: 46500000,
        marketValueCr: 618.5,
        marketCapCategory: "Mid Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 35.0,
        sharesChangeCount: 12050000,
        prevShares: 34450000,
        currentPriceInr: 133.0,
      },
      {
        symbol: "BIOCON",
        name: "Biocon Limited",
        isin: "INE376G01013",
        sector: "Healthcare & Life Sciences",
        weightPct: 5.2,
        shares: 16500000,
        marketValueCr: 595.5,
        marketCapCategory: "Mid Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 12.0,
        sharesChangeCount: 1770000,
        prevShares: 14730000,
        currentPriceInr: 361.0,
      },
      {
        symbol: "TRENT",
        name: "Trent Limited",
        isin: "INE849A01020",
        sector: "Consumer Discretionary",
        weightPct: 4.8,
        shares: 798000,
        marketValueCr: 550.0,
        marketCapCategory: "Large Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 24.5,
        sharesChangeCount: 157000,
        prevShares: 641000,
        currentPriceInr: 6890.0,
      },
      {
        symbol: "BEL",
        name: "Bharat Electronics Limited",
        isin: "INE263A01024",
        sector: "Capital Goods",
        weightPct: 4.25,
        shares: 16550000,
        marketValueCr: 486.5,
        marketCapCategory: "Large Cap",
        changeStatus: "NEW",
        sharesChangePct: 100.0,
        sharesChangeCount: 16550000,
        prevShares: 0,
        currentPriceInr: 294.0,
      },
      {
        symbol: "DIXON",
        name: "Dixon Technologies (India) Ltd",
        isin: "INE935N01020",
        sector: "Consumer Discretionary",
        weightPct: 3.8,
        shares: 357000,
        marketValueCr: 435.0,
        marketCapCategory: "Mid Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 19.5,
        sharesChangeCount: 58000,
        prevShares: 299000,
        currentPriceInr: 12195.0,
      },
      {
        symbol: "LICHSGFIN",
        name: "LIC Housing Finance Limited",
        isin: "INE115A01026",
        sector: "Financial Services",
        weightPct: 3.4,
        shares: 5850000,
        marketValueCr: 389.0,
        marketCapCategory: "Mid Cap",
        changeStatus: "TRIMMED",
        sharesChangePct: -14.2,
        sharesChangeCount: -970000,
        prevShares: 6820000,
        currentPriceInr: 665.0,
      },
    ],
    changesMoM: {
      month: "September 2026",
      newEntries: [
        {
          symbol: "BEL",
          name: "Bharat Electronics Limited",
          isin: "INE263A01024",
          sector: "Capital Goods",
          weightPct: 4.25,
          shares: 16550000,
          marketValueCr: 486.5,
          marketCapCategory: "Large Cap",
          changeStatus: "NEW",
          sharesChangePct: 100.0,
          sharesChangeCount: 16550000,
          currentPriceInr: 294.0,
        },
      ],
      completeExits: [
        {
          symbol: "ADANIPORTS",
          name: "Adani Ports and SEZ Ltd",
          isin: "INE742F01042",
          sector: "Services & Infrastructure",
          weightPct: 0.0,
          shares: 0,
          marketValueCr: 0,
          marketCapCategory: "Large Cap",
          changeStatus: "EXIT",
          sharesChangePct: -100.0,
          prevShares: 4120000,
          currentPriceInr: 1435.0,
        },
      ],
      accumulated: [
        {
          symbol: "SAIL",
          name: "Steel Authority of India Ltd",
          isin: "INE114A01011",
          sector: "Metals & Mining",
          weightPct: 5.4,
          shares: 46500000,
          marketValueCr: 618.5,
          marketCapCategory: "Mid Cap",
          changeStatus: "ACCUMULATED",
          sharesChangePct: 35.0,
          sharesChangeCount: 12050000,
        },
        {
          symbol: "TRENT",
          name: "Trent Limited",
          isin: "INE849A01020",
          sector: "Consumer Discretionary",
          weightPct: 4.8,
          shares: 798000,
          marketValueCr: 550.0,
          marketCapCategory: "Large Cap",
          changeStatus: "ACCUMULATED",
          sharesChangePct: 24.5,
          sharesChangeCount: 157000,
        },
        {
          symbol: "JIOFIN",
          name: "Jio Financial Services Limited",
          isin: "INE758E01017",
          sector: "Financial Services",
          weightPct: 7.6,
          shares: 24800000,
          marketValueCr: 870.5,
          marketCapCategory: "Large Cap",
          changeStatus: "ACCUMULATED",
          sharesChangePct: 22.0,
          sharesChangeCount: 4470000,
        },
      ],
      trimmed: [
        {
          symbol: "LICHSGFIN",
          name: "LIC Housing Finance Limited",
          isin: "INE115A01026",
          sector: "Financial Services",
          weightPct: 3.4,
          shares: 5850000,
          marketValueCr: 389.0,
          marketCapCategory: "Mid Cap",
          changeStatus: "TRIMMED",
          sharesChangePct: -14.2,
          sharesChangeCount: -970000,
        },
      ],
    },
  },
  {
    id: "sbi-small-cap",
    amfiCode: "125497",
    name: "SBI Small Cap Fund - Direct Plan - Growth",
    shortName: "SBI Small Cap",
    amc: "SBI Mutual Fund",
    category: "Small Cap",
    benchmark: "S&P BSE 250 SmallCap TRI",
    aumCr: 32410.0,
    nav: 178.6,
    navDate: "2026-09-29",
    expenseRatioPct: 0.68,
    riskRating: "Very High",
    inceptionDate: "2009-09-09",
    disclosureDate: "2026-09-10",
    disclosureUrl: "https://www.sbimf.com/en-us/portfolios",
    concentration: {
      top5WeightPct: 19.5,
      top10WeightPct: 34.2,
      totalHoldingsCount: 56,
      hhi: 220,
      effectiveNumStocks: 45.4,
      marketCapBreakdown: {
        largeCapPct: 8.5,
        midCapPct: 18.2,
        smallCapPct: 65.8,
        cashPct: 7.5,
      },
    },
    factorExposure: [
      {
        factor: "Quality",
        score: 1.65,
        label: "Prudent Small-Cap Quality",
        percentile: 94,
        description: "Zero tolerance for high leverage or aggressive promoter pledges.",
      },
      {
        factor: "Size Tilt",
        score: -1.6,
        label: "Small-Cap Bias",
        percentile: 95,
        description: "Disciplined allocation in niche market leaders.",
      },
      {
        factor: "Value",
        score: 0.85,
        label: "Valuation Sensitive",
        percentile: 78,
        description: "Has historical track record of pausing lump-sum inflows when valuations froth.",
      },
      {
        factor: "Low Volatility",
        score: 0.65,
        label: "Superior Alpha/Beta",
        percentile: 82,
        description: "Limits downside during broad smallcap market shakeouts.",
      },
      {
        factor: "Growth",
        score: 1.15,
        label: "Sustainable Compounders",
        percentile: 76,
        description: "Targets companies that double earnings organically every 4-5 years.",
      },
      {
        factor: "Momentum",
        score: 0.45,
        label: "Moderate Momentum",
        percentile: 56,
        description: "Avoids chasing sentiment spikes; accumulates on price dips.",
      },
    ],
    sectorExposure: [
      { sector: "Capital Goods & Industrials", weightPct: 21.8, benchmarkWeightPct: 18.5, diffPct: +3.3 },
      { sector: "Consumer Discretionary", weightPct: 16.5, benchmarkWeightPct: 14.2, diffPct: +2.3 },
      { sector: "Financial Services", weightPct: 12.8, benchmarkWeightPct: 15.6, diffPct: -2.8 },
      { sector: "Building Materials & Real Estate", weightPct: 11.4, benchmarkWeightPct: 9.8, diffPct: +1.6 },
      { sector: "Healthcare & Pharma", weightPct: 9.2, benchmarkWeightPct: 8.4, diffPct: +0.8 },
      { sector: "Information Technology", weightPct: 7.6, benchmarkWeightPct: 8.9, diffPct: -1.3 },
      { sector: "Cash & Equivalents", weightPct: 7.5, benchmarkWeightPct: 0.0, diffPct: +7.5 },
      { sector: "Others", weightPct: 13.2, benchmarkWeightPct: 24.6, diffPct: -11.4 },
    ],
    managerBehaviour: {
      managerName: "R. Srinivasan",
      managerTenureYears: 13.8,
      turnoverRatioPct: 19.2,
      activeSharePct: 84.1,
      philosophy: "Patient capital in niche industrial and consumer smallcaps with low capital intensity.",
      cashStance: {
        currentCashPct: 7.5,
        cashTrend: "INCREASING",
        cashHistory: [
          { month: "Jun 2026", cashPct: 5.8 },
          { month: "Jul 2026", cashPct: 6.5 },
          { month: "Aug 2026", cashPct: 7.1 },
          { month: "Sep 2026", cashPct: 7.5 },
        ],
      },
      convictionBets: [
        {
          symbol: "BLUESTARCO",
          name: "Blue Star Limited",
          fundWeightPct: 4.8,
          benchmarkWeightPct: 1.1,
          activeWeightPct: 3.7,
          rationale: "Commercial refrigeration expansion and room AC market share surge.",
        },
        {
          symbol: "LEMONTREE",
          name: "Lemon Tree Hotels Limited",
          fundWeightPct: 4.1,
          benchmarkWeightPct: 0.85,
          activeWeightPct: 3.25,
          rationale: "Domestic tourism boom, asset-light management contract scaling, and debt paydown.",
        },
        {
          symbol: "CARBORUNIV",
          name: "Carborundum Universal Limited",
          fundWeightPct: 3.85,
          benchmarkWeightPct: 0.75,
          activeWeightPct: 3.1,
          rationale: "Abrasives and technical ceramics technology leadership with global export moat.",
        },
      ],
    },
    holdings: [
      {
        symbol: "BLUESTARCO",
        name: "Blue Star Limited",
        isin: "INE472A01039",
        sector: "Consumer Discretionary",
        weightPct: 4.8,
        shares: 9450000,
        marketValueCr: 1555.5,
        marketCapCategory: "Mid Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 4.2,
        sharesChangeCount: 380000,
        prevShares: 9070000,
        currentPriceInr: 1646.0,
      },
      {
        symbol: "LEMONTREE",
        name: "Lemon Tree Hotels Limited",
        isin: "INE970X01018",
        sector: "Consumer Discretionary",
        weightPct: 4.1,
        shares: 98500000,
        marketValueCr: 1329.0,
        marketCapCategory: "Small Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 6.8,
        sharesChangeCount: 6270000,
        prevShares: 92230000,
        currentPriceInr: 135.0,
      },
      {
        symbol: "CARBORUNIV",
        name: "Carborundum Universal Limited",
        isin: "INE120A01034",
        sector: "Capital Goods & Industrials",
        weightPct: 3.85,
        shares: 8850000,
        marketValueCr: 1248.0,
        marketCapCategory: "Mid Cap",
        changeStatus: "UNCHANGED",
        sharesChangePct: 0.0,
        currentPriceInr: 1410.0,
      },
      {
        symbol: "KALPATPOWR",
        name: "Kalpataru Projects International",
        isin: "INE220B01022",
        sector: "Capital Goods & Industrials",
        weightPct: 3.5,
        shares: 9250000,
        marketValueCr: 1134.5,
        marketCapCategory: "Small Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 5.1,
        sharesChangeCount: 450000,
        prevShares: 8800000,
        currentPriceInr: 1226.5,
      },
      {
        symbol: "FINCABLES",
        name: "Finolex Cables Limited",
        isin: "INE004A01022",
        sector: "Capital Goods & Industrials",
        weightPct: 3.25,
        shares: 7200000,
        marketValueCr: 1053.0,
        marketCapCategory: "Small Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 7.2,
        sharesChangeCount: 485000,
        prevShares: 6715000,
        currentPriceInr: 1462.5,
      },
      {
        symbol: "TIMKEN",
        name: "Timken India Limited",
        isin: "INE325A01013",
        sector: "Capital Goods & Industrials",
        weightPct: 2.85,
        shares: 2450000,
        marketValueCr: 923.5,
        marketCapCategory: "Mid Cap",
        changeStatus: "UNCHANGED",
        sharesChangePct: 0.0,
        currentPriceInr: 3770.0,
      },
      {
        symbol: "VGUARD",
        name: "V-Guard Industries Limited",
        isin: "INE951I01027",
        sector: "Consumer Discretionary",
        weightPct: 2.65,
        shares: 16800000,
        marketValueCr: 859.0,
        marketCapCategory: "Small Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 3.8,
        sharesChangeCount: 615000,
        prevShares: 16185000,
        currentPriceInr: 511.0,
      },
    ],
    changesMoM: {
      month: "September 2026",
      newEntries: [
        {
          symbol: "KIMS",
          name: "Krishna Institute of Medical Sciences",
          isin: "INE967H01017",
          sector: "Healthcare & Pharma",
          weightPct: 2.15,
          shares: 2950000,
          marketValueCr: 697.0,
          marketCapCategory: "Mid Cap",
          changeStatus: "NEW",
          sharesChangePct: 100.0,
          sharesChangeCount: 2950000,
          currentPriceInr: 2362.5,
        },
      ],
      completeExits: [
        {
          symbol: "PVRINOX",
          name: "PVR INOX Limited",
          isin: "INE191H01014",
          sector: "Media & Entertainment",
          weightPct: 0.0,
          shares: 0,
          marketValueCr: 0,
          marketCapCategory: "Small Cap",
          changeStatus: "EXIT",
          sharesChangePct: -100.0,
          prevShares: 4500000,
          currentPriceInr: 1285.0,
        },
      ],
      accumulated: [
        {
          symbol: "LEMONTREE",
          name: "Lemon Tree Hotels Limited",
          isin: "INE970X01018",
          sector: "Consumer Discretionary",
          weightPct: 4.1,
          shares: 98500000,
          marketValueCr: 1329.0,
          marketCapCategory: "Small Cap",
          changeStatus: "ACCUMULATED",
          sharesChangePct: 6.8,
          sharesChangeCount: 6270000,
        },
        {
          symbol: "FINCABLES",
          name: "Finolex Cables Limited",
          isin: "INE004A01022",
          sector: "Capital Goods & Industrials",
          weightPct: 3.25,
          shares: 7200000,
          marketValueCr: 1053.0,
          marketCapCategory: "Small Cap",
          changeStatus: "ACCUMULATED",
          sharesChangePct: 7.2,
          sharesChangeCount: 485000,
        },
      ],
      trimmed: [],
    },
  },
  {
    id: "mirae-asset-large-cap",
    amfiCode: "118834",
    name: "Mirae Asset Large Cap Fund - Direct Plan - Growth",
    shortName: "Mirae Asset Large Cap",
    amc: "Mirae Asset Mutual Fund",
    category: "Large Cap",
    benchmark: "NIFTY 100 TRI",
    aumCr: 38450.0,
    nav: 124.85,
    navDate: "2026-09-29",
    expenseRatioPct: 0.54,
    riskRating: "Very High",
    inceptionDate: "2008-04-04",
    disclosureDate: "2026-09-10",
    disclosureUrl: "https://www.miraeassetmf.co.in/downloads/portfolio",
    concentration: {
      top5WeightPct: 36.2,
      top10WeightPct: 56.4,
      totalHoldingsCount: 58,
      hhi: 460,
      effectiveNumStocks: 21.7,
      marketCapBreakdown: {
        largeCapPct: 86.4,
        midCapPct: 10.2,
        smallCapPct: 0.0,
        cashPct: 3.4,
      },
    },
    factorExposure: [
      {
        factor: "Quality",
        score: 1.78,
        label: "High Operating ROCE",
        percentile: 94,
        description: "High governance, capital return discipline, and market share moat.",
      },
      {
        factor: "Growth",
        score: 1.25,
        label: "Steady Compounders",
        percentile: 80,
        description: "Consistent 14%+ annual revenue growth profile.",
      },
      {
        factor: "Size Tilt",
        score: 1.85,
        label: "Mega-Cap Heavy",
        percentile: 96,
        description: "Concentrated core in the top 50 Indian bluechips.",
      },
      {
        factor: "Low Volatility",
        score: 1.15,
        label: "Low Drawdown Profile",
        percentile: 86,
        description: "High liquidity enables seamless portfolio defense.",
      },
      {
        factor: "Momentum",
        score: 0.45,
        label: "Neutral Momentum",
        percentile: 56,
        description: "Takes strategic contrarian positions during pullbacks.",
      },
      {
        factor: "Value",
        score: 0.35,
        label: "Reasonable Valuations",
        percentile: 52,
        description: "Trimmed positions when price-to-earnings stretches beyond 3-year mean.",
      },
    ],
    sectorExposure: [
      { sector: "Financial Services", weightPct: 33.5, benchmarkWeightPct: 32.5, diffPct: +1.0 },
      { sector: "Information Technology", weightPct: 13.8, benchmarkWeightPct: 12.0, diffPct: +1.8 },
      { sector: "Energy & Utilities", weightPct: 11.2, benchmarkWeightPct: 11.2, diffPct: 0.0 },
      { sector: "Automobile & Ancillaries", weightPct: 9.8, benchmarkWeightPct: 8.2, diffPct: +1.6 },
      { sector: "Consumer Goods & FMCG", weightPct: 8.5, benchmarkWeightPct: 8.6, diffPct: -0.1 },
      { sector: "Capital Goods & Infra", weightPct: 7.6, benchmarkWeightPct: 7.8, diffPct: -0.2 },
      { sector: "Healthcare & Pharma", weightPct: 5.8, benchmarkWeightPct: 5.4, diffPct: +0.4 },
      { sector: "Telecommunication", weightPct: 4.8, benchmarkWeightPct: 4.8, diffPct: 0.0 },
      { sector: "Cash & Equivalents", weightPct: 3.4, benchmarkWeightPct: 0.0, diffPct: +3.4 },
      { sector: "Others", weightPct: 1.6, benchmarkWeightPct: 9.5, diffPct: -7.9 },
    ],
    managerBehaviour: {
      managerName: "Gaurav Misra",
      managerTenureYears: 7.1,
      turnoverRatioPct: 24.5,
      activeSharePct: 52.4,
      philosophy: "Disciplined large-cap investing seeking consistent risk-adjusted alpha through business moat analysis.",
      cashStance: {
        currentCashPct: 3.4,
        cashTrend: "STABLE",
        cashHistory: [
          { month: "Jun 2026", cashPct: 3.9 },
          { month: "Jul 2026", cashPct: 3.6 },
          { month: "Aug 2026", cashPct: 3.3 },
          { month: "Sep 2026", cashPct: 3.4 },
        ],
      },
      convictionBets: [
        {
          symbol: "HDFCBANK",
          name: "HDFC Bank Limited",
          fundWeightPct: 9.6,
          benchmarkWeightPct: 7.4,
          activeWeightPct: 2.2,
          rationale: "Post-merger loan repricing, stable NIM expansion, and attractive PEG ratio.",
        },
        {
          symbol: "INFOSYS",
          name: "Infosys Limited",
          fundWeightPct: 6.8,
          benchmarkWeightPct: 5.1,
          activeWeightPct: 1.7,
          rationale: "Mega-deal ramp ups in North America and generative AI advisory billing acceleration.",
        },
      ],
    },
    holdings: [
      {
        symbol: "HDFCBANK",
        name: "HDFC Bank Limited",
        isin: "INE040A01034",
        sector: "Financial Services",
        weightPct: 9.6,
        shares: 22000000,
        marketValueCr: 3691.0,
        marketCapCategory: "Large Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 5.5,
        sharesChangeCount: 1145000,
        prevShares: 20855000,
        currentPriceInr: 1676.0,
      },
      {
        symbol: "ICICIBANK",
        name: "ICICI Bank Limited",
        isin: "INE090A01021",
        sector: "Financial Services",
        weightPct: 8.7,
        shares: 27350000,
        marketValueCr: 3345.0,
        marketCapCategory: "Large Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 4.2,
        sharesChangeCount: 1100000,
        prevShares: 26250000,
        currentPriceInr: 1223.0,
      },
      {
        symbol: "RELIANCE",
        name: "Reliance Industries Limited",
        isin: "INE002A01018",
        sector: "Energy & Utilities",
        weightPct: 7.4,
        shares: 9600000,
        marketValueCr: 2845.0,
        marketCapCategory: "Large Cap",
        changeStatus: "UNCHANGED",
        sharesChangePct: 0.0,
        currentPriceInr: 2962.0,
      },
      {
        symbol: "INFOSYS",
        name: "Infosys Limited",
        isin: "INE009A01021",
        sector: "Information Technology",
        weightPct: 6.8,
        shares: 17200000,
        marketValueCr: 2614.5,
        marketCapCategory: "Large Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 4.8,
        sharesChangeCount: 785000,
        prevShares: 16415000,
        currentPriceInr: 1520.0,
      },
      {
        symbol: "TCS",
        name: "Tata Consultancy Services Ltd",
        isin: "INE467B01029",
        sector: "Information Technology",
        weightPct: 4.7,
        shares: 4620000,
        marketValueCr: 1807.0,
        marketCapCategory: "Large Cap",
        changeStatus: "UNCHANGED",
        sharesChangePct: 0.0,
        currentPriceInr: 3912.0,
      },
      {
        symbol: "BHARTIARTL",
        name: "Bharti Airtel Limited",
        isin: "INE397D01024",
        sector: "Telecommunication",
        weightPct: 4.8,
        shares: 11250000,
        marketValueCr: 1845.5,
        marketCapCategory: "Large Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 6.2,
        sharesChangeCount: 655000,
        prevShares: 10595000,
        currentPriceInr: 1637.0,
      },
      {
        symbol: "LT",
        name: "Larsen & Toubro Limited",
        isin: "INE018A01030",
        sector: "Capital Goods & Infra",
        weightPct: 4.4,
        shares: 4680000,
        marketValueCr: 1691.0,
        marketCapCategory: "Large Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 7.5,
        sharesChangeCount: 326000,
        prevShares: 4354000,
        currentPriceInr: 3613.0,
      },
      {
        symbol: "AXISBANK",
        name: "Axis Bank Limited",
        isin: "INE238A01034",
        sector: "Financial Services",
        weightPct: 3.9,
        shares: 12280000,
        marketValueCr: 1500.0,
        marketCapCategory: "Large Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 3.8,
        sharesChangeCount: 450000,
        prevShares: 11830000,
        currentPriceInr: 1221.5,
      },
      {
        symbol: "MARUTI",
        name: "Maruti Suzuki India Limited",
        isin: "INE585B01010",
        sector: "Automobile & Ancillaries",
        weightPct: 3.4,
        shares: 1048000,
        marketValueCr: 1307.5,
        marketCapCategory: "Large Cap",
        changeStatus: "UNCHANGED",
        sharesChangePct: 0.0,
        currentPriceInr: 12475.0,
      },
      {
        symbol: "TITAN",
        name: "Titan Company Limited",
        isin: "INE280A01028",
        sector: "Consumer Goods & FMCG",
        weightPct: 3.25,
        shares: 3680000,
        marketValueCr: 1248.0,
        marketCapCategory: "Large Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 5.2,
        sharesChangeCount: 182000,
        prevShares: 3498000,
        currentPriceInr: 3392.0,
      },
    ],
    changesMoM: {
      month: "September 2026",
      newEntries: [
        {
          symbol: "TRENT",
          name: "Trent Limited",
          isin: "INE849A01020",
          sector: "Consumer Retail",
          weightPct: 1.65,
          shares: 920000,
          marketValueCr: 634.0,
          marketCapCategory: "Large Cap",
          changeStatus: "NEW",
          sharesChangePct: 100.0,
          sharesChangeCount: 920000,
          currentPriceInr: 6890.0,
        },
      ],
      completeExits: [
        {
          symbol: "WIPRO",
          name: "Wipro Limited",
          isin: "INE075A01022",
          sector: "Information Technology",
          weightPct: 0.0,
          shares: 0,
          marketValueCr: 0,
          marketCapCategory: "Large Cap",
          changeStatus: "EXIT",
          sharesChangePct: -100.0,
          prevShares: 9400000,
          currentPriceInr: 531.0,
        },
      ],
      accumulated: [
        {
          symbol: "LT",
          name: "Larsen & Toubro Limited",
          isin: "INE018A01030",
          sector: "Capital Goods & Infra",
          weightPct: 4.4,
          shares: 4680000,
          marketValueCr: 1691.0,
          marketCapCategory: "Large Cap",
          changeStatus: "ACCUMULATED",
          sharesChangePct: 7.5,
          sharesChangeCount: 326000,
        },
        {
          symbol: "BHARTIARTL",
          name: "Bharti Airtel Limited",
          isin: "INE397D01024",
          sector: "Telecommunication",
          weightPct: 4.8,
          shares: 11250000,
          marketValueCr: 1845.5,
          marketCapCategory: "Large Cap",
          changeStatus: "ACCUMULATED",
          sharesChangePct: 6.2,
          sharesChangeCount: 655000,
        },
      ],
      trimmed: [],
    },
  },
  {
    id: "motilal-oswal-midcap",
    amfiCode: "127042",
    name: "Motilal Oswal Midcap Fund - Direct Plan - Growth",
    shortName: "Motilal Midcap",
    amc: "Motilal Oswal Mutual Fund",
    category: "Mid Cap",
    benchmark: "NIFTY Midcap 150 TRI",
    aumCr: 19840.0,
    nav: 114.7,
    navDate: "2026-09-29",
    expenseRatioPct: 0.65,
    riskRating: "Very High",
    inceptionDate: "2014-02-24",
    disclosureDate: "2026-09-10",
    disclosureUrl: "https://www.motilaloswalmf.com/downloads/mutual-fund/Factsheet",
    concentration: {
      top5WeightPct: 38.5,
      top10WeightPct: 64.2,
      totalHoldingsCount: 29,
      hhi: 580,
      effectiveNumStocks: 17.2,
      marketCapBreakdown: {
        largeCapPct: 22.5,
        midCapPct: 68.2,
        smallCapPct: 5.8,
        cashPct: 3.5,
      },
    },
    factorExposure: [
      {
        factor: "Growth",
        score: 1.92,
        label: "High QGLP Growth",
        percentile: 98,
        description: "Quality, Growth, Longevity, Price framework targeting >20% EPS growth.",
      },
      {
        factor: "Momentum",
        score: 1.65,
        label: "High Relative Strength",
        percentile: 94,
        description: "Focus on sector leaders with strong secular business momentum.",
      },
      {
        factor: "Quality",
        score: 1.45,
        label: "High ROE / Clean Governance",
        percentile: 88,
        description: "Zero tolerance for low-margin commoditized operations.",
      },
      {
        factor: "Size Tilt",
        score: -0.85,
        label: "Mid-Cap Concentration",
        percentile: 86,
        description: "Concentrated 25-30 stock portfolio in mid-cap compounders.",
      },
      {
        factor: "Value",
        score: -0.65,
        label: "Growth Over Deep Value",
        percentile: 24,
        description: "Willing to pay premium valuation for exponential market-share creators.",
      },
      {
        factor: "Low Volatility",
        score: -0.55,
        label: "Concentrated High Beta",
        percentile: 35,
        description: "High stock weights (>7% in top picks) amplify single-stock moves.",
      },
    ],
    sectorExposure: [
      { sector: "Information Technology", weightPct: 24.5, benchmarkWeightPct: 8.6, diffPct: +15.9 },
      { sector: "Consumer Discretionary & Retail", weightPct: 22.8, benchmarkWeightPct: 8.4, diffPct: +14.4 },
      { sector: "Capital Goods & Manufacturing", weightPct: 18.5, benchmarkWeightPct: 18.2, diffPct: +0.3 },
      { sector: "Financial Services", weightPct: 14.2, benchmarkWeightPct: 17.4, diffPct: -3.2 },
      { sector: "Healthcare & Pharma", weightPct: 9.8, benchmarkWeightPct: 10.8, diffPct: -1.0 },
      { sector: "Automobile & Ancillaries", weightPct: 6.7, benchmarkWeightPct: 10.5, diffPct: -3.8 },
      { sector: "Cash & Equivalents", weightPct: 3.5, benchmarkWeightPct: 0.0, diffPct: +3.5 },
    ],
    managerBehaviour: {
      managerName: "Niket Shah",
      managerTenureYears: 6.2,
      turnoverRatioPct: 45.0,
      activeSharePct: 89.2,
      philosophy: "High-conviction, low-diversification mid-cap portfolio chasing rapid EPS compounding.",
      cashStance: {
        currentCashPct: 3.5,
        cashTrend: "STABLE",
        cashHistory: [
          { month: "Jun 2026", cashPct: 4.2 },
          { month: "Jul 2026", cashPct: 3.8 },
          { month: "Aug 2026", cashPct: 3.4 },
          { month: "Sep 2026", cashPct: 3.5 },
        ],
      },
      convictionBets: [
        {
          symbol: "DIXON",
          name: "Dixon Technologies (India) Ltd",
          fundWeightPct: 9.2,
          benchmarkWeightPct: 1.25,
          activeWeightPct: 7.95,
          rationale: "Global supply chain de-risking, mobile and display manufacturing PLI dominance.",
        },
        {
          symbol: "TRENT",
          name: "Trent Limited",
          fundWeightPct: 8.8,
          benchmarkWeightPct: 2.1,
          activeWeightPct: 6.7,
          rationale: "Zudio store expansion flywheel, unmatched retail same-store-sales growth.",
        },
        {
          symbol: "COFORGE",
          name: "Coforge Limited",
          fundWeightPct: 7.4,
          benchmarkWeightPct: 1.6,
          activeWeightPct: 5.8,
          rationale: "Order book momentum, AI deal conversions, and strong client retention.",
        },
        {
          symbol: "POLYCAB",
          name: "Polycab India Limited",
          fundWeightPct: 6.8,
          benchmarkWeightPct: 1.4,
          activeWeightPct: 5.4,
          rationale: "India electrification, cables & wires volume share gains, and FMEG margin recovery.",
        },
      ],
    },
    holdings: [
      {
        symbol: "DIXON",
        name: "Dixon Technologies (India) Ltd",
        isin: "INE935N01020",
        sector: "Consumer Discretionary",
        weightPct: 9.2,
        shares: 1500000,
        marketValueCr: 1829.0,
        marketCapCategory: "Mid Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 14.5,
        sharesChangeCount: 190000,
        prevShares: 1310000,
        currentPriceInr: 12195.0,
      },
      {
        symbol: "TRENT",
        name: "Trent Limited",
        isin: "INE849A01020",
        sector: "Consumer Discretionary & Retail",
        weightPct: 8.8,
        shares: 2530000,
        marketValueCr: 1743.0,
        marketCapCategory: "Large Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 11.2,
        sharesChangeCount: 255000,
        prevShares: 2275000,
        currentPriceInr: 6890.0,
      },
      {
        symbol: "COFORGE",
        name: "Coforge Limited",
        isin: "INE591G01017",
        sector: "Information Technology",
        weightPct: 7.4,
        shares: 2045000,
        marketValueCr: 1468.0,
        marketCapCategory: "Mid Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 8.8,
        sharesChangeCount: 165000,
        prevShares: 1880000,
        currentPriceInr: 7180.0,
      },
      {
        symbol: "POLYCAB",
        name: "Polycab India Limited",
        isin: "INE455K01017",
        sector: "Capital Goods & Manufacturing",
        weightPct: 6.8,
        shares: 2010000,
        marketValueCr: 1348.5,
        marketCapCategory: "Large Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 6.5,
        sharesChangeCount: 122000,
        prevShares: 1888000,
        currentPriceInr: 6710.0,
      },
      {
        symbol: "PERSISTENT",
        name: "Persistent Systems Limited",
        isin: "INE262H01013",
        sector: "Information Technology",
        weightPct: 6.3,
        shares: 2420000,
        marketValueCr: 1249.5,
        marketCapCategory: "Mid Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 5.4,
        sharesChangeCount: 124000,
        prevShares: 2296000,
        currentPriceInr: 5163.0,
      },
      {
        symbol: "KALYANKJIL",
        name: "Kalyan Jewellers India Ltd",
        isin: "INE303R01014",
        sector: "Consumer Discretionary & Retail",
        weightPct: 5.2,
        shares: 18500000,
        marketValueCr: 1032.0,
        marketCapCategory: "Mid Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 16.5,
        sharesChangeCount: 2620000,
        prevShares: 15880000,
        currentPriceInr: 558.0,
      },
      {
        symbol: "SUZLON",
        name: "Suzlon Energy Limited",
        isin: "INE040H01021",
        sector: "Capital Goods & Manufacturing",
        weightPct: 4.6,
        shares: 122000000,
        marketValueCr: 912.5,
        marketCapCategory: "Mid Cap",
        changeStatus: "NEW",
        sharesChangePct: 100.0,
        sharesChangeCount: 122000000,
        prevShares: 0,
        currentPriceInr: 74.8,
      },
      {
        symbol: "BEL",
        name: "Bharat Electronics Limited",
        isin: "INE263A01024",
        sector: "Capital Goods & Manufacturing",
        weightPct: 4.1,
        shares: 27700000,
        marketValueCr: 814.0,
        marketCapCategory: "Large Cap",
        changeStatus: "ACCUMULATED",
        sharesChangePct: 12.0,
        sharesChangeCount: 2970000,
        prevShares: 24730000,
        currentPriceInr: 294.0,
      },
    ],
    changesMoM: {
      month: "September 2026",
      newEntries: [
        {
          symbol: "SUZLON",
          name: "Suzlon Energy Limited",
          isin: "INE040H01021",
          sector: "Capital Goods & Manufacturing",
          weightPct: 4.6,
          shares: 122000000,
          marketValueCr: 912.5,
          marketCapCategory: "Mid Cap",
          changeStatus: "NEW",
          sharesChangePct: 100.0,
          sharesChangeCount: 122000000,
          currentPriceInr: 74.8,
        },
      ],
      completeExits: [
        {
          symbol: "TATAELXSI",
          name: "Tata Elxsi Limited",
          isin: "INE670A01012",
          sector: "Information Technology",
          weightPct: 0.0,
          shares: 0,
          marketValueCr: 0,
          marketCapCategory: "Mid Cap",
          changeStatus: "EXIT",
          sharesChangePct: -100.0,
          prevShares: 1100000,
          currentPriceInr: 7150.0,
        },
      ],
      accumulated: [
        {
          symbol: "KALYANKJIL",
          name: "Kalyan Jewellers India Ltd",
          isin: "INE303R01014",
          sector: "Consumer Discretionary & Retail",
          weightPct: 5.2,
          shares: 18500000,
          marketValueCr: 1032.0,
          marketCapCategory: "Mid Cap",
          changeStatus: "ACCUMULATED",
          sharesChangePct: 16.5,
          sharesChangeCount: 2620000,
        },
        {
          symbol: "DIXON",
          name: "Dixon Technologies (India) Ltd",
          isin: "INE935N01020",
          sector: "Consumer Discretionary",
          weightPct: 9.2,
          shares: 1500000,
          marketValueCr: 1829.0,
          marketCapCategory: "Mid Cap",
          changeStatus: "ACCUMULATED",
          sharesChangePct: 14.5,
          sharesChangeCount: 190000,
        },
        {
          symbol: "BEL",
          name: "Bharat Electronics Limited",
          isin: "INE263A01024",
          sector: "Capital Goods & Manufacturing",
          weightPct: 4.1,
          shares: 27700000,
          marketValueCr: 814.0,
          marketCapCategory: "Large Cap",
          changeStatus: "ACCUMULATED",
          sharesChangePct: 12.0,
          sharesChangeCount: 2970000,
        },
      ],
      trimmed: [],
    },
  },
];

export function getAllMutualFunds(): MutualFund[] {
  return MUTUAL_FUNDS_STORE;
}

export function getMutualFundById(id: string): MutualFund | undefined {
  return MUTUAL_FUNDS_STORE.find(
    (f) => f.id.toLowerCase() === id.toLowerCase() || f.amfiCode === id
  );
}

export function searchMutualFunds(query: string): MutualFund[] {
  if (!query || query.trim() === "") return MUTUAL_FUNDS_STORE;
  const q = query.toLowerCase().trim();
  return MUTUAL_FUNDS_STORE.filter(
    (f) =>
      f.name.toLowerCase().includes(q) ||
      f.shortName.toLowerCase().includes(q) ||
      f.amc.toLowerCase().includes(q) ||
      f.category.toLowerCase().includes(q) ||
      f.holdings.some(
        (h) =>
          h.symbol.toLowerCase().includes(q) || h.name.toLowerCase().includes(q)
      )
  );
}

export function getFundsByCategory(category: string): MutualFund[] {
  if (!category || category === "All") return MUTUAL_FUNDS_STORE;
  return MUTUAL_FUNDS_STORE.filter((f) => f.category === category);
}
