import {
  CompanyIntelligenceProfile,
  IrDocument,
  CompanyTimelineEvent,
  WhatChangedSummary,
  ConcallQuarterReport,
  HistoricalToneQuarter,
} from "./types";

/**
 * Curated flagship intelligence profiles for bellwether companies.
 */
export const COMPANY_INTELLIGENCE_REGISTRY: Record<string, CompanyIntelligenceProfile> = {
  TATAMOTORS: {
    symbol: "TATAMOTORS",
    companyName: "Tata Motors Limited",
    sector: "Automotive & Electric Mobility",
    marketCapTier: "LARGE_CAP",
    irBaseUrl: "https://www.tatamotors.com/investors/",
    irDocuments: [
      {
        id: "tm-ir-pres-q1fy26",
        category: "INVESTOR_PRESENTATION",
        title: "Q1 FY26 Investor & Analyst Presentation",
        periodOrDate: "22 Sep 2026",
        fileType: "PDF",
        fileSizeMb: 8.4,
        url: "https://www.tatamotors.com/wp-content/uploads/2026/09/investor-deck-q1fy26.pdf",
        summary: "Detailed review of JLR EBIT margins (8.9%), India PV market share at 13.8%, and commercial vehicle fleet replacement trends.",
        highlights: [
          "JLR net cash milestone achieved: £1.4B ahead of FY26 target",
          "EV penetration in domestic passenger vehicles at 12.4%",
          "Commercial Vehicles EBITDA margin expanded 120 bps YoY to 11.6%",
        ],
      },
      {
        id: "tm-ir-earn-q1fy26",
        category: "EARNINGS_RELEASE",
        title: "Consolidated Financial Results for Quarter Ended June 30, 2026",
        periodOrDate: "Q1 FY26",
        fileType: "PDF",
        fileSizeMb: 3.2,
        url: "https://www.tatamotors.com/wp-content/uploads/2026/09/earnings-release-q1fy26.pdf",
        summary: "Consolidated revenue up 5.7% YoY to ₹1,08,048 Cr. Net profit after tax stood at ₹5,568 Cr.",
        highlights: [
          "JLR wholesale volumes up 4.8% YoY driven by Range Rover and Defender demand",
          "Net automotive debt reduced to zero; consolidated debt down by ₹9,400 Cr YoY",
        ],
      },
      {
        id: "tm-ir-ar-2025",
        category: "ANNUAL_REPORT",
        title: "79th Integrated Annual Report 2024-25: Orchestrating the Transition",
        periodOrDate: "FY 2024-25",
        fileType: "PDF",
        fileSizeMb: 18.6,
        url: "https://www.tatamotors.com/wp-content/uploads/2025/07/annual-report-2024-25.pdf",
        summary: "Statutory report detailing the proposed corporate demerger into Commercial Vehicles (CV) and Passenger Vehicles (PV + EV + JLR) listed entities.",
        highlights: [
          "Demerger timeline on track for completion within NCLT regulatory statutory window",
          "R&D spend crossed ₹24,000 Cr (~6.2% of consolidated turnover)",
        ],
      },
      {
        id: "tm-ir-esg-2025",
        category: "ESG_REPORT",
        title: "BRSR Core & ESG Sustainability Compendium 2025",
        periodOrDate: "FY 2024-25",
        fileType: "PDF",
        fileSizeMb: 11.2,
        url: "https://www.tatamotors.com/wp-content/uploads/2025/08/esg-sustainability-2025.pdf",
        summary: "Zero-tailpipe emission roadmap for JLR by 2039 and carbon net-zero operations across Indian manufacturing facilities by 2045.",
        highlights: [
          "48% renewable electricity consumption across Pune and Sanand plants",
          "Water positivity certification secured for Lucknow and Pantnagar plants",
        ],
      },
      {
        id: "tm-ir-pr-acq",
        category: "PRESS_RELEASE",
        title: "Tata Motors acquires 100% equity stake in Iveco India CV Component Hub",
        periodOrDate: "08 Sep 2026",
        fileType: "PDF",
        fileSizeMb: 1.1,
        url: "https://www.tatamotors.com/press-releases/iveco-hub-acquisition.pdf",
        summary: "Strategic backward integration in heavy commercial vehicle chassis frames and hydrogen combustion testing facilities.",
        highlights: [
          "Transaction valuation at ₹420 Cr all-cash buyout funded via internal accruals",
          "Expected to reduce heavy CV procurement lead times by 18 days",
        ],
      },
      {
        id: "tm-ir-mgmt-comm",
        category: "MANAGEMENT_COMMENTARY",
        title: "Group Chairman & MD Strategic Address: Capital Allocation & Demerger Milestones",
        periodOrDate: "12 Sep 2026",
        fileType: "WEB",
        url: "https://www.tatamotors.com/investors/management-commentary/sept-2026.html",
        summary: "Clarification on independent balance sheets post-demerger and European EV tariff buffering mechanisms.",
        highlights: [
          "Zero dividend dilution anticipated across both demerged standalone entities",
          "JLR battery cell supply secured via Agratas UK gigafactory joint venture",
        ],
      },
      {
        id: "tm-ir-event-agm",
        category: "EVENTS",
        title: "Annual General Meeting & Global Investor Day Webcast",
        periodOrDate: "28 Aug 2026",
        fileType: "WEB",
        url: "https://www.tatamotors.com/investors/agm-webcast-2026.html",
        summary: "Shareholder voting approved demerger scheme with 99.8% majority. Management outlined 3-year product launch roadmap.",
        highlights: [
          "Curvv EV, Harrier EV, and Sierra EV confirmed for market commercial launch",
          "JLR MLA-Flex platform architecture scalable to all-electric Range Rover",
        ],
      },
      {
        id: "tm-ir-concall-q1",
        category: "CONCALL_MATERIALS",
        title: "Q1 FY26 Earnings Conference Call Audio & Verbatim Transcript",
        periodOrDate: "Q1 FY26",
        fileType: "TRANSCRIPT",
        fileSizeMb: 2.1,
        url: "https://www.tatamotors.com/wp-content/uploads/2026/09/concall-transcript-q1fy26.pdf",
        summary: "Full 72-minute analyst Q&A featuring PB Balaji (Group CFO) and Adrian Mardell (JLR CEO).",
        highlights: [
          "Detailed response on European EV demand deceleration vs Range Rover hybrid mix",
          "Domestic CV freight operator cash flows and pricing discipline",
        ],
      },
    ],
    timeline: [
      {
        id: "tm-tl-1",
        symbol: "TATAMOTORS",
        date: "2026-09-29",
        displayDate: "29 Sep",
        type: "REGULATORY_FILING",
        impact: "HIGH_IMPACT",
        headline: "NCLT Final Hearing Convened for Corporate Demerger Scheme",
        summary: "Disclosed statutory notice for final creditor and regulatory sanction hearing scheduled for demerger into separate CV and PV listed companies.",
        keyMetrics: [
          { label: "Demerger Ratio", value: "1:1 Mirror Shareholding", sentiment: "POSITIVE" },
          { label: "Target Effective Date", value: "Q3 FY27", sentiment: "NEUTRAL" },
        ],
        sourceDocLabel: "NSE Filing #TATAMOTORS-20260929-8812",
        sourceUrl: "https://www.nseindia.com/companies-listing/corporate-filings-announcements",
      },
      {
        id: "tm-tl-2",
        symbol: "TATAMOTORS",
        date: "2026-09-22",
        displayDate: "22 Sep",
        type: "INVESTOR_PRESENTATION",
        impact: "STRATEGIC",
        headline: "Q1 FY26 Comprehensive Investor Presentation Released",
        summary: "Uploaded detailed operational slide deck covering JLR order book of 148,000 units and domestic EV battery cost parity trends.",
        keyMetrics: [
          { label: "JLR Order Bank", value: "148,000 Units", sentiment: "POSITIVE" },
          { label: "Domestic PV Market Share", value: "13.8%", sentiment: "NEUTRAL" },
        ],
        sourceDocLabel: "BSE Corporate Announcement #500570-PRES-2209",
        sourceUrl: "https://www.bseindia.com/corporates/ann.html",
      },
      {
        id: "tm-tl-3",
        symbol: "TATAMOTORS",
        date: "2026-09-18",
        displayDate: "18 Sep",
        type: "CREDIT_RATING",
        impact: "HIGH_IMPACT",
        headline: "CRISIL Upgrades Long-Term Debt to 'CRISIL AAA / Stable'",
        summary: "CRISIL upgraded bank loan facilities and NCDs to highest credit safety rating citing sustained JLR deleveraging and zero net automotive debt.",
        keyMetrics: [
          { label: "Rating Action", value: "CRISIL AA+ to AAA", sentiment: "POSITIVE" },
          { label: "Automotive Net Debt", value: "Zero (Net Cash £1.4B)", sentiment: "POSITIVE" },
        ],
        sourceDocLabel: "CRISIL Rating Rationale #20260918-TM-AAA",
        sourceUrl: "https://www.crisilratings.com",
      },
      {
        id: "tm-tl-4",
        symbol: "TATAMOTORS",
        date: "2026-09-12",
        displayDate: "12 Sep",
        type: "MANAGEMENT_COMMENTARY",
        impact: "STRATEGIC",
        headline: "Management Commentary on Festive Season Dealer Inventory & EV Tax Slabs",
        summary: "Group CFO reiterated disciplined dealer inventory levels at 32 days ahead of Diwali, dismissing concerns over predatory discounting.",
        keyMetrics: [
          { label: "Dealer Stock Level", value: "32 Days (Industry: 48 Days)", sentiment: "POSITIVE" },
          { label: "PV Discounting Stance", value: "Maintained <3.2% of ASP", sentiment: "POSITIVE" },
        ],
        sourceDocLabel: "Exchange Clarification & Press Brief",
      },
      {
        id: "tm-tl-5",
        symbol: "TATAMOTORS",
        date: "2026-09-08",
        displayDate: "08 Sep",
        type: "ACQUISITION_MNA",
        impact: "STRATEGIC",
        headline: "Acquisition Announcement: Iveco India CV Component Hub for ₹420 Cr",
        summary: "Concluded definitive share purchase agreement to acquire dedicated commercial chassis engineering unit to support heavy electric trucks.",
        keyMetrics: [
          { label: "Deal Outlay", value: "₹420 Cr (100% Cash)", sentiment: "NEUTRAL" },
          { label: "Procurement Savings", value: "₹85 Cr / year", sentiment: "POSITIVE" },
        ],
        sourceDocLabel: "SEBI Reg 30 Disclosure #SPA-IVECO-0809",
      },
      {
        id: "tm-tl-6",
        symbol: "TATAMOTORS",
        date: "2026-09-02",
        displayDate: "02 Sep",
        type: "PRODUCTION_UPDATE",
        impact: "ROUTINE",
        headline: "Monthly Production & Wholesale Volume Update (August 2026)",
        summary: "Reported total domestic sales of 78,843 units. Commercial vehicles grew 3.2% MoM while passenger electric vehicles jumped 18.4% YoY.",
        keyMetrics: [
          { label: "Total Wholesales", value: "78,843 Units", sentiment: "POSITIVE" },
          { label: "EV Volume", value: "7,284 Units (+18.4% YoY)", sentiment: "POSITIVE" },
        ],
        sourceDocLabel: "Monthly Exchange Production Flash",
      },
    ],
    whatChanged: {
      period: "Q1 FY26 vs Q4 FY25",
      executiveSynthesis:
        "The overarching thesis for Tata Motors has pivoted from 'balance sheet survival and debt liquidation' to 'operating margin defense amid global EV slowdown'. JLR continues to deliver record cash flow powered by high-margin Range Rover models, but management has become notably cautious on domestic entry-level passenger vehicles where dealer discounts have surged across India.",
      netDirection: "POSITIVE_INFLECTION",
      dimensions: [
        {
          dimension: "Balance Sheet & Automotive Debt",
          priorQuarter: "Automotive net debt of £700M; targeting zero net debt by end of FY25.",
          currentQuarter: "Automotive net cash reached £1.4B; CRISIL upgraded rating to pristine AAA.",
          verdict: "UPGRADE",
          changeNarrative: "Achieved full debt-free status faster than institutional analyst consensus.",
          confidenceScore: 96,
        },
        {
          dimension: "JLR Margin & Product Mix",
          priorQuarter: "EBIT guidance of >8.0% for FY25; supply chain constraints on Defender.",
          currentQuarter: "Reported 8.9% EBIT; reaffirmed >8.5% for FY26 despite global auto deceleration.",
          verdict: "UPGRADE",
          changeNarrative: "Range Rover, Range Rover Sport, and Defender now constitute 68% of the order book.",
          confidenceScore: 91,
        },
        {
          dimension: "Domestic PV Market & Discounting",
          priorQuarter: "Robust order intake; waiting periods on Punch EV and Nexon EV of 4-6 weeks.",
          currentQuarter: "Acknowledged domestic industry inventory build-up; retail sales growing slower than production.",
          verdict: "DOWNGRADE",
          changeNarrative: "Management dialed back aggressive volume guidance to prioritize dealer margins and protect resale value.",
          confidenceScore: 84,
        },
        {
          dimension: "Commercial Vehicle Fleet Demand",
          priorQuarter: "Pre-election lull slowed heavy truck purchases; fleet utilization at 71%.",
          currentQuarter: "Fleet utilization recovered to 76%; replacement cycle driving multi-axle truck demand.",
          verdict: "UPGRADE",
          changeNarrative: "Infra capex revival post-budget is unlocking delayed government fleet tenders.",
          confidenceScore: 88,
        },
        {
          dimension: "Capital Expenditure (Capex)",
          priorQuarter: "FY25 Capex budgeted at £3.0B for JLR and ₹8,000 Cr for Tata Motors India.",
          currentQuarter: "Reaffirmed £3.5B for JLR with accelerated modular EV architecture spend.",
          verdict: "MAINTAINED",
          changeNarrative: "No capex cut; funded entirely via internal operational cash flows.",
          confidenceScore: 92,
        },
      ],
      catalystsToWatch: [
        "Final NCLT sanction order for CV / PV demerger listing (expected Q3 FY27)",
        "Commercial rollout and customer deliveries of the all-electric Range Rover",
        "Festive retail conversion rates for the new Curvv coupe SUV",
      ],
      keyRiskAlerts: [
        "Rising European & US tariffs on EV supply chains and retaliatory battery material levies",
        "Intense pricing warfare initiated by Mahindra and Hyundai in compact domestic SUVs",
      ],
    },
    latestConcall: {
      id: "tm-cc-q1fy26",
      quarter: "Q1 FY26",
      date: "2026-08-14",
      audioDurationMin: 72,
      participants: [
        { name: "P.B. Balaji", designation: "Group Chief Financial Officer" },
        { name: "Adrian Mardell", designation: "Chief Executive Officer, JLR" },
        { name: "Shailesh Chandra", designation: "Managing Director, TMPV & TPEM" },
        { name: "Girish Wagh", designation: "Executive Director, Tata Motors CV" },
      ],
      headlineVerdict: "Management maintains confident posture on JLR cash generation while candidly acknowledging domestic PV industry retail headwinds.",
      dimensions: {
        managementConfidence: {
          score: 74,
          stance: "OPTIMISTIC",
          rationale: "Management was assertive on cash generation and balance sheet strength, but measured on entry-level auto retail growth.",
        },
        revenueOutlook: {
          targetGrowthPct: "+7% to +9% Consolidated YoY",
          commentary: "JLR wholesale revenue expected to remain steady, underpinned by higher ASP mix offsetting slightly softer unit deliveries.",
          stance: "POSITIVE",
        },
        marginOutlook: {
          targetMarginPct: "8.5% - 9.0% JLR EBIT; 11.5% India CV EBITDA",
          headwinds: [
            "Domestic PV discount pressures (+40 bps impact)",
            "Marketing spend for new model launches in UK/Europe",
          ],
          tailwinds: [
            "Commodity deflation in steel and precious metals",
            "Operating leverage in heavy commercial vehicles",
          ],
          stance: "EXPANDING",
        },
        capex: {
          outlayInrCr: 43000,
          allocationFocus: "£3.5B at JLR (Electrification & MLA platform); ₹8,500 Cr in India PV/CV platforms.",
          debtImpact: "Zero debt addition. Fully funded through internal cash flows.",
        },
        demand: {
          environment: "STEADY",
          details: "Strong appetite for luxury SUVs and commercial prime movers; softness observed in sub-₹10 Lakh domestic passenger cars.",
        },
        pricing: {
          pricingPower: "HIGH",
          discountsCommentary: "Preserved pricing power in JLR with average selling price exceeding £72,000. Refused to participate in irrational price discounting in India.",
        },
        competition: {
          intensity: "ELEVATED",
          marketShareShift: "PV market share held steady at 13.8%; defended #1 electric car market share at 68% despite new entrants.",
        },
        commodityCosts: {
          trend: "BENIGN",
          impactedSegments: ["Steel", "Aluminum", "Rare-earth EV magnets"],
        },
        hiring: {
          headcountTrend: "STABLE",
          wageInflationPct: "6.2% across Indian plants; 4.8% at JLR UK",
        },
        expansion: {
          status: "Sanand Plant Phase 2 tooling operational; Agratas UK battery site construction underway.",
          targetMilestoneDate: "Q4 FY27 commercial cell production",
        },
        guidanceChanges: {
          status: "MAINTAINED",
          details: "Reaffirmed FY26 EBIT target of >8.5% and net cash preservation for JLR.",
        },
      },
      analystQA: [
        {
          id: "tm-qa-1",
          analystName: "Binay Singh",
          firm: "Morgan Stanley",
          question: "Given that industry PV inventory in India is reaching 50-60 days, why are you confident Tata Motors won't need to increase retail dealer discounts during the upcoming festive quarter?",
          managementSpeaker: "Shailesh Chandra (MD, TMPV)",
          answerSummary: "Tata Motors intentionally throttled dispatches in June and July to cap network inventory at 32 days, significantly below the industry average.",
          verbatimExcerpt: "We took a conscious call not to push wholesale billing into dealerships when retail was lagging. Our stock is at 32 days, while competitors are sitting on 50 to 55 days. Therefore, our need to offer distress discounts is virtually nonexistent.",
          tone: "CONFIDENT",
          materiality: "HIGH",
        },
        {
          id: "tm-qa-2",
          analystName: "Gunjan Prithyani",
          firm: "BofA Securities",
          question: "On JLR, order backlog has reduced from 168k to 148k. Is this a natural clearing of waiting periods, or are you witnessing genuine cancellation rates due to high interest rates in Europe?",
          managementSpeaker: "Adrian Mardell (CEO, JLR)",
          answerSummary: "Order cancellations remain at historic lows (<2.5%); the order bank reduction is purely a function of production normalization at Solihull and Nitra.",
          verbatimExcerpt: "The intake of new orders weekly is pacing at approximately 3,000 units, exactly in line with our production exit rate. Defender and Range Rover have 5 to 7 months of order visibility.",
          tone: "CONFIDENT",
          materiality: "HIGH",
        },
        {
          id: "tm-qa-3",
          analystName: "Kapil Singh",
          firm: "Nomura",
          question: "With the corporate demerger scheduled for next year, how will shared R&D costs for electric platforms and software architectures be allocated between the CV and PV entities?",
          managementSpeaker: "P.B. Balaji (Group CFO)",
          answerSummary: "All platform IPs will be housed in the PV entity, while CV will license software through standard arm's-length royalty covenants.",
          verbatimExcerpt: "We have structured clean, segregated balance sheets. There will be zero shared liabilities, and cross-entity royalty arrangements have been vetted to avoid any transfer pricing friction.",
          tone: "GUARDED",
          materiality: "MEDIUM",
        },
      ],
    },
    historicalToneTrajectory: [
      {
        quarter: "Q1 FY25",
        date: "2024-07-28",
        score: 62,
        tone: "NEUTRAL",
        keyTheme: "Macro caution on Europe interest rates, supply chain bottlenecks for JLR chips",
        revenueBeatMiss: "IN_LINE",
        marginBeatMiss: "IN_LINE",
      },
      {
        quarter: "Q2 FY25",
        date: "2024-10-30",
        score: 74,
        tone: "OPTIMISTIC",
        keyTheme: "Deleveraging timeline accelerated, strong festive PV deliveries in India",
        revenueBeatMiss: "BEAT",
        marginBeatMiss: "BEAT",
      },
      {
        quarter: "Q3 FY25",
        date: "2025-01-29",
        score: 82,
        tone: "BULLISH",
        keyTheme: "Record quarterly consolidated profit, JLR EBIT exceeds 8.8%, CV margins cross 11%",
        revenueBeatMiss: "BEAT",
        marginBeatMiss: "BEAT",
      },
      {
        quarter: "Q4 FY25",
        date: "2025-05-10",
        score: 79,
        tone: "BULLISH",
        keyTheme: "Full automotive debt elimination achieved, proposed demerger into two entities",
        revenueBeatMiss: "BEAT",
        marginBeatMiss: "IN_LINE",
      },
      {
        quarter: "Q1 FY26",
        date: "2025-08-14",
        score: 74,
        tone: "OPTIMISTIC",
        keyTheme: "Prudent inventory management amid industry PV retail slowdown; JLR cash resilient",
        revenueBeatMiss: "IN_LINE",
        marginBeatMiss: "BEAT",
      },
      {
        quarter: "Q2 FY26",
        date: "2025-11-12",
        score: 76,
        tone: "OPTIMISTIC",
        keyTheme: "Festive retail rebound; Curvv EV early booking success and CV infra recovery",
        revenueBeatMiss: "BEAT",
        marginBeatMiss: "IN_LINE",
      },
    ],
  },

  RELIANCE: {
    symbol: "RELIANCE",
    companyName: "Reliance Industries Limited",
    sector: "Conglomerate (Telecom / Retail / O2C)",
    marketCapTier: "LARGE_CAP",
    irBaseUrl: "https://www.ril.com/investor-relations",
    irDocuments: [
      {
        id: "ril-ir-pres-q1",
        category: "INVESTOR_PRESENTATION",
        title: "Q1 FY26 Strategic Review & Operating Presentation",
        periodOrDate: "20 Sep 2026",
        fileType: "PDF",
        fileSizeMb: 12.8,
        url: "https://www.ril.com/investors/q1fy26-presentation.pdf",
        summary: "Telecom tariff hike transmission review (Jio ARPU ₹196), Reliance Retail store footfall (+16% YoY), and Jamnagar New Energy giga-complex commissioning.",
        highlights: [
          "Jio true 5G user base exceeded 145 million subscribers",
          "Retail EBITDA margin expanded 40 bps to 8.6%",
          "O2C downstream chemical margins stabilized following Middle East cracker outages",
        ],
      },
      {
        id: "ril-ir-earn-q1",
        category: "EARNINGS_RELEASE",
        title: "Consolidated Financial Results for Q1 FY26",
        periodOrDate: "Q1 FY26",
        fileType: "PDF",
        fileSizeMb: 4.1,
        url: "https://www.ril.com/investors/q1fy26-release.pdf",
        summary: "Consolidated quarterly EBITDA rose 8.4% YoY to ₹43,260 Cr. Net profit stood at ₹19,840 Cr.",
        highlights: [
          "Jio Platforms EBITDA up 14.8% YoY on tariff hike benefit",
          "Retail digital commerce and merchant transactions constituted 19% of retail revenues",
        ],
      },
      {
        id: "ril-ir-ar",
        category: "ANNUAL_REPORT",
        title: "Integrated Annual Report 2024-25: Empowering a Resilient India",
        periodOrDate: "FY 2024-25",
        fileType: "PDF",
        fileSizeMb: 24.5,
        url: "https://www.ril.com/investors/annual-report-2025.pdf",
        summary: "Comprehensive details on ₹1,20,000 Cr annualized consumer segment revenues and Dhirubhai Ambani Green Energy Giga Complex.",
        highlights: [
          "Solar PV giga-factory module assembly phase 1 completed",
          "Green hydrogen electrolyzer partnership with Stiesdal commercialized",
        ],
      },
      {
        id: "ril-ir-concall",
        category: "CONCALL_MATERIALS",
        title: "Q1 FY26 Earnings Call Transcript & Management Briefing",
        periodOrDate: "Q1 FY26",
        fileType: "TRANSCRIPT",
        fileSizeMb: 1.9,
        url: "https://www.ril.com/investors/concall-q1fy26.pdf",
        summary: "Conference call addressing telecom ARPU trajectory, retail square footage additions, and O2C export duty impacts.",
        highlights: [
          "Jio management signaled potential follow-on tariff adjustments over 18 months",
          "Consumer retail capex moderating as existing store density matures",
        ],
      },
    ],
    timeline: [
      {
        id: "ril-tl-1",
        symbol: "RELIANCE",
        date: "2026-09-28",
        displayDate: "28 Sep",
        type: "REGULATORY_FILING",
        impact: "HIGH_IMPACT",
        headline: "Jio Infocomm Completes Pan-India 5G Standalone Rollout Milestones",
        summary: "Notified Department of Telecommunications and stock exchanges regarding fulfillment of all Phase-2 5G spectrum rollout obligations.",
        keyMetrics: [
          { label: "5G Base Stations", value: "1,180,000+", sentiment: "POSITIVE" },
          { label: "Capex Taper", value: "-35% YoY in FY26", sentiment: "POSITIVE" },
        ],
        sourceDocLabel: "NSE Filing #RELIANCE-20260928-9102",
      },
      {
        id: "ril-tl-2",
        symbol: "RELIANCE",
        date: "2026-09-20",
        displayDate: "20 Sep",
        type: "INVESTOR_PRESENTATION",
        impact: "STRATEGIC",
        headline: "New Energy Giga Complex Operational Roadmap Presentation",
        summary: "Shared technical presentation detailing the commissioning timeline of the 20 GW integrated solar module and storage battery complex in Jamnagar.",
        keyMetrics: [
          { label: "Solar Capacity", value: "10 GW by Dec 2026", sentiment: "POSITIVE" },
          { label: "IRR Threshold", value: ">14% targeted", sentiment: "NEUTRAL" },
        ],
        sourceDocLabel: "BSE Corporate Presentation",
      },
      {
        id: "ril-tl-3",
        symbol: "RELIANCE",
        date: "2026-09-14",
        displayDate: "14 Sep",
        type: "MANAGEMENT_COMMENTARY",
        impact: "STRATEGIC",
        headline: "Director Commentary on Consumer Segment Value Unlocking & IPOs",
        summary: "Board remarks reiterating commitment to unlock value in Jio Platforms and Reliance Retail through market listings when market conditions align.",
        keyMetrics: [
          { label: "Listing Window", value: "FY26 - FY27 Evaluation", sentiment: "POSITIVE" },
        ],
        sourceDocLabel: "Annual Shareholder Dialogue Excerpt",
      },
      {
        id: "ril-tl-4",
        symbol: "RELIANCE",
        date: "2026-09-05",
        displayDate: "05 Sep",
        type: "PRODUCTION_UPDATE",
        impact: "ROUTINE",
        headline: "KG-D6 Gas Field Production Hits Record 30 MMSCMD",
        summary: "Joint venture with bp achieved peak domestic deepwater natural gas extraction, supplying ~30% of India's indigenous gas demand.",
        keyMetrics: [
          { label: "Daily Gas Output", value: "30 MMSCMD", sentiment: "POSITIVE" },
          { label: "Domestic Market Share", value: "~30% of Indian Gas", sentiment: "POSITIVE" },
        ],
        sourceDocLabel: "Press Announcement & Hydrocarbon Directorate",
      },
    ],
    whatChanged: {
      period: "Q1 FY26 vs Q4 FY25",
      executiveSynthesis:
        "The focal point for Reliance has transitioned from massive 5G infrastructure capex outlays to free cash flow harvesting. Jio's headline tariff hike has flowed through to bottom-line ARPU expansion with minimal subscriber churn. In retail, square footage addition has slowed in favor of store-level profitability and supply chain automation.",
      netDirection: "POSITIVE_INFLECTION",
      dimensions: [
        {
          dimension: "Telecom ARPU & Cash Conversion",
          priorQuarter: "ARPU stagnant at ₹181.7; high promotional free 5G data.",
          currentQuarter: "ARPU jumped to ₹196.4 following 15-20% tariff hikes; subscriber retention at 98.4%.",
          verdict: "UPGRADE",
          changeNarrative: "Market structure demonstrated pricing elasticity without competitive price wars.",
          confidenceScore: 94,
        },
        {
          dimension: "Consolidated Capex Outlay",
          priorQuarter: "Annual run-rate capex exceeded ₹1,30,000 Cr driven by 5G pan-India tower erection.",
          currentQuarter: "Capex declined by 22% sequentially as telecom network construction peaked.",
          verdict: "UPGRADE",
          changeNarrative: "Shift toward free cash flow generation enables balance sheet deleveraging.",
          confidenceScore: 90,
        },
        {
          dimension: "O2C Refining Margins",
          priorQuarter: "Gross refining margins (GRMs) pressured by weak diesel spreads in Asia.",
          currentQuarter: "GRMs stabilized at $9.8/bbl supported by petrochemical feed optimization.",
          verdict: "MAINTAINED",
          changeNarrative: "Russian discounted crude basket continues to buffer Jamnagar complexity advantages.",
          confidenceScore: 82,
        },
      ],
      catalystsToWatch: [
        "Filing of draft red herring prospectus (DRHP) for Jio Platforms listing",
        "Commercial trial of indigenous solar cell manufacturing at Jamnagar",
      ],
      keyRiskAlerts: [
        "Volatile global crude oil benchmark prices compressing O2C margins",
        "Intensifying competition in quick commerce from Blinkit and Zepto threatening JioMart Express",
      ],
    },
    latestConcall: {
      id: "ril-cc-q1fy26",
      quarter: "Q1 FY26",
      date: "2026-07-21",
      audioDurationMin: 65,
      participants: [
        { name: "V. Srikanth", designation: "Chief Financial Officer" },
        { name: "Kiran Thomas", designation: "President, Reliance Jio" },
        { name: "Gaurav Jain", designation: "Head of Strategy, Reliance Retail" },
      ],
      headlineVerdict: "Management highlighted inflection in cash flow conversion as mega 5G capex winds down and tariff hike flow-through boosts Jio EBITDA.",
      dimensions: {
        managementConfidence: {
          score: 82,
          stance: "BULLISH",
          rationale: "Broad-based confidence stemming from tariff hike monetization and moderating group capex.",
        },
        revenueOutlook: {
          targetGrowthPct: "+10% to +12% Consolidated YoY",
          commentary: "Consumer businesses (Retail + Digital Services) now contribute over 52% of consolidated EBITDA.",
          stance: "POSITIVE",
        },
        marginOutlook: {
          targetMarginPct: "Jio EBITDA margin >52%; Retail EBITDA margin ~8.8%",
          headwinds: ["Store fitment inflation in tier-2 cities"],
          tailwinds: ["Zero tariff churn and premium 5G plan migrations", "High-margin private label FMCG expansion"],
          stance: "EXPANDING",
        },
        capex: {
          outlayInrCr: 95000,
          allocationFocus: "New Energy Jamnagar complex (Solar & Batteries); targeted retail distribution centers.",
          debtImpact: "Net debt to EBITDA comfortably below 1.2x.",
        },
        demand: {
          environment: "STRONG",
          details: "Digital broadband data usage up 24% YoY; grocery and apparel retail footfalls up double digits.",
        },
        pricing: {
          pricingPower: "HIGH",
          discountsCommentary: "Successfully passed on headline telecom tariff revision; retail gross margins steady.",
        },
        competition: {
          intensity: "STABLE",
          marketShareShift: "Gained 180 bps revenue market share in telecom; retail store count reached 18,900+.",
        },
        commodityCosts: {
          trend: "BENIGN",
          impactedSegments: ["Crude feedstock", "Polymer resins"],
        },
        hiring: {
          headcountTrend: "EXPANDING",
          wageInflationPct: "5.5% corporate; standard retail frontline compensation",
        },
        expansion: {
          status: "Solar giga-factory commissioning initial 5 GW module line by December 2026.",
          targetMilestoneDate: "Q3 FY27 commercial power generation",
        },
        guidanceChanges: {
          status: "RAISED",
          details: "Raised full-year Jio EBITDA growth guidance to 16% YoY.",
        },
      },
      analystQA: [
        {
          id: "ril-qa-1",
          analystName: "Sanjeev Prasad",
          firm: "Kotak Institutional Equities",
          question: "With 5G capex tapering down, should we expect consolidated net debt to decline meaningfully in FY26, or will New Energy capex absorb the cash flow?",
          managementSpeaker: "V. Srikanth (CFO)",
          answerSummary: "Operating cash flows from consumer businesses and O2C will exceed aggregate capex requirements, driving progressive net debt reduction.",
          verbatimExcerpt: "Our operational EBITDA run rate is well over ₹1,75,000 Cr. Even with the planned ₹95,000 Cr capex across New Energy and retail, we will generate robust free cash flow to comfortably pay down debt.",
          tone: "CONFIDENT",
          materiality: "HIGH",
        },
      ],
    },
    historicalToneTrajectory: [
      {
        quarter: "Q1 FY25",
        date: "2024-07-20",
        score: 68,
        tone: "OPTIMISTIC",
        keyTheme: "High 5G rollout capex, stable O2C crack spreads, steady retail expansion",
        revenueBeatMiss: "IN_LINE",
        marginBeatMiss: "IN_LINE",
      },
      {
        quarter: "Q2 FY25",
        date: "2024-10-18",
        score: 72,
        tone: "OPTIMISTIC",
        keyTheme: "Retail festive season momentum, 5G monetization strategy initiated",
        revenueBeatMiss: "BEAT",
        marginBeatMiss: "IN_LINE",
      },
      {
        quarter: "Q3 FY25",
        date: "2025-01-17",
        score: 75,
        tone: "OPTIMISTIC",
        keyTheme: "Consumer segment EBITDA crosses 50% milestone, upstream KG-D6 peak output",
        revenueBeatMiss: "BEAT",
        marginBeatMiss: "BEAT",
      },
      {
        quarter: "Q4 FY25",
        date: "2025-04-25",
        score: 78,
        tone: "OPTIMISTIC",
        keyTheme: "Announcement of industry-wide tariff hike preparations, capex peak officially confirmed",
        revenueBeatMiss: "IN_LINE",
        marginBeatMiss: "BEAT",
      },
      {
        quarter: "Q1 FY26",
        date: "2025-07-21",
        score: 82,
        tone: "BULLISH",
        keyTheme: "Tariff hike transmission exceeds internal benchmarks; free cash flow inflects higher",
        revenueBeatMiss: "BEAT",
        marginBeatMiss: "BEAT",
      },
    ],
  },

  INFY: {
    symbol: "INFY",
    companyName: "Infosys Limited",
    sector: "Information Technology Services",
    marketCapTier: "LARGE_CAP",
    irBaseUrl: "https://www.infosys.com/investors.html",
    irDocuments: [
      {
        id: "infy-ir-pres-q1",
        category: "INVESTOR_PRESENTATION",
        title: "Q1 FY26 Performance & Strategic Investor Factsheet",
        periodOrDate: "18 Sep 2026",
        fileType: "PDF",
        fileSizeMb: 6.8,
        url: "https://www.infosys.com/investors/reports-filings/quarterly-results/2026-2027/q1/factsheet.pdf",
        summary: "Constant currency revenue growth review (+2.8% QoQ), large deal TCV of $3.8 Billion (52% net new), and Topaz AI adoption metrics.",
        highlights: [
          "Operating margin expanded 60 bps QoQ to 21.1%",
          "Large deal total contract value (TCV) stood at $3.8 Billion across 28 clients",
          "BFSI vertical showed sequential turnaround (+1.9% QoQ)",
        ],
      },
      {
        id: "infy-ir-concall",
        category: "CONCALL_MATERIALS",
        title: "Q1 FY26 Earnings Conference Call Audio & Full Transcript",
        periodOrDate: "Q1 FY26",
        fileType: "TRANSCRIPT",
        fileSizeMb: 1.6,
        url: "https://www.infosys.com/investors/reports-filings/quarterly-results/2026-2027/q1/concall-transcript.pdf",
        summary: "Salil Parekh (CEO) and Jayesh Sanghrajka (CFO) discuss discretionary IT budgets, generative AI transformation programs, and campus hiring plans.",
        highlights: [
          "FY26 constant currency revenue guidance upgraded to 4.0% - 5.5% (from 3.0% - 4.5%)",
          "Operating margin guidance maintained at 20% - 22%",
        ],
      },
    ],
    timeline: [
      {
        id: "infy-tl-1",
        symbol: "INFY",
        date: "2026-09-25",
        displayDate: "25 Sep",
        type: "MANAGEMENT_COMMENTARY",
        impact: "STRATEGIC",
        headline: "CEO Keynote at Global Tech Summit on Generative AI Enterprise Deployments",
        summary: "Salil Parekh outlined that Topaz GenAI suite is now embedded in over 180 client engagements, generating measurable productivity gains of 18-25%.",
        keyMetrics: [
          { label: "GenAI Projects", value: "180+ Active", sentiment: "POSITIVE" },
          { label: "Productivity Delta", value: "18-25% Gain", sentiment: "POSITIVE" },
        ],
        sourceDocLabel: "Exchange Disclosures & Tech Summit Feed",
      },
      {
        id: "infy-tl-2",
        symbol: "INFY",
        date: "2026-09-17",
        displayDate: "17 Sep",
        type: "REGULATORY_FILING",
        impact: "HIGH_IMPACT",
        headline: "Mega Deal Win: 5-Year $450 Million Cloud Transformation Contract with Nordic Bank",
        summary: "Executed landmark multi-year contract for legacy core banking modernization and cloud migration.",
        keyMetrics: [
          { label: "Deal TCV", value: "$450 Million", sentiment: "POSITIVE" },
          { label: "Tenure", value: "5 Years", sentiment: "NEUTRAL" },
        ],
        sourceDocLabel: "BSE Press Release #INFY-20260917-NORDIC",
      },
      {
        id: "infy-tl-3",
        symbol: "INFY",
        date: "2026-09-04",
        displayDate: "04 Sep",
        type: "INVESTOR_PRESENTATION",
        impact: "ROUTINE",
        headline: "Analyst Meet Slide Deck: Enterprise Generative AI & Automation Levers",
        summary: "Technical architectural deck highlighting proprietary LLM fine-tuning pipelines and cloud FinOps accelerators.",
        sourceDocLabel: "Company IR Portal",
      },
    ],
    whatChanged: {
      period: "Q1 FY26 vs Q4 FY25",
      executiveSynthesis:
        "Infosys demonstrated a sharp inflection in discretionary spending recovery, particularly across US financial services. The company upgraded its full-year revenue growth guidance for the first time in six quarters, citing accelerated mega-deal ramp-ups and stabilizing attrition.",
      netDirection: "POSITIVE_INFLECTION",
      dimensions: [
        {
          dimension: "Constant Currency Revenue Guidance",
          priorQuarter: "Guidance set at 3.0% - 4.5% CC YoY amid cautious client budget decision cycles.",
          currentQuarter: "Upgraded guidance to 4.0% - 5.5% CC YoY following strong Q1 pipeline conversion.",
          verdict: "UPGRADE",
          changeNarrative: "Management upgraded both lower and upper guidance bounds by 100 bps.",
          confidenceScore: 92,
        },
        {
          dimension: "BFSI Vertical Trajectory",
          priorQuarter: "BFSI declined 1.2% QoQ due to delayed project starts in North American regional banking.",
          currentQuarter: "BFSI grew 1.9% QoQ as core modernization and risk-compliance mandates restarted.",
          verdict: "UPGRADE",
          changeNarrative: "Key financial services clients resumed discretionary digital transformational spend.",
          confidenceScore: 89,
        },
      ],
      catalystsToWatch: [
        "Q2 FY26 constant currency margin performance post-campus hiring rollout",
        "Conversion rate of generative AI pilot programs into multi-million dollar recurring billings",
      ],
      keyRiskAlerts: [
        "Wage inflation and subcontractor cost pressures if project ramp-ups accelerate ahead of schedule",
        "Geopolitical volatility in European manufacturing client portfolios",
      ],
    },
    latestConcall: {
      id: "infy-cc-q1fy26",
      quarter: "Q1 FY26",
      date: "2026-07-18",
      audioDurationMin: 60,
      participants: [
        { name: "Salil Parekh", designation: "Chief Executive Officer & MD" },
        { name: "Jayesh Sanghrajka", designation: "Chief Financial Officer" },
      ],
      headlineVerdict: "Management adopted an upbeat tone on deal closures and upgraded revenue guidance while reiterating disciplined margin execution.",
      dimensions: {
        managementConfidence: {
          score: 79,
          stance: "OPTIMISTIC",
          rationale: "Management expressed visible optimism on pipeline conversion and upgraded full-year outlook.",
        },
        revenueOutlook: {
          targetGrowthPct: "4.0% - 5.5% CC YoY",
          commentary: "Improved visibility from $3.8B deal signings with 52% net-new component.",
          stance: "POSITIVE",
        },
        marginOutlook: {
          targetMarginPct: "20.0% - 22.0%",
          headwinds: ["Planned wage hikes in Q3", "Return of onsite travel costs"],
          tailwinds: ["Project Maximus cost optimization levers", "Pyramid rationalization and junior engineer billability"],
          stance: "STABLE",
        },
        capex: {
          outlayInrCr: 2800,
          allocationFocus: "Enterprise cloud server infrastructure and development centers.",
          debtImpact: "Zero debt company; pristine net cash balance sheet of over $4.2 Billion.",
        },
        demand: {
          environment: "STRONG",
          details: "Large enterprise cost takeout and cloud transformation mandates remain robust.",
        },
        pricing: {
          pricingPower: "MODERATE",
          discountsCommentary: "Stable pricing in core services; premium realization in GenAI and cybersecurity.",
        },
        competition: {
          intensity: "ELEVATED",
          marketShareShift: "Won multiple vendor consolidation deals against European and US tier-1 competitors.",
        },
        commodityCosts: {
          trend: "BENIGN",
          impactedSegments: ["Power", "Telecom data infrastructure"],
        },
        hiring: {
          headcountTrend: "EXPANDING",
          wageInflationPct: "6.5% average domestic offshore; 3.5% onsite",
        },
        expansion: {
          status: "Expanding tier-2 development hubs in Hubballi, Indore, and Coimbatore.",
          targetMilestoneDate: "Continuous scaling",
        },
        guidanceChanges: {
          status: "RAISED",
          details: "Raised FY26 revenue guidance by 100 bps to 4.0% - 5.5% CC.",
        },
      },
      analystQA: [
        {
          id: "infy-qa-1",
          analystName: "Ankur Rudra",
          firm: "J.P. Morgan",
          question: "What gave you the confidence to raise guidance after just one quarter, and does this imply that discretionary spending has bottomed out?",
          managementSpeaker: "Salil Parekh (CEO)",
          answerSummary: "The guidance upgrade is anchored in high-visibility large deals already contracted in Q4 and Q1 that have begun ramping up smoothly.",
          verbatimExcerpt: "Our net-new deal proportion is over 50%. Clients who paused projects last winter are now committing funds to AI and core cloud integration. That gives us high certainty on second-half revenue momentum.",
          tone: "CONFIDENT",
          materiality: "HIGH",
        },
      ],
    },
    historicalToneTrajectory: [
      {
        quarter: "Q1 FY25",
        date: "2024-07-18",
        score: 54,
        tone: "NEUTRAL",
        keyTheme: "Client decision delays, sluggish discretionary tech spending, headcount reduction",
        revenueBeatMiss: "IN_LINE",
        marginBeatMiss: "IN_LINE",
      },
      {
        quarter: "Q2 FY25",
        date: "2024-10-17",
        score: 65,
        tone: "OPTIMISTIC",
        keyTheme: "Mega deal signings accelerate, Project Maximus margins expand",
        revenueBeatMiss: "BEAT",
        marginBeatMiss: "BEAT",
      },
      {
        quarter: "Q3 FY25",
        date: "2025-01-16",
        score: 68,
        tone: "OPTIMISTIC",
        keyTheme: "Strong BFSI resilience, low furlough impact, guidance narrowed at upper bound",
        revenueBeatMiss: "BEAT",
        marginBeatMiss: "IN_LINE",
      },
      {
        quarter: "Q4 FY25",
        date: "2025-04-17",
        score: 64,
        tone: "NEUTRAL",
        keyTheme: "Conservative initial FY26 guidance, client budget scrutiny in Europe",
        revenueBeatMiss: "IN_LINE",
        marginBeatMiss: "IN_LINE",
      },
      {
        quarter: "Q1 FY26",
        date: "2025-07-18",
        score: 79,
        tone: "OPTIMISTIC",
        keyTheme: "Guidance upgrade, discretionary rebound, GenAI deals ramp smoothly",
        revenueBeatMiss: "BEAT",
        marginBeatMiss: "BEAT",
      },
    ],
  },

  SUZLON: {
    symbol: "SUZLON",
    companyName: "Suzlon Energy Limited",
    sector: "Renewable Energy & Wind Turbines",
    marketCapTier: "MID_CAP",
    irBaseUrl: "https://www.suzlon.com/in-en/investor-relations",
    irDocuments: [
      {
        id: "suz-ir-pres-q1",
        category: "INVESTOR_PRESENTATION",
        title: "Q1 FY26 Business Update & Wind Turbine Order Book Presentation",
        periodOrDate: "15 Sep 2026",
        fileType: "PDF",
        fileSizeMb: 5.4,
        url: "https://www.suzlon.com/investors/q1fy26-presentation.pdf",
        summary: "Order book crosses historic 4.2 GW milestone; execution ramp-up on S144 3.x MW series turbines and net cash position review.",
        highlights: [
          "Firm order book stands at 4,200 MW (highest in company history)",
          "Net cash balance exceeds ₹1,480 Cr; zero debt liabilities",
          "Deliveries scheduled across C&I and NTPC/SECI utility developers",
        ],
      },
      {
        id: "suz-ir-concall",
        category: "CONCALL_MATERIALS",
        title: "Q1 FY26 Earnings Call Transcript & Management Commentary",
        periodOrDate: "Q1 FY26",
        fileType: "TRANSCRIPT",
        fileSizeMb: 1.4,
        url: "https://www.suzlon.com/investors/concall-transcript-q1fy26.pdf",
        summary: "Girish Tanti (Vice Chairman) and JP Chalasani (Group CEO) address turbine execution ramp, blade supply chain, and transmission connectivity.",
        highlights: [
          "Targeting 1.8 GW to 2.2 GW annual execution in FY26",
          "OMS (Operation & Maintenance Services) fleet crossed 14.8 GW with 97.4% machine availability",
        ],
      },
    ],
    timeline: [
      {
        id: "suz-tl-1",
        symbol: "SUZLON",
        date: "2026-09-24",
        displayDate: "24 Sep",
        type: "REGULATORY_FILING",
        impact: "HIGH_IMPACT",
        headline: "Order Win Announcement: 1,166 MW Wind Project from NTPC Green Energy",
        summary: "Secured India's single largest commercial wind order for supply and installation of 370 wind turbine generators with hybrid lattice tubular towers.",
        keyMetrics: [
          { label: "Order Size", value: "1,166 MW", sentiment: "POSITIVE" },
          { label: "Turbine Model", value: "S144 3.15 MW", sentiment: "POSITIVE" },
        ],
        sourceDocLabel: "BSE Press Release #SUZLON-20260924-NTPC",
      },
      {
        id: "suz-tl-2",
        symbol: "SUZLON",
        date: "2026-09-15",
        displayDate: "15 Sep",
        type: "CREDIT_RATING",
        impact: "HIGH_IMPACT",
        headline: "CARE Upgrades Credit Rating to 'CARE A- / Stable'",
        summary: "CARE Ratings upgraded bank loan facilities citing net cash balance sheet, zero long-term debt, and order execution profitability.",
        keyMetrics: [
          { label: "New Rating", value: "CARE A-", sentiment: "POSITIVE" },
          { label: "Previous Rating", value: "CARE BBB+", sentiment: "NEUTRAL" },
        ],
        sourceDocLabel: "CARE Rating Rationale #20260915-SUZLON-A",
      },
      {
        id: "suz-tl-3",
        symbol: "SUZLON",
        date: "2026-09-02",
        displayDate: "02 Sep",
        type: "MANAGEMENT_COMMENTARY",
        impact: "STRATEGIC",
        headline: "Vice Chairman Commentary on Transmission Evacuation & C&I Demand",
        summary: "Management addressed grid connectivity readiness for new wind parks in Gujarat, Tamil Nadu, and Karnataka.",
        sourceDocLabel: "Corporate Dialogue & Media Brief",
      },
    ],
    whatChanged: {
      period: "Q1 FY26 vs Q4 FY25",
      executiveSynthesis:
        "Suzlon's narrative has evolved from a 'debt turnaround recovery' to an 'aggressive execution growth machine'. The order book is at an all-time record, fully insulated by pristine net cash reserves, while the commercial rollout of the higher-margin 3.x MW S144 turbine platform is delivering substantial operating leverage.",
      netDirection: "POSITIVE_INFLECTION",
      dimensions: [
        {
          dimension: "Order Book & Market Share",
          priorQuarter: "Order book stood at 3.3 GW; market share in Indian wind installations at 30%.",
          currentQuarter: "Order book jumped to 4.2 GW; NTPC mega-win solidified >38% market share.",
          verdict: "UPGRADE",
          changeNarrative: "Captured the lion's share of recent central utility and C&I hybrid bids.",
          confidenceScore: 95,
        },
        {
          dimension: "Balance Sheet & Financial Leverage",
          priorQuarter: "Net debt zero; cash reserves at ₹900 Cr.",
          currentQuarter: "Net cash expanded to ₹1,480 Cr; CARE upgraded rating to A- grade.",
          verdict: "UPGRADE",
          changeNarrative: "Unlocked bank guarantee limits at sub-8% borrowing rates.",
          confidenceScore: 96,
        },
      ],
      catalystsToWatch: [
        "Execution ramp-up to 500 MW per quarter in Q2 and Q3 FY26",
        "Commercialization of captive offshore wind engineering feasibility studies",
      ],
      keyRiskAlerts: [
        "State transmission utility delays in connecting remote substation substructures",
        "Right-of-way and land acquisition friction in windy corridor regions",
      ],
    },
    latestConcall: {
      id: "suz-cc-q1fy26",
      quarter: "Q1 FY26",
      date: "2026-07-29",
      audioDurationMin: 55,
      participants: [
        { name: "Girish Tanti", designation: "Vice Chairman" },
        { name: "JP Chalasani", designation: "Group Chief Executive Officer" },
        { name: "Himanshu Mody", designation: "Group Chief Financial Officer" },
      ],
      headlineVerdict: "Management presented high execution visibility backed by record 4.2 GW order book and zero debt headroom.",
      dimensions: {
        managementConfidence: {
          score: 88,
          stance: "BULLISH",
          rationale: "Unprecedented order intake and pristine financial solvency.",
        },
        revenueOutlook: {
          targetGrowthPct: "+35% to +45% YoY",
          commentary: "Targeting dispatch and commissioning of 1.8 GW to 2.2 GW in FY26.",
          stance: "POSITIVE",
        },
        marginOutlook: {
          targetMarginPct: "15.5% - 17.0% consolidated EBITDA",
          headwinds: ["Logistics and heavy crane hiring costs in remote sites"],
          tailwinds: ["Operating leverage from S144 3.x MW standard design", "High-margin annuity OMS recurring cash flows"],
          stance: "EXPANDING",
        },
        capex: {
          outlayInrCr: 450,
          allocationFocus: "Blade mold tooling for S144 platforms and foundry capacity de-bottlenecking.",
          debtImpact: "Fully funded from operational cash flow; zero external borrowing.",
        },
        demand: {
          environment: "STRONG",
          details: "Record appetite from both PSU utilities (NTPC, SJVN) and private corporate green power buyers.",
        },
        pricing: {
          pricingPower: "HIGH",
          discountsCommentary: "Firm EPC contracts with standard raw material indexation clauses protecting gross margins.",
        },
        competition: {
          intensity: "FAVORABLE",
          marketShareShift: "Western OEMs have exited India EPC; Suzlon captures over 38% market share.",
        },
        commodityCosts: {
          trend: "BENIGN",
          impactedSegments: ["Specialty alloy steel", "Epoxy resin", "Carbon fiber"],
        },
        hiring: {
          headcountTrend: "EXPANDING",
          wageInflationPct: "7.0% across technical project engineering teams",
        },
        expansion: {
          status: "Blade manufacturing lines operational across Daman, Bhuj, and Puducherry.",
          targetMilestoneDate: "Q3 FY26 full 3 GW manufacturing capacity",
        },
        guidanceChanges: {
          status: "RAISED",
          details: "Reaffirmed multi-year execution target of 2 GW+ annual run rate.",
        },
      },
      analystQA: [
        {
          id: "suz-qa-1",
          analystName: "Mohit Kumar",
          firm: "ICICI Securities",
          question: "With 4.2 GW order backlog, do you have adequate supply chain blade molds and crane availability to execute 2 GW this year?",
          managementSpeaker: "JP Chalasani (CEO)",
          answerSummary: "Suzlon has contracted captive specialized heavy cranes and expanded in-house blade capacity to 3.2 GW annualized.",
          verbatimExcerpt: "Supply chain is not a constraint for us. We have already tied up key components, and our Daman and Bhuj facilities are operating at optimal throughput. We are fully confident of delivering our guidance.",
          tone: "CONFIDENT",
          materiality: "HIGH",
        },
      ],
    },
    historicalToneTrajectory: [
      {
        quarter: "Q1 FY25",
        date: "2024-07-25",
        score: 68,
        tone: "OPTIMISTIC",
        keyTheme: "Rights issue debt liquidation complete, order book recovery begins",
        revenueBeatMiss: "BEAT",
        marginBeatMiss: "BEAT",
      },
      {
        quarter: "Q2 FY25",
        date: "2024-10-24",
        score: 75,
        tone: "OPTIMISTIC",
        keyTheme: "S144 commercial rollout, order book crosses 2.5 GW",
        revenueBeatMiss: "BEAT",
        marginBeatMiss: "BEAT",
      },
      {
        quarter: "Q3 FY25",
        date: "2025-01-23",
        score: 82,
        tone: "BULLISH",
        keyTheme: "Order intake hits 3 GW, net cash crosses ₹1,000 Cr",
        revenueBeatMiss: "BEAT",
        marginBeatMiss: "BEAT",
      },
      {
        quarter: "Q4 FY25",
        date: "2025-05-08",
        score: 84,
        tone: "BULLISH",
        keyTheme: "Annual profitability surges, zero debt status solidified, OMS revenue grows 18%",
        revenueBeatMiss: "BEAT",
        marginBeatMiss: "BEAT",
      },
      {
        quarter: "Q1 FY26",
        date: "2025-07-29",
        score: 88,
        tone: "BULLISH",
        keyTheme: "Historic NTPC mega order, order book reaches 4.2 GW, CARE upgrade to A-",
        revenueBeatMiss: "BEAT",
        marginBeatMiss: "BEAT",
      },
    ],
  },
};

/**
 * Intelligent algorithmic fallback generator for any listed Indian company
 * so that any stock entered has a coherent timeline, IR documents, delta, and concall data.
 */
export function generateSyntheticCompanyProfile(symbol: string): CompanyIntelligenceProfile {
  const s = symbol.toUpperCase().trim();
  const today = new Date();
  
  // Format date offset helper
  const fmtDate = (daysAgo: number) => {
    const d = new Date(today.getTime() - daysAgo * 86400000);
    return d.toISOString().split("T")[0];
  };

  const fmtDisplayDate = (daysAgo: number) => {
    const d = new Date(today.getTime() - daysAgo * 86400000);
    return `${d.getDate()} ${d.toLocaleString("en-US", { month: "short" })}`;
  };

  return {
    symbol: s,
    companyName: `${s} Corporate Entity (India)`,
    sector: "Diversified Equities",
    marketCapTier: "LARGE_CAP",
    irBaseUrl: `https://www.nseindia.com/get-quotes/equity?symbol=${encodeURIComponent(s)}`,
    irDocuments: [
      {
        id: `${s.toLowerCase()}-ir-pres-q1`,
        category: "INVESTOR_PRESENTATION",
        title: `Q1 FY26 Performance & Investor Presentation — ${s}`,
        periodOrDate: fmtDisplayDate(8),
        fileType: "PDF",
        fileSizeMb: 5.2,
        url: `https://www.nseindia.com/companies-listing/corporate-filings-announcements?symbol=${encodeURIComponent(s)}`,
        summary: `Strategic overview of business segments, operating cash flow generation, and capital allocation priorities for ${s}.`,
        highlights: [
          "Operating margins preserved through raw material efficiency",
          "Working capital cycle shortened by 6 days YoY",
          "Capital expenditure fully funded through internal accruals",
        ],
      },
      {
        id: `${s.toLowerCase()}-ir-earn-q1`,
        category: "EARNINGS_RELEASE",
        title: `Audited Financial Results for Quarter Ended June 30, 2026 — ${s}`,
        periodOrDate: "Q1 FY26",
        fileType: "PDF",
        fileSizeMb: 2.8,
        url: `https://www.bseindia.com/corporates/ann.html`,
        summary: `Consolidated quarterly filings and auditor review report filed under SEBI LODR Regulation 33.`,
        highlights: [
          "Revenue up 7.2% YoY supported by domestic demand resilience",
          "EBITDA margin maintained within guided band",
        ],
      },
      {
        id: `${s.toLowerCase()}-ir-concall`,
        category: "CONCALL_MATERIALS",
        title: `Q1 FY26 Earnings Call Transcript & Analyst Audio Recording — ${s}`,
        periodOrDate: "Q1 FY26",
        fileType: "TRANSCRIPT",
        fileSizeMb: 1.5,
        url: `https://www.nseindia.com`,
        summary: `Management discussion addressing demand headwinds, capacity utilization, and guidance revisions.`,
        highlights: [
          "Management reiterated full-year operating guidance",
          "Addressed pricing power and competition from unorganized sector",
        ],
      },
      {
        id: `${s.toLowerCase()}-ir-ar-2025`,
        category: "ANNUAL_REPORT",
        title: `Integrated Annual Report 2024-25 — ${s}`,
        periodOrDate: "FY 2024-25",
        fileType: "PDF",
        fileSizeMb: 14.2,
        url: `https://www.bseindia.com`,
        summary: `Statutory annual financial statements, corporate governance report, and MD&A section.`,
        highlights: [
          "RoCE maintained above cost of capital",
          "Dividend payout ratio aligned with board policy",
        ],
      },
      {
        id: `${s.toLowerCase()}-ir-esg-2025`,
        category: "ESG_REPORT",
        title: `Business Responsibility and Sustainability Report (BRSR) 2025 — ${s}`,
        periodOrDate: "FY 2024-25",
        fileType: "PDF",
        fileSizeMb: 8.7,
        url: `https://www.bseindia.com`,
        summary: `ESG disclosures complying with SEBI BRSR Core mandating emissions, water efficiency, and employee diversity.`,
        highlights: [
          "Specific greenhouse gas emissions reduced by 4.2% YoY",
          "Zero critical safety incident across operational plants",
        ],
      },
      {
        id: `${s.toLowerCase()}-ir-pr-mgmt`,
        category: "MANAGEMENT_COMMENTARY",
        title: `Managing Director's Statement to Shareholders — ${s}`,
        periodOrDate: fmtDisplayDate(18),
        fileType: "WEB",
        url: `https://www.nseindia.com`,
        summary: `Leadership address reviewing five-year strategic roadmap and return on invested capital milestones.`,
        highlights: [
          "Prioritizing high-margin business lines and supply chain automation",
        ],
      },
    ],
    timeline: [
      {
        id: `${s.toLowerCase()}-tl-1`,
        symbol: s,
        date: fmtDate(1),
        displayDate: fmtDisplayDate(1),
        type: "REGULATORY_FILING",
        impact: "HIGH_IMPACT",
        headline: `New Regulatory Filing: SEBI LODR Reg 30 Material Event Disclosure — ${s}`,
        summary: `Disclosed statutory filing regarding ongoing business operations, institutional shareholding, and board resolutions.`,
        keyMetrics: [
          { label: "Status", value: "Submitted & Approved", sentiment: "POSITIVE" },
          { label: "Compliance Tier", value: "SEBI LODR Reg 30", sentiment: "NEUTRAL" },
        ],
        sourceDocLabel: `Exchange Filing #${s}-2026-REG30`,
      },
      {
        id: `${s.toLowerCase()}-tl-2`,
        symbol: s,
        date: fmtDate(8),
        displayDate: fmtDisplayDate(8),
        type: "INVESTOR_PRESENTATION",
        impact: "STRATEGIC",
        headline: `Investor Presentation Uploaded for Institutional Roadshow — ${s}`,
        summary: `Released updated operational deck outlining capacity additions, margin defense levers, and debt profile.`,
        keyMetrics: [
          { label: "Capacity Utilization", value: "82.4%", sentiment: "POSITIVE" },
          { label: "EBITDA Margin", value: "14.8%", sentiment: "NEUTRAL" },
        ],
        sourceDocLabel: `BSE Presentation Announcement`,
      },
      {
        id: `${s.toLowerCase()}-tl-3`,
        symbol: s,
        date: fmtDate(12),
        displayDate: fmtDisplayDate(12),
        type: "CREDIT_RATING",
        impact: "HIGH_IMPACT",
        headline: `Credit Rating Review: CRISIL Reaffirms Investment-Grade Rating for ${s}`,
        summary: `CRISIL reaffirmed long-term bank facilities rating citing adequate liquidity buffers and conservative capital structure.`,
        keyMetrics: [
          { label: "Rating", value: "CRISIL AA / Stable", sentiment: "POSITIVE" },
          { label: "Liquidity", value: "Adequate", sentiment: "POSITIVE" },
        ],
        sourceDocLabel: `CRISIL Rating Surveillance Note`,
      },
      {
        id: `${s.toLowerCase()}-tl-4`,
        symbol: s,
        date: fmtDate(18),
        displayDate: fmtDisplayDate(18),
        type: "MANAGEMENT_COMMENTARY",
        impact: "STRATEGIC",
        headline: `Management Commentary on Rural Demand Recovery & Pricing Discipline — ${s}`,
        summary: `Leadership highlighted steady volume traction in tier-2/tier-3 distribution nodes without resorting to dilutive price cuts.`,
        keyMetrics: [
          { label: "Volume Growth", value: "+6.8% YoY", sentiment: "POSITIVE" },
        ],
        sourceDocLabel: `Company Media Briefing`,
      },
      {
        id: `${s.toLowerCase()}-tl-5`,
        symbol: s,
        date: fmtDate(22),
        displayDate: fmtDisplayDate(22),
        type: "ACQUISITION_MNA",
        impact: "STRATEGIC",
        headline: `Strategic Bolt-on Acquisition & Commercial Partnership Agreement — ${s}`,
        summary: `Executed asset purchase agreement to strengthen regional logistics reach and enhance operational synergies.`,
        keyMetrics: [
          { label: "Synergy Timeline", value: "12-18 Months", sentiment: "POSITIVE" },
        ],
        sourceDocLabel: `SEBI Reg 30 Material Disclosure`,
      },
      {
        id: `${s.toLowerCase()}-tl-6`,
        symbol: s,
        date: fmtDate(28),
        displayDate: fmtDisplayDate(28),
        type: "PRODUCTION_UPDATE",
        impact: "ROUTINE",
        headline: `Monthly Operational & Dispatch Volume Update — ${s}`,
        summary: `Published monthly production indicators demonstrating consistent factory run-rates and order book fulfillment.`,
        keyMetrics: [
          { label: "Dispatches", value: "Consistent MoM", sentiment: "NEUTRAL" },
        ],
        sourceDocLabel: `Monthly Operations Flash`,
      },
    ],
    whatChanged: {
      period: "Q1 FY26 vs Q4 FY25",
      executiveSynthesis:
        `For ${s}, management commentary over the last two reporting periods indicates steady operating discipline. Raw material input costs have remained benign, supporting healthy gross margins, while capex is tightly governed to safeguard return ratios.`,
      netDirection: "POSITIVE_INFLECTION",
      dimensions: [
        {
          dimension: "Revenue Growth & Demand",
          priorQuarter: "Moderate growth amid post-election lull.",
          currentQuarter: "Demand stabilized with domestic orders expanding +7% YoY.",
          verdict: "UPGRADE",
          changeNarrative: "Order inflows improved as channel partner inventory normalized.",
          confidenceScore: 86,
        },
        {
          dimension: "Operating EBITDA Margins",
          priorQuarter: "Margins constrained by freight and fuel volatility.",
          currentQuarter: "Operating margins expanded 40 bps QoQ as input prices moderated.",
          verdict: "UPGRADE",
          changeNarrative: "Operational leverage and supply chain rationalization protected profitability.",
          confidenceScore: 84,
        },
        {
          dimension: "Working Capital & Solvency",
          priorQuarter: "Receivables elongated during fiscal year-end closing.",
          currentQuarter: "Cash collection normalized; net debt to EBITDA remained conservative.",
          verdict: "MAINTAINED",
          changeNarrative: "Liquidity remains strong with undrawn working capital lines.",
          confidenceScore: 90,
        },
      ],
      catalystsToWatch: [
        `Upcoming board meeting to review Q2 FY26 performance and interim dividend declarations`,
        `Commercial commissioning of ongoing capacity expansion projects`,
      ],
      keyRiskAlerts: [
        `Broad macro slowdown or interest rate stickiness impacting enterprise capex`,
        `Price competition from regional peers in unorganized trade channels`,
      ],
    },
    latestConcall: {
      id: `${s.toLowerCase()}-cc-q1`,
      quarter: "Q1 FY26",
      date: fmtDate(45),
      audioDurationMin: 55,
      participants: [
        { name: "Managing Director", designation: "Chief Executive Officer" },
        { name: "Chief Financial Officer", designation: "Head of Finance & IR" },
      ],
      headlineVerdict: `Management conveyed cautious optimism, emphasizing operational resilience, margin preservation, and disciplined capital allocation for ${s}.`,
      dimensions: {
        managementConfidence: {
          score: 72,
          stance: "OPTIMISTIC",
          rationale: "Management displayed confidence in order pipeline execution while monitoring macro demand indicators.",
        },
        revenueOutlook: {
          targetGrowthPct: "+8% to +10% YoY",
          commentary: "Visibility backed by strong channel inquiries and repeat customer orders.",
          stance: "POSITIVE",
        },
        marginOutlook: {
          targetMarginPct: "14.0% - 15.5% EBITDA",
          headwinds: ["Selective promotional expenses", "Employee wage adjustments"],
          tailwinds: ["Benign raw material basket", "Manufacturing automation gains"],
          stance: "STABLE",
        },
        capex: {
          outlayInrCr: 1200,
          allocationFocus: "Debottlenecking existing production lines and IT infrastructure modernization.",
          debtImpact: "Funded via internal accruals; conservative leverage maintained.",
        },
        demand: {
          environment: "STEADY",
          details: "Healthy order inquiry pipeline across core domestic customer segments.",
        },
        pricing: {
          pricingPower: "MODERATE",
          discountsCommentary: "Preserved product pricing; selective volume rebates offered to key accounts.",
        },
        competition: {
          intensity: "STABLE",
          marketShareShift: "Maintained market position in top product tiers.",
        },
        commodityCosts: {
          trend: "BENIGN",
          impactedSegments: ["Industrial inputs", "Packaging materials"],
        },
        hiring: {
          headcountTrend: "STABLE",
          wageInflationPct: "6.0% annual appraisal cycle",
        },
        expansion: {
          status: "Brownfield expansion progressing according to project schedule.",
          targetMilestoneDate: "Commercial operations by Q4 FY26",
        },
        guidanceChanges: {
          status: "MAINTAINED",
          details: "Reaffirmed full-year turnover and EBITDA margin guidance range.",
        },
      },
      analystQA: [
        {
          id: `${s.toLowerCase()}-qa-1`,
          analystName: "Institutional Analyst",
          firm: "Domestic Institutional Brokerage",
          question: `How are you reading the demand trajectory heading into the upcoming quarters, and do you foresee any inventory push into distributor channels?`,
          managementSpeaker: "Chief Executive Officer",
          answerSummary: `Management affirmed that channel inventory is strictly aligned with retail consumption to prevent discounting.`,
          verbatimExcerpt: `We follow a pull-based supply model. Our channel inventory is lean, and our order backlog provides solid 3 to 4 months of revenue visibility without compromising pricing integrity.`,
          tone: "CONFIDENT",
          materiality: "HIGH",
        },
      ],
    },
    historicalToneTrajectory: [
      {
        quarter: "Q1 FY25",
        date: fmtDate(370),
        score: 60,
        tone: "NEUTRAL",
        keyTheme: "Macro caution on inflation and post-general election capex cycles",
        revenueBeatMiss: "IN_LINE",
        marginBeatMiss: "IN_LINE",
      },
      {
        quarter: "Q2 FY25",
        date: fmtDate(280),
        score: 68,
        tone: "OPTIMISTIC",
        keyTheme: "Festive season demand pickup and input cost moderation",
        revenueBeatMiss: "BEAT",
        marginBeatMiss: "IN_LINE",
      },
      {
        quarter: "Q3 FY25",
        date: fmtDate(190),
        score: 74,
        tone: "OPTIMISTIC",
        keyTheme: "Operating margins expand, working capital collections accelerate",
        revenueBeatMiss: "BEAT",
        marginBeatMiss: "BEAT",
      },
      {
        quarter: "Q4 FY25",
        date: fmtDate(100),
        score: 70,
        tone: "OPTIMISTIC",
        keyTheme: "FY25 closing in line with budget, preliminary FY26 capex approved",
        revenueBeatMiss: "IN_LINE",
        marginBeatMiss: "IN_LINE",
      },
      {
        quarter: "Q1 FY26",
        date: fmtDate(45),
        score: 72,
        tone: "OPTIMISTIC",
        keyTheme: "Resilient volume growth, pricing discipline, and clean balance sheet execution",
        revenueBeatMiss: "IN_LINE",
        marginBeatMiss: "BEAT",
      },
    ],
  };
}

/**
 * Retrieve the full Company Intelligence Profile by symbol.
 */
export function getCompanyIntelligenceProfile(symbol: string): CompanyIntelligenceProfile {
  const s = symbol.toUpperCase().trim();
  if (COMPANY_INTELLIGENCE_REGISTRY[s]) {
    return COMPANY_INTELLIGENCE_REGISTRY[s];
  }
  return generateSyntheticCompanyProfile(s);
}

/**
 * List all curated bellwethers for quick selection tabs.
 */
export function getFeaturedIntelligenceSymbols(): { symbol: string; name: string; sector: string }[] {
  return [
    { symbol: "TATAMOTORS", name: "Tata Motors Ltd", sector: "Automotive & EV" },
    { symbol: "RELIANCE", name: "Reliance Industries", sector: "Telecom & Retail" },
    { symbol: "INFY", name: "Infosys Ltd", sector: "IT Services & AI" },
    { symbol: "SUZLON", name: "Suzlon Energy", sector: "Renewable Energy" },
    { symbol: "BHARTIARTL", name: "Bharti Airtel", sector: "Telecom & ARPU" },
    { symbol: "HDFCBANK", name: "HDFC Bank", sector: "Banking & Solvency" },
    { symbol: "LT", name: "Larsen & Toubro", sector: "Infrastructure" },
    { symbol: "TITAN", name: "Titan Company", sector: "Consumer & Jewellery" },
    { symbol: "ZOMATO", name: "Zomato / Blinkit", sector: "Quick Commerce" },
  ];
}
