"use client";

import { AdminCard } from "@/components/admin/admin-card";
import { useEffect, useState } from "react";

type Doc = { id: string; source: "admin" | "app"; title: string; content: string; created_at: string };

export default function AdminKnowledgeBasePage() {
  const [docs, setDocs] = useState<Doc[] | null>(null);
  const [form, setForm] = useState({ title: "", content: "" });
  const [saving, setSaving] = useState(false);
  const [ingesting, setIngesting] = useState(false);
  const [error, setError] = useState("");

  const [question, setQuestion] = useState("");
  const [asking, setAsking] = useState(false);
  const [answer, setAnswer] = useState<{ answer: string; sources: { id: string; title: string }[] } | null>(null);

  function load() {
    fetch("/api/admin/rag/documents")
      .then((r) => r.json())
      .then((json) => setDocs(json.documents))
      .catch(() => {});
  }
  useEffect(load, []);

  async function addDocument(e: React.FormEvent) {
    e.preventDefault();
    setSaving(true);
    setError("");
    try {
      const res = await fetch("/api/admin/rag/documents", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(form),
      });
      const json = await res.json();
      if (!res.ok) throw new Error(json.error ?? "Failed to add document");
      setForm({ title: "", content: "" });
      load();
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to add document");
    } finally {
      setSaving(false);
    }
  }

  async function removeDoc(id: string) {
    await fetch(`/api/admin/rag/documents?id=${id}`, { method: "DELETE" });
    load();
  }

  async function ingestAppData() {
    setIngesting(true);
    try {
      await fetch("/api/admin/rag/ingest-app-data", { method: "POST" });
      load();
    } finally {
      setIngesting(false);
    }
  }

  async function ask(e: React.FormEvent) {
    e.preventDefault();
    setAsking(true);
    setAnswer(null);
    try {
      const res = await fetch("/api/admin/rag/ask", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ question }),
      });
      const json = await res.json();
      if (!res.ok) throw new Error(json.error ?? "Failed to answer");
      setAnswer(json);
    } catch (e) {
      setAnswer({ answer: e instanceof Error ? e.message : "Failed to answer", sources: [] });
    } finally {
      setAsking(false);
    }
  }

  return (
    <div className="space-y-6">
      <div>
        <p className="text-sm uppercase tracking-[0.2em] text-blue-600">Knowledge base</p>
        <h1 className="mt-1 text-xl font-semibold">RAG assistant</h1>
        <p className="mt-1 text-sm text-gray-500">
          Retrieval is Postgres full-text search (no embedding model needed); answers are generated by Groq grounded in the
          retrieved documents.
        </p>
      </div>

      {error ? <p className="text-sm text-rose-600">{error}</p> : null}

      <AdminCard title="Ask the knowledge base">
        <form onSubmit={ask} className="flex gap-2">
          <input
            required
            value={question}
            onChange={(e) => setQuestion(e.target.value)}
            placeholder="e.g. how is Sharpe ratio calculated?"
            className="flex-1 rounded-md border border-gray-200 bg-gray-100 px-2.5 py-1.5 text-sm outline-none focus:border-blue-600"
          />
          <button
            type="submit"
            disabled={asking}
            className="rounded-md bg-blue-600 px-3 py-1.5 text-sm font-semibold text-white hover:opacity-90 disabled:opacity-50"
          >
            {asking ? "Asking…" : "Ask"}
          </button>
        </form>
        {answer ? (
          <div className="mt-4 rounded-md border border-gray-200 bg-gray-100 p-3 text-sm">
            <p className="whitespace-pre-wrap text-gray-800">{answer.answer}</p>
            {answer.sources.length ? (
              <p className="mt-2 text-sm text-gray-500">Sources: {answer.sources.map((s) => s.title).join(", ")}</p>
            ) : null}
          </div>
        ) : null}
      </AdminCard>

      <AdminCard
        title="Feed in data"
        subtitle="Admin-authored documents plus a one-click pull of the app's own metric glossary and macro explainers"
        action={
          <button
            type="button"
            onClick={ingestAppData}
            disabled={ingesting}
            className="rounded-md border border-gray-300 px-2.5 py-1 text-sm text-gray-700 hover:bg-gray-100 disabled:opacity-50"
          >
            {ingesting ? "Ingesting…" : "Ingest app data"}
          </button>
        }
      >
        <form onSubmit={addDocument} className="space-y-3">
          <div className="space-y-1">
            <label className="text-sm text-gray-500">Title</label>
            <input
              required
              value={form.title}
              onChange={(e) => setForm((f) => ({ ...f, title: e.target.value }))}
              className="w-full rounded-md border border-gray-200 bg-gray-100 px-2.5 py-1.5 text-sm outline-none focus:border-blue-600"
            />
          </div>
          <div className="space-y-1">
            <label className="text-sm text-gray-500">Content</label>
            <textarea
              required
              rows={5}
              value={form.content}
              onChange={(e) => setForm((f) => ({ ...f, content: e.target.value }))}
              className="w-full rounded-md border border-gray-200 bg-gray-100 px-2.5 py-1.5 text-sm outline-none focus:border-blue-600"
            />
          </div>
          <button
            type="submit"
            disabled={saving}
            className="rounded-md bg-blue-600 px-3 py-1.5 text-sm font-semibold text-white hover:opacity-90 disabled:opacity-50"
          >
            {saving ? "Adding…" : "Add document"}
          </button>
        </form>
      </AdminCard>

      <AdminCard title={`Documents (${docs?.length ?? 0})`}>
        <div className="space-y-1.5">
          {(docs ?? []).map((d) => (
            <div key={d.id} className="flex items-start justify-between gap-3 rounded-md border border-gray-200 px-3 py-2 text-sm">
              <div className="min-w-0">
                <p className="truncate font-medium text-gray-900">
                  {d.title} <span className="ml-1 rounded bg-gray-200 px-1 text-sm text-gray-500">{d.source}</span>
                </p>
                <p className="truncate text-sm text-gray-500">{d.content.slice(0, 140)}</p>
              </div>
              <button type="button" onClick={() => removeDoc(d.id)} className="shrink-0 rounded px-2 py-1 text-sm text-rose-600 hover:bg-rose-500/10">
                Delete
              </button>
            </div>
          ))}
          {docs && docs.length === 0 ? <p className="text-sm text-gray-500">No documents yet.</p> : null}
        </div>
      </AdminCard>
    </div>
  );
}
