import type { PromoterActivityRecord, PromoterActivityType } from "./types";

export const PROMOTER_ACTIVITIES_STORE: PromoterActivityRecord[] = [
  // 1. PROMOTER BUYING
  {
    id: "act-pb-01",
    symbol: "TATAMOTORS",
    companyName: "Tata Motors Limited",
    sector: "Automobile & Auto Components",
    category: "PROMOTER_BUYING",
    transactionDate: "2026-09-24",
    reportingDate: "2026-09-25",
    personName: "Tata Sons Private Limited",
    personCategory: "Promoter",
    sharesCount: 4500000,
    transactionPriceInr: 980.5,
    transactionValueCr: 441.2,
    stakePctBefore: 46.36,
    stakePctAfter: 46.48,
    stakePctChange: 0.12,
    exchange: "NSE",
    sourceRegulation: "SEBI PIT Reg 7(2)",
    riskImpact: "BULLISH_CONVICTION",
    rationale: "Parent promoter Tata Sons infused incremental equity via open market purchases, signaling strong long-term balance sheet conviction following JLR debt reduction.",
  },
  {
    id: "act-pb-02",
    symbol: "BHARTIARTL",
    companyName: "Bharti Airtel Limited",
    sector: "Telecommunication",
    category: "PROMOTER_BUYING",
    transactionDate: "2026-09-21",
    reportingDate: "2026-09-22",
    personName: "Bharti Telecom Limited",
    personCategory: "Promoter Group",
    sharesCount: 7800000,
    transactionPriceInr: 1540.0,
    transactionValueCr: 1201.2,
    stakePctBefore: 39.85,
    stakePctAfter: 40.12,
    stakePctChange: 0.27,
    exchange: "NSE",
    sourceRegulation: "SEBI SAST Reg 29",
    riskImpact: "BULLISH_CONVICTION",
    rationale: "Promoter group entity Bharti Telecom acquired additional stake to consolidate voting control ahead of 5G monetization and tariff hikes.",
  },
  {
    id: "act-pb-03",
    symbol: "BAJAJFINSV",
    companyName: "Bajaj Finserv Limited",
    sector: "Financial Services",
    category: "PROMOTER_BUYING",
    transactionDate: "2026-09-18",
    reportingDate: "2026-09-19",
    personName: "Jamnalal Sons Private Limited",
    personCategory: "Promoter",
    sharesCount: 480000,
    transactionPriceInr: 1850.0,
    transactionValueCr: 88.8,
    stakePctBefore: 54.18,
    stakePctAfter: 54.21,
    stakePctChange: 0.03,
    exchange: "BOTH",
    sourceRegulation: "SEBI PIT Reg 7(2)",
    riskImpact: "BULLISH_CONVICTION",
    rationale: "Sustained creeping acquisition by Bajaj family promoter trusts within the permissible 5% annual SAST regulatory creep window.",
  },
  {
    id: "act-pb-04",
    symbol: "SUNPHARMA",
    companyName: "Sun Pharmaceutical Industries Ltd",
    sector: "Healthcare & Pharmaceuticals",
    category: "PROMOTER_BUYING",
    transactionDate: "2026-09-15",
    reportingDate: "2026-09-16",
    personName: "Shanghvi Finance Private Limited",
    personCategory: "Promoter Group",
    sharesCount: 1100000,
    transactionPriceInr: 1820.0,
    transactionValueCr: 200.2,
    stakePctBefore: 54.48,
    stakePctAfter: 54.53,
    stakePctChange: 0.05,
    exchange: "NSE",
    sourceRegulation: "SEBI PIT Reg 7(2)",
    riskImpact: "BULLISH_CONVICTION",
    rationale: "Promoter investment arm purchased shares from the secondary market, signaling management optimism in specialty portfolio expansion.",
  },

  // 2. PROMOTER SELLING
  {
    id: "act-ps-01",
    symbol: "WHIRLPOOL",
    companyName: "Whirlpool of India Limited",
    sector: "Consumer Discretionary",
    category: "PROMOTER_SELLING",
    transactionDate: "2026-09-12",
    reportingDate: "2026-09-13",
    personName: "Whirlpool Mauritius Limited",
    personCategory: "Promoter",
    sharesCount: 30450000,
    transactionPriceInr: 1280.0,
    transactionValueCr: 3897.6,
    stakePctBefore: 75.0,
    stakePctAfter: 51.0,
    stakePctChange: -24.0,
    exchange: "NSE",
    sourceRegulation: "SEBI SAST Reg 29",
    riskImpact: "BEARISH_DILUTION",
    rationale: "Global parent trimmed stake to reduce debt at the global parent entity, introducing short-term secondary market supply overhang.",
  },
  {
    id: "act-ps-02",
    symbol: "MEDANTA",
    companyName: "Global Health Limited",
    sector: "Healthcare & Pharmaceuticals",
    category: "PROMOTER_SELLING",
    transactionDate: "2026-09-08",
    reportingDate: "2026-09-09",
    personName: "Dr. Naresh Trehan & Promoter Associates",
    personCategory: "Promoter",
    sharesCount: 4200000,
    transactionPriceInr: 1350.0,
    transactionValueCr: 567.0,
    stakePctBefore: 33.15,
    stakePctAfter: 31.58,
    stakePctChange: -1.57,
    exchange: "NSE",
    sourceRegulation: "SEBI SAST Reg 29",
    riskImpact: "BEARISH_DILUTION",
    rationale: "Partial promoter stake monetization via block window to private institutional funds to increase public float.",
  },

  // 3. PLEDGE INCREASE (HIGH GOVERNANCE RISK)
  {
    id: "act-pi-01",
    symbol: "VEDL",
    companyName: "Vedanta Limited",
    sector: "Metals & Mining",
    category: "PLEDGE_INCREASE",
    transactionDate: "2026-09-22",
    reportingDate: "2026-09-23",
    personName: "Finsider International Company Ltd / Vedanta Resources",
    personCategory: "Promoter Group",
    sharesCount: 185000000,
    transactionPriceInr: 450.0,
    transactionValueCr: 8325.0,
    stakePctBefore: 61.95,
    stakePctAfter: 61.95,
    stakePctChange: 0,
    pledgePctOfPromoterHolding: 74.8,
    pledgePctOfTotalEquity: 46.3,
    exchange: "BOTH",
    sourceRegulation: "SEBI SAST Reg 31 (Pledge)",
    riskImpact: "HIGH_GOVERNANCE_RISK",
    rationale: "Severe pledge increase: Promoter entity pledged an additional 18.5 Cr shares to international lenders as collateral for parent debt refinancing. Heightened margin call risk during volatility.",
  },
  {
    id: "act-pi-02",
    symbol: "GMRINFRA",
    companyName: "GMR Airports Infrastructure Limited",
    sector: "Infrastructure & Logistics",
    category: "PLEDGE_INCREASE",
    transactionDate: "2026-09-17",
    reportingDate: "2026-09-18",
    personName: "GMR Enterprises Private Limited",
    personCategory: "Promoter",
    sharesCount: 95000000,
    transactionPriceInr: 92.5,
    transactionValueCr: 878.75,
    stakePctBefore: 58.85,
    stakePctAfter: 58.85,
    stakePctChange: 0,
    pledgePctOfPromoterHolding: 48.5,
    pledgePctOfTotalEquity: 28.5,
    exchange: "NSE",
    sourceRegulation: "SEBI SAST Reg 31 (Pledge)",
    riskImpact: "HIGH_GOVERNANCE_RISK",
    rationale: "Promoter pledge increased to 48.5% of promoter holding to secure credit facilities for airport expansion programs.",
  },

  // 4. PLEDGE DECREASE (POSITIVE DELEVERAGING)
  {
    id: "act-pd-01",
    symbol: "ADANIPORTS",
    companyName: "Adani Ports and Special Economic Zone Ltd",
    sector: "Infrastructure & Logistics",
    category: "PLEDGE_DECREASE",
    transactionDate: "2026-09-25",
    reportingDate: "2026-09-26",
    personName: "Gautam S. Adani & Rajesh S. Adani (on behalf of S.B. Adani Family Trust)",
    personCategory: "Promoter Group",
    sharesCount: 38500000,
    transactionPriceInr: 1420.0,
    transactionValueCr: 5467.0,
    stakePctBefore: 65.89,
    stakePctAfter: 65.89,
    stakePctChange: 0,
    pledgePctOfPromoterHolding: 3.8,
    pledgePctOfTotalEquity: 2.5,
    exchange: "BOTH",
    sourceRegulation: "SEBI SAST Reg 31 (Pledge)",
    riskImpact: "POSITIVE_DELEVERAGING",
    rationale: "Major balance sheet de-risking: Promoter prepaid share-backed debt facilities, revoking pledge on 3.85 Cr equity shares. Encumbered holding reduced to negligible 3.8%.",
  },
  {
    id: "act-pd-02",
    symbol: "SWANENERGY",
    companyName: "Swan Energy Limited",
    sector: "Energy & Petrochemicals",
    category: "PLEDGE_DECREASE",
    transactionDate: "2026-09-14",
    reportingDate: "2026-09-15",
    personName: "Dave Family Trust & Promoter Associates",
    personCategory: "Promoter",
    sharesCount: 14500000,
    transactionPriceInr: 580.0,
    transactionValueCr: 841.0,
    stakePctBefore: 53.98,
    stakePctAfter: 53.98,
    stakePctChange: 0,
    pledgePctOfPromoterHolding: 11.2,
    pledgePctOfTotalEquity: 6.0,
    exchange: "NSE",
    sourceRegulation: "SEBI SAST Reg 31 (Pledge)",
    riskImpact: "POSITIVE_DELEVERAGING",
    rationale: "Promoter released substantial encumbrance following shipyard project milestone debt settlement, reducing pledge from 32% to 11.2%.",
  },

  // 5. INSIDER BUYING (DIRECTORS / KMP)
  {
    id: "act-ib-01",
    symbol: "INFY",
    companyName: "Infosys Limited",
    sector: "Information Technology",
    category: "INSIDER_BUYING",
    transactionDate: "2026-09-23",
    reportingDate: "2026-09-24",
    personName: "Jayesh Sanghrajka (CFO) & Executive Directors",
    personCategory: "Director / KMP",
    sharesCount: 42000,
    transactionPriceInr: 1880.0,
    transactionValueCr: 7.89,
    stakePctBefore: 0.02,
    stakePctAfter: 0.021,
    stakePctChange: 0.001,
    exchange: "NSE",
    sourceRegulation: "SEBI PIT Reg 7(2)",
    riskImpact: "BULLISH_CONVICTION",
    rationale: "CFO and senior management personnel purchased equity shares from the open market, demonstrating internal conviction ahead of Q2 earnings cycle.",
  },
  {
    id: "act-ib-02",
    symbol: "HDFCBANK",
    companyName: "HDFC Bank Limited",
    sector: "Financial Services",
    category: "INSIDER_BUYING",
    transactionDate: "2026-09-20",
    reportingDate: "2026-09-21",
    personName: "Kaizad Bharucha (Deputy Managing Director)",
    personCategory: "Director / KMP",
    sharesCount: 35000,
    transactionPriceInr: 1640.0,
    transactionValueCr: 5.74,
    stakePctBefore: 0.04,
    stakePctAfter: 0.041,
    stakePctChange: 0.001,
    exchange: "NSE",
    sourceRegulation: "SEBI PIT Reg 7(2)",
    riskImpact: "BULLISH_CONVICTION",
    rationale: "Deputy MD acquired shares on the open market following post-merger CD ratio normalization milestone.",
  },

  // 6. INSIDER SELLING
  {
    id: "act-is-01",
    symbol: "ZOMATO",
    companyName: "Zomato Limited",
    sector: "Consumer Discretionary & Retail",
    category: "INSIDER_SELLING",
    transactionDate: "2026-09-22",
    reportingDate: "2026-09-23",
    personName: "Key Executive Officers (ESOP Trust)",
    personCategory: "Director / KMP",
    sharesCount: 4200000,
    transactionPriceInr: 275.0,
    transactionValueCr: 115.5,
    stakePctBefore: 0.85,
    stakePctAfter: 0.80,
    stakePctChange: -0.05,
    exchange: "NSE",
    sourceRegulation: "SEBI PIT Reg 7(2)",
    riskImpact: "NEUTRAL_LIQUIDITY",
    rationale: "Vested ESOP exercise monetization by senior officers. High liquidity volume absorbed smoothly without price dislocation.",
  },
  {
    id: "act-is-02",
    symbol: "PERSISTENT",
    companyName: "Persistent Systems Limited",
    sector: "Information Technology",
    category: "INSIDER_SELLING",
    transactionDate: "2026-09-16",
    reportingDate: "2026-09-17",
    personName: "Executive Vice President (Engineering)",
    personCategory: "Director / KMP",
    sharesCount: 52000,
    transactionPriceInr: 5400.0,
    transactionValueCr: 28.08,
    stakePctBefore: 0.12,
    stakePctAfter: 0.08,
    stakePctChange: -0.04,
    exchange: "NSE",
    sourceRegulation: "SEBI PIT Reg 7(2)",
    riskImpact: "NEUTRAL_LIQUIDITY",
    rationale: "Routine ESOP exercise and post-vesting profit-taking following multi-quarter stock re-rating.",
  },

  // 7. LARGE SHAREHOLDER CHANGES (HNI / MARQUEE INVESTORS)
  {
    id: "act-ls-01",
    symbol: "ITC",
    companyName: "ITC Limited",
    sector: "Consumer Goods & FMCG",
    category: "LARGE_SHAREHOLDER_CHANGE",
    transactionDate: "2026-09-19",
    reportingDate: "2026-09-20",
    personName: "GQG Partners Emerging Markets Fund",
    personCategory: "Institutional / FII",
    sharesCount: 125000000,
    transactionPriceInr: 495.0,
    transactionValueCr: 6187.5,
    stakePctBefore: 2.15,
    stakePctAfter: 3.15,
    stakePctChange: 1.0,
    exchange: "NSE",
    sourceRegulation: "SEBI SAST Reg 29",
    riskImpact: "BULLISH_CONVICTION",
    rationale: "Rajiv Jain-led GQG Partners acquired an additional 1.0% stake in ITC via secondary transactions, citing robust hotel demerger and FMCG value accretion.",
  },
  {
    id: "act-ls-02",
    symbol: "FEDERALBNK",
    companyName: "The Federal Bank Limited",
    sector: "Financial Services",
    category: "LARGE_SHAREHOLDER_CHANGE",
    transactionDate: "2026-09-11",
    reportingDate: "2026-09-12",
    personName: "Rekha Rakesh Jhunjhunwala",
    personCategory: "Marquee HNI",
    sharesCount: 16500000,
    transactionPriceInr: 198.5,
    transactionValueCr: 327.5,
    stakePctBefore: 2.65,
    stakePctAfter: 3.32,
    stakePctChange: 0.67,
    exchange: "NSE",
    sourceRegulation: "SEBI SAST Reg 29",
    riskImpact: "BULLISH_CONVICTION",
    rationale: "Marquee investor estate expanded stake in Federal Bank following RBI approval for leadership transition and strong asset quality.",
  },

  // 8. BLOCK DEALS (>= 10 Cr Window)
  {
    id: "act-bd-01",
    symbol: "INDIGO",
    companyName: "InterGlobe Aviation Limited",
    sector: "Consumer Discretionary & Travel",
    category: "BLOCK_DEAL",
    transactionDate: "2026-09-24",
    reportingDate: "2026-09-24",
    personName: "Rakesh Gangwal & Chinkerpoo Family Trust (Promoter Co-Founder)",
    personCategory: "Promoter Group",
    sharesCount: 9200000,
    transactionPriceInr: 4780.0,
    transactionValueCr: 4397.6,
    stakePctBefore: 13.4,
    stakePctAfter: 11.0,
    stakePctChange: -2.4,
    exchange: "NSE",
    sourceRegulation: "NSE Block Window",
    riskImpact: "BEARISH_DILUTION",
    rationale: "Co-founder Rakesh Gangwal executed pre-announced partial stake sale via morning block window at a 1.5% discount to market, bought by Morgan Stanley & domestic mutual funds.",
  },
  {
    id: "act-bd-02",
    symbol: "PAYTM",
    companyName: "One97 Communications Limited",
    sector: "Financial Technology",
    category: "BLOCK_DEAL",
    transactionDate: "2026-09-18",
    reportingDate: "2026-09-18",
    personName: "Antfin (Netherlands) Holding B.V.",
    personCategory: "Large Shareholder",
    sharesCount: 22000000,
    transactionPriceInr: 685.0,
    transactionValueCr: 1507.0,
    stakePctBefore: 9.8,
    stakePctAfter: 6.3,
    stakePctChange: -3.5,
    exchange: "NSE",
    sourceRegulation: "NSE Block Window",
    riskImpact: "NEUTRAL_LIQUIDITY",
    rationale: "Chinese sponsor Antfin continued systematic stake reduction via designated block deal window, eliminating overhang as domestic mutual funds absorbed the supply.",
  },

  // 9. BULK DEALS (> 0.5% of Equity)
  {
    id: "act-bk-01",
    symbol: "SUZLON",
    companyName: "Suzlon Energy Limited",
    sector: "Renewable Energy & Power",
    category: "BULK_DEAL",
    transactionDate: "2026-09-23",
    reportingDate: "2026-09-23",
    personName: "BlackRock Global Emerging Markets Growth Fund",
    personCategory: "Institutional / FII",
    sharesCount: 75000000,
    transactionPriceInr: 82.5,
    transactionValueCr: 618.75,
    stakePctBefore: 0.0,
    stakePctAfter: 0.55,
    stakePctChange: 0.55,
    exchange: "NSE",
    sourceRegulation: "NSE Bulk Window",
    riskImpact: "BULLISH_CONVICTION",
    rationale: "Institutional bulk purchase surpassing 0.5% equity threshold on regular order book as wind turbine order book hit multi-year highs.",
  },
  {
    id: "act-bk-02",
    symbol: "DIXON",
    companyName: "Dixon Technologies (India) Ltd",
    sector: "Consumer Electronics & EMS",
    category: "BULK_DEAL",
    transactionDate: "2026-09-19",
    reportingDate: "2026-09-19",
    personName: "Nomura India Investment Fund Mother Fund",
    personCategory: "Institutional / FII",
    sharesCount: 380000,
    transactionPriceInr: 12450.0,
    transactionValueCr: 473.1,
    stakePctBefore: 0.15,
    stakePctAfter: 0.78,
    stakePctChange: 0.63,
    exchange: "NSE",
    sourceRegulation: "NSE Bulk Window",
    riskImpact: "BULLISH_CONVICTION",
    rationale: "Bulk acquisition driven by production-linked incentive (PLI) smartphone ramp-up and export order wins.",
  }
];

export function getAllPromoterActivities(): PromoterActivityRecord[] {
  return PROMOTER_ACTIVITIES_STORE;
}

export function filterPromoterActivities(filters?: {
  category?: string;
  sector?: string;
  symbol?: string;
  riskImpact?: string;
  search?: string;
}): PromoterActivityRecord[] {
  if (!filters) return PROMOTER_ACTIVITIES_STORE;

  return PROMOTER_ACTIVITIES_STORE.filter((item) => {
    if (filters.category && filters.category !== "ALL" && item.category !== filters.category) {
      return false;
    }
    if (filters.sector && filters.sector !== "ALL" && item.sector !== filters.sector) {
      return false;
    }
    if (filters.symbol && filters.symbol.trim() !== "" && item.symbol.toUpperCase() !== filters.symbol.toUpperCase()) {
      return false;
    }
    if (filters.riskImpact && filters.riskImpact !== "ALL" && item.riskImpact !== filters.riskImpact) {
      return false;
    }
    if (filters.search && filters.search.trim() !== "") {
      const q = filters.search.toLowerCase().trim();
      const match =
        item.symbol.toLowerCase().includes(q) ||
        item.companyName.toLowerCase().includes(q) ||
        item.personName.toLowerCase().includes(q) ||
        item.sector.toLowerCase().includes(q) ||
        item.rationale.toLowerCase().includes(q);
      if (!match) return false;
    }
    return true;
  });
}

export function getPromoterActivitiesBySymbol(symbol: string): PromoterActivityRecord[] {
  const s = symbol.toUpperCase().trim();
  return PROMOTER_ACTIVITIES_STORE.filter((a) => a.symbol.toUpperCase() === s);
}
