import type { Holding, PortfolioSettings } from "@/lib/my-portfolio/types";

export const DEFAULT_PORTFOLIO_SETTINGS: PortfolioSettings = {
  name: "MI Institutional Book",
  benchmark: "NIFTY50",
  baseCurrency: "INR",
};

export const REALISTIC_DEFAULT_HOLDINGS: Holding[] = [
  {
    id: "h-rel",
    market: "IN",
    symbol: "RELIANCE",
    instrumentKey: "NSE_EQ|INE002A01018",
    name: "Reliance Industries Ltd",
    sector: "Energy",
    currency: "INR",
    shares: 200,
    avgCost: 2860.0,
    addedAt: "2024-01-15",
  },
  {
    id: "h-tcs",
    market: "IN",
    symbol: "TCS",
    instrumentKey: "NSE_EQ|INE467B01029",
    name: "Tata Consultancy Services Ltd",
    sector: "Technology",
    currency: "INR",
    shares: 120,
    avgCost: 3880.0,
    addedAt: "2024-02-10",
  },
  {
    id: "h-hdfc",
    market: "IN",
    symbol: "HDFCBANK",
    instrumentKey: "NSE_EQ|INE040A01034",
    name: "HDFC Bank Ltd",
    sector: "Financials",
    currency: "INR",
    shares: 350,
    avgCost: 1610.0,
    addedAt: "2024-01-20",
  },
  {
    id: "h-infy",
    market: "IN",
    symbol: "INFY",
    instrumentKey: "NSE_EQ|INE009A01021",
    name: "Infosys Ltd",
    sector: "Technology",
    currency: "INR",
    shares: 250,
    avgCost: 1740.0,
    addedAt: "2024-03-05",
  },
  {
    id: "h-bharti",
    market: "IN",
    symbol: "BHARTIARTL",
    instrumentKey: "NSE_EQ|INE397D01024",
    name: "Bharti Airtel Ltd",
    sector: "Communication",
    currency: "INR",
    shares: 200,
    avgCost: 1420.0,
    addedAt: "2024-04-12",
  },
  {
    id: "h-aapl",
    market: "US",
    symbol: "AAPL",
    instrumentKey: null,
    name: "Apple Inc",
    sector: "Technology",
    currency: "USD",
    shares: 25,
    avgCost: 215.0,
    addedAt: "2024-02-18",
  },
  {
    id: "h-msft",
    market: "US",
    symbol: "MSFT",
    instrumentKey: null,
    name: "Microsoft Corp",
    sector: "Technology",
    currency: "USD",
    shares: 15,
    avgCost: 410.0,
    addedAt: "2024-03-01",
  },
];
