export type GlossaryEntry = {
  id: string;
  label: string;
  definition: string;
  formula: string;
  example: string;
  why: string;
  /** Section reference in docs/market_intelligence_metrics_specification.md */
  specSection?: string;
};

export const GLOSSARY: Record<string, GlossaryEntry> = {
  nav: {
    id: "nav",
    label: "NAV / AUM",
    definition: "Net Asset Value — the total mark-to-market value of every holding plus cash, in your base currency (INR).",
    formula: "NAV = Σ(shares_i × last price_i, converted to INR) + cash",
    example: "10 RELIANCE @ ₹2,900 + 5 AAPL @ $230 (₹19,500/$) = ₹29,000 + ₹22,42,500 ≈ ₹22,71,500 NAV.",
    why: "Everything else — return, risk, concentration — is measured against this one number.",
  },
  absoluteReturn: {
    id: "absoluteReturn",
    label: "Absolute Return",
    definition: "Total cumulative return of the portfolio since you first added a holding, before comparing to any benchmark.",
    formula: "R_abs = (P_T − P_0) / P_0 = Π(1 + R_{p,t}) − 1",
    specSection: "§1.1",
    example: "Portfolio started at ₹10,00,000 and is now ₹11,80,000 → Absolute Return = +18.0%.",
    why: "The simplest \"did I make money\" number — everything else refines this by adjusting for risk or comparing to a yardstick.",
  },
  cagr: {
    id: "cagr",
    label: "CAGR",
    definition: "Compound Annual Growth Rate — the steady annual growth rate that would take you from inception NAV to today's NAV.",
    formula: "CAGR = (P_T/P_0)^(1/Y) − 1, Y = calendar years (Δdays/365.25); suppressed if Y < 1/12",
    specSection: "§1.2",
    example: "₹10,00,000 → ₹12,10,000 over 2 years → CAGR = (1.21)^(1/2) − 1 ≈ 10%.",
    why: "Makes returns of different time periods comparable — an 18% return over 3 years is very different from 18% over 3 months.",
  },
  twr: {
    id: "twr",
    label: "TWR",
    definition: "Time-Weighted Return — links together each day's return, which removes the distortion caused by when you added money.",
    formula: "TWR = Π(1 + daily return_t) − 1, chained day over day",
    example: "You add a large holding right before a rally — TWR isolates the *strategy's* return from the lucky timing of your cash addition.",
    why: "The standard way to judge how good your stock picks/allocation were, independent of your deposit timing.",
  },
  mwrIrr: {
    id: "mwrIrr",
    label: "MWR / IRR",
    definition: "Money-Weighted Return (Internal Rate of Return) — the discount rate that makes the present value of every cash addition equal to today's NAV.",
    formula: "0 = Σ CF_t / (1+IRR)^t  (solved numerically; CF = each holding purchase as an outflow, NAV_today as the final inflow)",
    example: "You added ₹5L then, 6 months later, another ₹5L right before a rally — IRR is higher than TWR because your *timing* helped.",
    why: "Unlike TWR, this reflects how much money you actually made given *when* you added it — the number that matches your bank account.",
  },
  rollingReturn: {
    id: "rollingReturn",
    label: "Rolling Return",
    definition: "Return over a fixed trailing window (e.g. the last 3 months), recomputed for every day — shows how consistent performance has been.",
    formula: "Rolling Return(t) = NAV_t / NAV_(t−window) − 1",
    example: "Trailing-3-month return recalculated every trading day for the past year shows whether gains were steady or a single lucky quarter.",
    why: "A great since-inception number can hide one lucky quarter — rolling returns expose consistency (or the lack of it).",
  },
  activeReturn: {
    id: "activeReturn",
    label: "Active Return",
    definition: "How much your portfolio returned above (or below) the benchmark over the same period.",
    formula: "Active Return = Portfolio Return − Benchmark Return",
    example: "Portfolio +18%, NIFTY 50 +14% → Active Return = +4%.",
    why: "The single number that answers \"was picking my own stocks worth it versus just buying the index?\"",
  },
  benchmarkReturn: {
    id: "benchmarkReturn",
    label: "Benchmark Return",
    definition: "The return of your chosen yardstick index (NIFTY 50 / S&P 500 / NASDAQ 100) over the same period as your portfolio.",
    formula: "Benchmark Return = (Index_today / Index_inception) − 1",
    example: "NIFTY 50 moved from 22,000 to 25,080 → Benchmark Return = +14%.",
    why: "Without a yardstick, a 14% gain looks great — until you learn the market did 20%.",
  },
  sharpe: {
    id: "sharpe",
    label: "Sharpe Ratio",
    definition: "Return earned per unit of total risk taken (volatility), above the risk-free rate.",
    formula: "Sharpe = (Portfolio Return − Risk-free Rate) / Volatility",
    example: "12% return, 4.5% risk-free rate, 15% volatility → Sharpe = (12−4.5)/15 = 0.5.",
    why: "Two portfolios can have the same return with very different bumpiness — Sharpe tells you which one earned it more efficiently. Above 1 is good, above 2 is excellent.",
  },
  treynor: {
    id: "treynor",
    label: "Treynor Ratio",
    definition: "Like Sharpe, but divides by market risk (beta) instead of total volatility — isolates reward for *systematic* risk only.",
    formula: "Treynor = (Portfolio Return − Risk-free Rate) / Beta",
    example: "12% return, 4.5% risk-free, beta 0.9 → Treynor = 7.5/0.9 ≈ 8.3%.",
    why: "Useful when a portfolio is well-diversified (so stock-specific risk is already washed out) and you only care about market-timing skill.",
  },
  sortino: {
    id: "sortino",
    label: "Sortino Ratio",
    definition: "Like Sharpe, but only penalizes downside volatility — upside swings don't count against you.",
    formula: "Sortino = (Portfolio Return − Risk-free Rate) / Downside Deviation",
    example: "A portfolio with big up-days and small down-days can have a much higher Sortino than Sharpe, since Sharpe punishes both equally.",
    why: "Investors don't mind upside volatility — Sortino measures the risk that actually worries you.",
  },
  jensensAlpha: {
    id: "jensensAlpha",
    label: "Jensen's Alpha",
    definition: "The CAPM-model \"excess\" return your portfolio delivered beyond what its market risk (beta) alone would predict.",
    formula: "Alpha = Portfolio Return − [Risk-free + Beta × (Benchmark Return − Risk-free)]",
    example: "Beta 0.9, benchmark returned 14%, risk-free 4.5% → expected return = 4.5 + 0.9×9.5 = 13.05%. If you actually made 18%, Alpha = +4.95%.",
    why: "Separates genuine stock-picking skill from simply taking on more or less market risk than the benchmark.",
  },
  informationRatio: {
    id: "informationRatio",
    label: "Information Ratio",
    definition: "Active return earned per unit of active risk (tracking error) taken versus the benchmark.",
    formula: "Information Ratio = Active Return / Tracking Error",
    example: "+4% active return with 8% tracking error → Information Ratio = 0.5.",
    why: "Tells you whether your bets away from the index are being rewarded consistently, or just adding noise.",
  },
  calmar: {
    id: "calmar",
    label: "Calmar Ratio",
    definition: "Annualized return divided by the worst peak-to-trough loss you experienced (Maximum Drawdown).",
    formula: "Calmar = CAGR / |Maximum Drawdown|",
    example: "CAGR 15%, Max Drawdown −20% → Calmar = 15/20 = 0.75.",
    why: "Rewards portfolios that grow steadily without brutal crashes — popular with investors who can't stomach deep drawdowns.",
  },
  sterling: {
    id: "sterling",
    label: "Sterling Ratio",
    definition: "Like Calmar, but divides by the *average* of your worst few drawdowns instead of just the single worst one — less sensitive to one outlier event.",
    formula: "Sterling ≈ CAGR / (average of the 3 largest drawdowns)",
    example: "If your 3 worst drawdowns averaged −12% instead of one −20% outlier, Sterling gives a fairer risk-adjusted picture than Calmar alone.",
    why: "One freak crash shouldn't define your whole risk profile — Sterling smooths that out.",
  },
  burke: {
    id: "burke",
    label: "Burke Ratio",
    definition: "Similar intent to Calmar/Sterling, but penalizes the *square* of every drawdown, so it's most sensitive to a few large drawdowns rather than many small dips.",
    formula: "Burke = (Portfolio Return − Risk-free) / √(Σ drawdown_i²)",
    example: "Many small −2% dips barely move Burke, but a single −25% drawdown dominates the denominator.",
    why: "A middle ground between Calmar (only cares about the single worst event) and volatility-based ratios (treat every wiggle equally).",
  },
  omega: {
    id: "omega",
    label: "Omega Ratio",
    definition: "The ratio of total gains to total losses relative to a threshold (usually 0%) — uses the whole return distribution, not just its average and spread.",
    formula: "Omega = Σ(gains above threshold) / Σ(losses below threshold)",
    example: "Omega of 1.8 means your portfolio's cumulative up-moves are 1.8× the size of its cumulative down-moves.",
    why: "Sharpe assumes returns are symmetric (bell-curve); Omega captures skewness and fat tails that Sharpe misses.",
  },
  kappa: {
    id: "kappa",
    label: "Kappa Ratio",
    definition: "A generalization of Sortino that penalizes larger downside deviations disproportionately more (using the 3rd power instead of the 2nd).",
    formula: "Kappa₃ = (Return − threshold) / (downside deviation raised to the 3rd moment)^(1/3)",
    example: "Two portfolios with the same Sortino can have different Kappa if one has occasional severe down-days versus many mild ones.",
    why: "Flags portfolios prone to rare-but-severe losses even when their average downside risk looks tame.",
  },
  m2: {
    id: "m2",
    label: "M² (Modigliani)",
    definition: "Re-expresses Sharpe Ratio in percentage-return terms by scaling your portfolio to the benchmark's volatility level, making it directly comparable to the benchmark's return.",
    formula: "M² = Risk-free Rate + Sharpe Ratio × Benchmark Volatility",
    example: "If M² = 16% and the benchmark returned 14%, your risk-adjusted performance \"beat the index\" by 2 percentage points, in return terms.",
    why: "Sharpe is a dimensionless number that's hard to explain to a non-technical investor; M² translates it back into \"% return you'd expect at the market's risk level.\"",
  },
  appraisal: {
    id: "appraisal",
    label: "Appraisal Ratio",
    definition: "Jensen's Alpha divided by the portfolio's stock-specific (idiosyncratic) risk — the risk that isn't explained by the market.",
    formula: "Appraisal Ratio = Jensen's Alpha / Specific Risk, where Specific Risk = √(Volatility² − Beta² × Benchmark Volatility²)",
    example: "Two managers with the same Alpha, but one achieves it while taking far less stock-specific risk — that manager has the higher Appraisal Ratio.",
    why: "Tells you whether outperformance came from a few concentrated, risky bets or was earned efficiently.",
  },
  beta: {
    id: "beta",
    label: "Beta",
    definition: "How sensitive your portfolio's daily moves are to the benchmark's moves.",
    formula: "Beta = Covariance(portfolio returns, benchmark returns) / Variance(benchmark returns)",
    example: "Beta of 1.2 means when NIFTY 50 moves +1%, your portfolio has historically moved about +1.2%.",
    why: "Tells you how much market risk you're carrying — a beta well above 1 means bigger swings in both directions.",
  },
  alpha: {
    id: "alpha",
    label: "Alpha",
    definition: "Annualized excess return versus what your portfolio's market risk (beta) alone would predict — same concept as Jensen's Alpha.",
    formula: "Alpha = Portfolio Return − [Risk-free + Beta × (Benchmark Return − Risk-free)], annualized",
    example: "A consistently positive alpha across market cycles is the hallmark of genuine stock-picking skill (or good luck).",
    why: "The headline number for \"did my choices add value beyond just taking on market risk?\"",
  },
  volatility: {
    id: "volatility",
    label: "Volatility",
    definition: "The annualized standard deviation of daily portfolio returns — how much your NAV swings around its average.",
    formula: "Volatility = stdev(daily returns) × √252",
    example: "A daily stdev of 1.2% annualizes to roughly 19% volatility.",
    why: "The most common measure of \"risk\" — higher volatility means a bumpier ride, for better or worse.",
  },
  var: {
    id: "var",
    label: "VaR (Value at Risk)",
    definition: "The loss level you'd expect to not exceed on 95% of days, based on your historical return distribution.",
    formula: "VaR₉₅ = 5th percentile of historical daily returns × current NAV",
    example: "A 1-day 95% VaR of ₹45,000 means on 95 out of 100 days, you shouldn't expect to lose more than that in a single day.",
    why: "A concrete, NAV-denominated answer to \"how bad could a normal-ish bad day be?\"",
  },
  cvar: {
    id: "cvar",
    label: "CVaR / Expected Shortfall",
    definition: "The *average* loss on the worst 5% of days — goes further than VaR by describing how bad the tail actually is, not just where it starts.",
    formula: "CVaR₉₅ = mean(daily returns below the 5th percentile) × current NAV",
    example: "If VaR₉₅ is ₹45,000 but CVaR₉₅ is ₹95,000, your worst days are far worse than the VaR threshold suggests.",
    why: "VaR tells you the cutoff; CVaR tells you how painful things get once you're past it — often the more honest risk number.",
  },
  trackingError: {
    id: "trackingError",
    label: "Tracking Error",
    definition: "The annualized volatility of the *difference* between your daily returns and the benchmark's — how closely you track the index.",
    formula: "Tracking Error = stdev(portfolio return − benchmark return) × √252",
    example: "A tracking error of 3% means your daily active bets are fairly tame; 15% means you're running a very different book from the index.",
    why: "Quantifies how much you've deviated from the benchmark — the risk you're taking to try to beat it.",
  },
  downsideDeviation: {
    id: "downsideDeviation",
    label: "Downside Deviation",
    definition: "Like volatility, but only counts days with negative (or below-threshold) returns.",
    formula: "Downside Deviation = stdev(returns where return < 0) × √252",
    example: "A portfolio with frequent small gains and rare sharp losses will show low volatility but a much higher downside deviation.",
    why: "Captures the risk investors actually fear — losing money — without being diluted by \"good\" volatility (upside swings).",
  },
  maxDrawdown: {
    id: "maxDrawdown",
    label: "Maximum Drawdown",
    definition: "The largest peak-to-trough decline your NAV has experienced.",
    formula: "Max Drawdown = min over time of (NAV_t / running peak NAV − 1)",
    example: "NAV peaked at ₹12,00,000, later fell to ₹9,60,000 before recovering → Max Drawdown = −20%.",
    why: "The single best answer to \"what's the worst it's gotten so far\" — a key gut-check for how much pain you can tolerate.",
  },
  avgDrawdown: {
    id: "avgDrawdown",
    label: "Average Drawdown",
    definition: "The average size of every drawdown episode (not just the worst one) over the period.",
    formula: "Average Drawdown = mean of (NAV_t / running peak − 1) across all days currently below a prior peak",
    example: "Even if your Max Drawdown was a scary −25%, an Average Drawdown of −4% shows most dips are mild.",
    why: "Prevents one bad event from making the whole strategy look riskier than it typically is day-to-day.",
  },
  drawdownDuration: {
    id: "drawdownDuration",
    label: "Drawdown Duration",
    definition: "How many days the portfolio spent below its prior peak, for its longest drawdown episode.",
    formula: "Drawdown Duration = trading days from the peak to the point the NAV fully recovers to that peak (or today, if still underwater)",
    example: "NAV peaked on day 40, didn't reclaim that high until day 130 → Drawdown Duration = 90 days.",
    why: "A deep-but-brief drawdown feels very different from a shallow-but-endless one — this captures the time cost of losses.",
  },
  recoveryPeriod: {
    id: "recoveryPeriod",
    label: "Recovery Period",
    definition: "How many days it took (or is taking) to climb back to the prior peak after the Maximum Drawdown.",
    formula: "Recovery Period = days from the Max Drawdown's trough back to the NAV level at its preceding peak",
    example: "If the portfolio is still below its pre-drawdown peak, this shows \"ongoing\" rather than a fixed number.",
    why: "Tells you not just how deep the worst loss was, but how long you were underwater because of it.",
  },
  recoveryFactor: {
    id: "recoveryFactor",
    label: "Recovery Factor",
    definition: "Total return earned relative to the worst drawdown suffered along the way.",
    formula: "Recovery Factor = Absolute Return / |Maximum Drawdown|",
    example: "+40% total return with a −20% max drawdown → Recovery Factor = 2.0.",
    why: "A high number means your gains have comfortably outpaced your worst setback; a low one means you're barely ahead of your own worst drop.",
  },
  activeShare: {
    id: "activeShare",
    label: "Active Share",
    definition: "How different your holdings' weights are from the benchmark's constituent weights — 0% means you own the index exactly, 100% means zero overlap.",
    formula: "Active Share = ½ × Σ |portfolio weight_i − benchmark weight_i| across all names in either",
    example: "If you hold 60% in 5 stocks the index barely holds, Active Share will be high even if your total return tracks the index closely.",
    why: "Shows how much genuine stock-picking is happening versus closet-indexing. Uses a periodically-updated snapshot of index weights (not live), so treat it as approximate.",
  },
  upsideCapture: {
    id: "upsideCapture",
    label: "Upside Capture",
    definition: "What percentage of the benchmark's gains your portfolio captured, measured only on days/periods the benchmark was up.",
    formula: "Upside Capture = (Portfolio return in up-periods) / (Benchmark return in up-periods)",
    example: "110% upside capture means when the market rises, you tend to rise slightly more.",
    why: "A portfolio can have a great Sharpe Ratio while still lagging badly in strong bull markets — this exposes that.",
  },
  downsideCapture: {
    id: "downsideCapture",
    label: "Downside Capture",
    definition: "What percentage of the benchmark's losses your portfolio experienced, measured only on days/periods the benchmark was down.",
    formula: "Downside Capture = (Portfolio return in down-periods) / (Benchmark return in down-periods)",
    example: "80% downside capture means when the market falls 10%, your portfolio has tended to fall only about 8%.",
    why: "The ideal profile is high upside capture and low downside capture — this pair of metrics shows whether that's happening.",
  },
  battingAverage: {
    id: "battingAverage",
    label: "Batting Average",
    definition: "The percentage of periods (days) where your portfolio outperformed the benchmark.",
    formula: "Batting Average = (number of days portfolio return > benchmark return) / (total days)",
    example: "A batting average of 55% means you beat the index on just over half of all trading days.",
    why: "Consistency check — you can have a great total return from a few huge days while losing most days; this shows which pattern you have.",
  },
  concentration: {
    id: "concentration",
    label: "Top-N Concentration",
    definition: "The share of your total NAV held in your largest few positions (commonly top 5 or top 10).",
    formula: "Top-10 Concentration = Σ(market value of your 10 largest holdings) / NAV",
    example: "If your top 10 holdings are 70% of NAV, the portfolio's fate rides heavily on those names.",
    why: "High concentration can drive outperformance — or a much rougher ride if a top holding stumbles.",
  },
  hhi: {
    id: "hhi",
    label: "HHI",
    definition: "Herfindahl-Hirschman Index — a standard concentration measure that squares each position's weight before summing, so large positions count disproportionately more.",
    formula: "HHI = Σ (weight_i)²",
    example: "20 equally-weighted 5% positions give HHI = 20×(0.05)² = 0.05. One 50% position plus 20 tiny ones gives HHI ≈ 0.25 — five times more concentrated.",
    why: "Catches concentration risk that a simple \"number of holdings\" count would miss.",
  },
  effectiveHoldings: {
    id: "effectiveHoldings",
    label: "Effective Holdings",
    definition: "The number of *equally-weighted* positions that would produce the same concentration (HHI) as your actual portfolio.",
    formula: "Effective Holdings = 1 / HHI",
    example: "You technically own 20 stocks, but if 3 of them dominate the weight, Effective Holdings might work out to only ~6.",
    why: "A more honest \"how diversified am I really\" number than just counting tickers.",
  },
  grossExposure: {
    id: "grossExposure",
    label: "Gross Exposure",
    definition: "Total market value of all positions (long + short) as a percentage of NAV. Since this tracker only supports long positions, it equals Net Exposure here.",
    formula: "Gross Exposure = Σ|market value of each position| / NAV",
    example: "₹18,00,000 in holdings on a ₹20,00,000 NAV → Gross Exposure = 90%.",
    why: "Shows how fully invested you are — the gap to 100% is sitting in cash.",
  },
  netExposure: {
    id: "netExposure",
    label: "Net Exposure",
    definition: "Long value minus short value, as a percentage of NAV — your actual directional market exposure.",
    formula: "Net Exposure = (Long value − Short value) / NAV",
    example: "This tracker only supports long adds, so Net Exposure equals your equity weight (1 − Cash %).",
    why: "The number that tells you how much of your capital actually has market risk attached.",
  },
  leverage: {
    id: "leverage",
    label: "Leverage",
    definition: "Gross Exposure relative to NAV — a value over 100% would mean the portfolio is using borrowed capital.",
    formula: "Leverage = Gross Exposure / NAV",
    example: "This tracker never borrows or shorts, so leverage is always 1.0x or less.",
    why: "Leverage magnifies both gains and losses — this confirms whether any is being used.",
  },
  cashPct: {
    id: "cashPct",
    label: "Cash %",
    definition: "The share of NAV sitting uninvested, since this tracker doesn't model a dedicated cash balance — shown as the residual after all holdings.",
    formula: "Cash % = 1 − (Σ market value of holdings / NAV)",
    example: "If every rupee you've added is deployed into a holding, Cash % will show close to 0%.",
    why: "Cash is a real (if passive) allocation decision — this tracks how much dry powder you're sitting on.",
  },
  assetAllocation: {
    id: "assetAllocation",
    label: "Asset Allocation (Attribution)",
    definition: "How much of your active return came from *how you split capital* across asset buckets (e.g. India equity vs US equity vs cash) rather than from picking specific winners within each bucket.",
    formula: "Allocation effect (bucket) = (portfolio weight − benchmark weight) × (benchmark bucket return − total benchmark return)",
    example: "Overweighting US equities right before a US rally shows up here as a positive allocation effect, even before looking at which US stocks you picked.",
    why: "Separates \"I called the right market/asset class\" skill from \"I picked the right stock within it.\"",
  },
  securitySelection: {
    id: "securitySelection",
    label: "Security Selection (Attribution)",
    definition: "How much of your active return came from picking specific winners/losers within an allocation, versus the allocation decision itself.",
    formula: "Selection effect = portfolio weight in bucket × (bucket's actual return − bucket's benchmark return)",
    example: "You had the same India/US split as the benchmark, but your specific India picks beat the India benchmark — that shows up entirely here.",
    why: "The purest \"was I a good stock-picker\" number, isolated from asset-allocation calls.",
  },
  sectorContribution: {
    id: "sectorContribution",
    label: "Sector Contribution",
    definition: "How much each sector (Technology, Banking, Energy, ...) added to or subtracted from your total return.",
    formula: "Sector Contribution = Σ(weight_i × return_i) for all holdings in that sector",
    example: "A 30%-weighted Technology sleeve that returned 20% contributed roughly +6 percentage points to your total return.",
    why: "Shows where your return actually came from at a glance — useful for spotting unintended sector bets.",
  },
  stockContribution: {
    id: "stockContribution",
    label: "Stock Contribution",
    definition: "How much a single holding added to or subtracted from your total portfolio return.",
    formula: "Stock Contribution = holding's portfolio weight × holding's own return",
    example: "A 10%-weighted stock that doubled contributed +10 percentage points to your total return, even if every other holding was flat.",
    why: "The most granular attribution view — tells you exactly which picks are doing the work.",
  },
  factorContribution: {
    id: "factorContribution",
    label: "Factor Contribution",
    definition: "How much of your return can be explained by exposure to broad style factors (Value, Growth, Momentum, etc.) rather than stock-specific effects.",
    formula: "Factor Contribution ≈ Σ(factor exposure × factor's realized return) for each style factor",
    example: "If Momentum had a strong year and your portfolio leaned into high-momentum names, this shows up as a positive Momentum contribution.",
    why: "Helps you understand whether your return came from a style tilt that could reverse, not just individual stock skill.",
  },
  currencyContribution: {
    id: "currencyContribution",
    label: "Currency Contribution",
    definition: "How much of your return (in INR) came purely from the Rupee weakening or strengthening against foreign holdings' currencies, holding local returns constant.",
    formula: "Currency Contribution = weight in foreign-currency holdings × (% change in USD/INR over the period)",
    example: "Your US stocks were flat in USD, but the Rupee weakened 3% against the Dollar over the period — that 3% shows up here.",
    why: "Especially relevant for a mixed India/US book — separates \"the stock moved\" from \"the currency moved.\"",
  },
  factorValue: {
    id: "factorValue",
    label: "Factor: Value",
    definition: "Exposure to cheaply-priced stocks, proxied here by each holding's earnings yield (inverse of P/E) where that data is available.",
    formula: "Value exposure ≈ weighted-average (1 / trailing P/E) across holdings with known P/E",
    example: "A portfolio full of low-P/E banks and energy names will show a high Value exposure; high-P/E growth names show low/negative.",
    why: "Value has historically been a persistent, well-documented driver of long-run returns — worth knowing your tilt.",
  },
  factorGrowth: {
    id: "factorGrowth",
    label: "Factor: Growth",
    definition: "Exposure to fast-growing-earnings/revenue companies.",
    formula: "Would require multi-year revenue/earnings growth history per holding.",
    example: "—",
    why: "A standard factor-model dimension, shown for completeness alongside the others.",
  },
  factorMomentum: {
    id: "factorMomentum",
    label: "Factor: Momentum",
    definition: "Exposure to stocks that have been rising strongly over the trailing 12 months (excluding the most recent month), a well-documented persistence effect.",
    formula: "Momentum exposure ≈ weighted-average 12-month-minus-1-month trailing return across holdings",
    example: "A portfolio full of names up 40%+ over the past year (excluding the last month) has high positive Momentum exposure.",
    why: "Momentum tends to persist over medium horizons — high exposure means part of your return depends on that trend continuing.",
  },
  factorQuality: {
    id: "factorQuality",
    label: "Factor: Quality",
    definition: "Exposure to financially healthy companies (high profitability, low debt).",
    formula: "Would require balance-sheet fundamentals (ROE, debt/equity) per holding.",
    example: "—",
    why: "A standard factor-model dimension, shown for completeness alongside the others.",
  },
  factorSize: {
    id: "factorSize",
    label: "Factor: Size",
    definition: "Exposure to smaller-market-cap companies versus mega-caps, proxied using market cap where available.",
    formula: "Size exposure ≈ weighted-average of (−log market cap) across holdings with known market cap, normalized",
    example: "A portfolio of small/mid-caps shows positive Size exposure; a portfolio of mega-caps (Reliance, Apple) shows negative.",
    why: "Smaller companies have historically carried a different risk/return profile than mega-caps — useful to know your tilt.",
  },
  factorLowVol: {
    id: "factorLowVol",
    label: "Factor: Low Volatility",
    definition: "Exposure to historically calmer stocks versus more volatile ones.",
    formula: "Low-Vol exposure ≈ weighted-average of (−realized volatility) across holdings, normalized",
    example: "A portfolio of steady FMCG/utility names scores high on Low-Vol; a portfolio of small-cap momentum names scores low.",
    why: "Counterintuitively, historically lower-volatility stocks haven't given up much return — a useful factor to track deliberately.",
  },
  factorMarket: {
    id: "factorMarket",
    label: "Factor: Market",
    definition: "Overall sensitivity to the broad market — identical to Beta.",
    formula: "Market exposure = Beta (see Beta above)",
    example: "See Beta.",
    why: "Included in the factor breakdown because it's the single largest driver of most portfolios' returns.",
  },
  turnover: {
    id: "turnover",
    label: "Portfolio Turnover",
    definition: "How much of the portfolio has been bought/sold (added/removed) over the past year, annualized.",
    formula: "Turnover = min(total buys, total sells) / average NAV, annualized",
    example: "₹5,00,000 bought and ₹3,00,000 sold against a ₹20,00,000 average NAV over the year → Turnover = 15%.",
    why: "Low turnover suggests a buy-and-hold approach; high turnover suggests active trading — useful context for the other numbers.",
  },
  bidAskSpread: {
    id: "bidAskSpread",
    label: "Bid-Ask Spread",
    definition: "The live gap between the best buy and best sell price for a holding — a direct cost of trading it.",
    formula: "Spread % = (Ask − Bid) / Mid price",
    example: "Bid ₹1,499.50 / Ask ₹1,500.50 → Spread ≈ 0.07%.",
    why: "Wider spreads mean it's more expensive to enter/exit a position — relevant to how tradeable a holding really is.",
  },
  slippage: {
    id: "slippage",
    label: "Slippage",
    definition: "The difference between the price you intended to trade at and the price you actually got filled at.",
    formula: "Slippage = Fill Price − Decision Price",
    example: "You decide to buy at ₹1,500, but by the time the order fills the price is ₹1,504 — that's ₹4 of slippage per share.",
    why: "A real execution cost — but this tracker records holdings you've added, not live order execution, so there's no fill data to measure it from.",
  },
  implementationShortfall: {
    id: "implementationShortfall",
    label: "Implementation Shortfall",
    definition: "The total gap between a paper portfolio's theoretical return and what you actually achieved after real-world trading costs and delays.",
    formula: "Implementation Shortfall = Paper Return − Actual Return (including commissions, spread, slippage, delay)",
    example: "A backtest shows +12%, but after real trading frictions your actual result was +10.5% — the 1.5-point gap is the shortfall.",
    why: "The most complete measure of \"how much did the mechanics of trading cost me\" — but it requires a real order blotter, which this tracker doesn't have.",
  },
  daysToLiquidate: {
    id: "daysToLiquidate",
    label: "Days to Liquidate",
    definition: "An estimate of how many trading days it would take to exit a position without moving its price too much, based on typical daily trading volume.",
    formula: "Days to Liquidate ≈ Position Shares / (Average Daily Volume × max participation rate, typically 20%)",
    example: "10,000 shares held, average daily volume 200,000, 20% max participation → 10,000 / (200,000 × 0.20) = 0.25 days.",
    why: "A large position in a thinly-traded stock can be much harder to exit than its dollar value suggests.",
  },
  positionAdv: {
    id: "positionAdv",
    label: "Position / ADV",
    definition: "Your position size as a multiple of the stock's average daily trading volume.",
    formula: "Position / ADV = Position Shares / Average Daily Volume (shares)",
    example: "You hold 50,000 shares in a stock that trades 100,000 shares/day on average → Position/ADV = 0.5 days' worth of volume.",
    why: "A quick gut-check for how much of the day's liquidity your position represents — high values flag exit risk.",
  },
  marketImpact: {
    id: "marketImpact",
    label: "Market Impact",
    definition: "An estimate of how much your own trading would move the price, using a standard \"square-root\" market-impact model.",
    formula: "Market Impact (illustrative) ≈ k × Volatility × √(Position / ADV), k ≈ 1 (a common rule-of-thumb constant)",
    example: "A position that's 25% of ADV in a 30%-volatility stock might show an illustrative impact estimate of roughly 0.5% of price.",
    why: "This is a widely-used *model estimate*, not a measurement — this tracker has no real execution data, so treat this as illustrative only.",
  },
};

export const CATEGORY_TITLES: Record<string, string> = {
  performance: "Performance",
  riskAdjusted: "Risk-Adjusted Performance",
  marketRisk: "Market Risk",
  drawdown: "Drawdown",
  relativePerformance: "Relative Performance",
  portfolioConstruction: "Portfolio Construction",
  attribution: "Attribution",
  factor: "Factor",
  liquidity: "Liquidity / Execution",
};

export const CATEGORY_METRICS: Record<string, string[]> = {
  performance: ["absoluteReturn", "cagr", "twr", "mwrIrr", "rollingReturn", "activeReturn"],
  riskAdjusted: [
    "sharpe",
    "treynor",
    "sortino",
    "jensensAlpha",
    "informationRatio",
    "calmar",
    "sterling",
    "burke",
    "omega",
    "kappa",
    "m2",
    "appraisal",
  ],
  marketRisk: ["beta", "alpha", "volatility", "var", "cvar", "trackingError", "downsideDeviation"],
  drawdown: ["maxDrawdown", "avgDrawdown", "drawdownDuration", "recoveryPeriod", "recoveryFactor"],
  relativePerformance: [
    "activeShare",
    "informationRatio",
    "trackingError",
    "upsideCapture",
    "downsideCapture",
    "battingAverage",
  ],
  portfolioConstruction: [
    "concentration",
    "hhi",
    "effectiveHoldings",
    "grossExposure",
    "netExposure",
    "leverage",
    "cashPct",
  ],
  attribution: [
    "assetAllocation",
    "securitySelection",
    "sectorContribution",
    "stockContribution",
    "factorContribution",
    "currencyContribution",
  ],
  factor: ["factorValue", "factorGrowth", "factorMomentum", "factorQuality", "factorSize", "factorLowVol", "factorMarket"],
  liquidity: ["turnover", "bidAskSpread", "slippage", "implementationShortfall", "daysToLiquidate", "positionAdv", "marketImpact"],
};

export const OVERVIEW_METRICS = [
  "nav",
  "absoluteReturn",
  "benchmarkReturn",
  "activeReturn",
  "alpha",
  "sharpe",
  "sortino",
  "maxDrawdown",
  "volatility",
  "beta",
  "informationRatio",
  "trackingError",
  "activeShare",
  "concentration",
  "netExposure",
];
